-- =============================================================================
-- DENIAL CODES - CARC/RARC LOOKUP TABLES
-- Migration: 0015_add_denial_codes_carc_rarc.sql
-- Created: 2025-12-27
-- Description: Add CARC (Claim Adjustment Reason Codes) and RARC (Remittance
--              Advice Remark Codes) lookup tables for denial management
-- Compliance: HIPAA 835 standards, WPC/CMS code lists
-- =============================================================================

-- ============================================
-- TABLE 1: CARC CODES (Claim Adjustment Reason Codes)
-- ============================================
-- Purpose: Store standard CARC codes explaining claim adjustments/denials
-- Source: Washington Publishing Company (WPC) - Official HIPAA code maintainer
CREATE TABLE IF NOT EXISTS "carc_codes" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- CARC Code
  "code" varchar(10) UNIQUE NOT NULL,

  -- Code details
  "description" text NOT NULL,
  "short_description" varchar(255),

  -- Categorization
  "category" varchar(50) NOT NULL,
  "group_code" varchar(2) NOT NULL,

  -- Impact classification
  "is_denial" boolean DEFAULT false NOT NULL,
  "is_appealable" boolean DEFAULT true,
  "severity" varchar(20) DEFAULT 'MEDIUM',

  -- Recommended actions
  "recommended_action" text,
  "appeal_template" text,
  "documentation_required" jsonb,

  -- Analytics
  "common_payer_types" jsonb,
  "average_appeal_success_rate" bigint,

  -- Status
  "is_active" boolean DEFAULT true NOT NULL,
  "effective_date" timestamp,
  "termination_date" timestamp,

  -- Reference information
  "source" varchar(100) DEFAULT 'WPC',
  "source_url" text,
  "last_updated_from_source" timestamp,

  -- Notes
  "internal_notes" text,
  "examples" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_carc_codes_code" ON "carc_codes"("code");
CREATE INDEX IF NOT EXISTS "idx_carc_codes_category" ON "carc_codes"("category");
CREATE INDEX IF NOT EXISTS "idx_carc_codes_group" ON "carc_codes"("group_code");
CREATE INDEX IF NOT EXISTS "idx_carc_codes_appealable" ON "carc_codes"("is_appealable") WHERE "is_appealable" = true;
CREATE INDEX IF NOT EXISTS "idx_carc_codes_active" ON "carc_codes"("is_active") WHERE "is_active" = true;

-- ============================================
-- TABLE 2: RARC CODES (Remittance Advice Remark Codes)
-- ============================================
-- Purpose: Store standard RARC codes providing additional payment information
CREATE TABLE IF NOT EXISTS "rarc_codes" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- RARC Code
  "code" varchar(10) UNIQUE NOT NULL,

  -- Code details
  "description" text NOT NULL,
  "short_description" varchar(255),

  -- Categorization
  "code_type" varchar(50),

  -- Related information
  "related_carc_codes" jsonb,

  -- Recommended actions
  "recommended_action" text,
  "requires_provider_action" boolean DEFAULT false,

  -- Status
  "is_active" boolean DEFAULT true NOT NULL,
  "effective_date" timestamp,
  "termination_date" timestamp,

  -- Reference information
  "source" varchar(100) DEFAULT 'WPC',
  "source_url" text,
  "last_updated_from_source" timestamp,

  -- Notes
  "internal_notes" text,
  "examples" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_rarc_codes_code" ON "rarc_codes"("code");
CREATE INDEX IF NOT EXISTS "idx_rarc_codes_type" ON "rarc_codes"("code_type");
CREATE INDEX IF NOT EXISTS "idx_rarc_codes_action_required" ON "rarc_codes"("requires_provider_action") WHERE "requires_provider_action" = true;
CREATE INDEX IF NOT EXISTS "idx_rarc_codes_active" ON "rarc_codes"("is_active") WHERE "is_active" = true;

-- ============================================
-- TABLE 3: DENIAL CATEGORIES
-- ============================================
-- Purpose: Custom categorization for denial analytics and reporting
CREATE TABLE IF NOT EXISTS "denial_categories" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Category details
  "category_code" varchar(50) UNIQUE NOT NULL,
  "category_name" varchar(255) NOT NULL,
  "description" text,

  -- Hierarchy
  "parent_category_id" bigint REFERENCES "denial_categories"("id"),
  "level" bigint DEFAULT 1,

  -- Associated CARC codes
  "carc_codes" jsonb,

  -- Analytics settings
  "is_preventable" boolean DEFAULT true,
  "typical_resolution_time_days" bigint,

  -- Display settings
  "color_code" varchar(7),
  "icon" varchar(50),
  "sort_order" bigint DEFAULT 0,

  -- Status
  "is_active" boolean DEFAULT true NOT NULL,

  -- Notes
  "internal_notes" text,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_denial_categories_code" ON "denial_categories"("category_code");
CREATE INDEX IF NOT EXISTS "idx_denial_categories_parent" ON "denial_categories"("parent_category_id");
CREATE INDEX IF NOT EXISTS "idx_denial_categories_preventable" ON "denial_categories"("is_preventable");
CREATE INDEX IF NOT EXISTS "idx_denial_categories_active" ON "denial_categories"("is_active") WHERE "is_active" = true;

-- ============================================
-- TABLE 4: PAYER CODE MAPPINGS
-- ============================================
-- Purpose: Map payer-specific codes to standard CARC/RARC codes
CREATE TABLE IF NOT EXISTS "payer_code_mappings" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Payer information
  "payer_name" varchar(255) NOT NULL,
  "payer_identifier" varchar(50),

  -- Custom code
  "payer_code" varchar(50) NOT NULL,
  "payer_code_description" text,

  -- Standard mapping
  "standard_carc_code" varchar(10),
  "standard_rarc_code" varchar(10),
  "mapping_confidence" varchar(20) DEFAULT 'HIGH',

  -- Notes
  "mapping_notes" text,
  "verified_by" text,
  "verified_at" timestamp,

  -- Status
  "is_active" boolean DEFAULT true NOT NULL,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_payer_mappings_payer" ON "payer_code_mappings"("payer_name");
CREATE INDEX IF NOT EXISTS "idx_payer_mappings_code" ON "payer_code_mappings"("payer_code");
CREATE INDEX IF NOT EXISTS "idx_payer_mappings_carc" ON "payer_code_mappings"("standard_carc_code");
CREATE INDEX IF NOT EXISTS "idx_payer_mappings_active" ON "payer_code_mappings"("is_active") WHERE "is_active" = true;

-- ============================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================

COMMENT ON TABLE "carc_codes" IS 'Phase 3C: HIPAA standard Claim Adjustment Reason Codes (CARC) for denial tracking';
COMMENT ON TABLE "rarc_codes" IS 'Phase 3C: HIPAA standard Remittance Advice Remark Codes (RARC)';
COMMENT ON TABLE "denial_categories" IS 'Phase 3C: Custom denial categorization for analytics and reporting';
COMMENT ON TABLE "payer_code_mappings" IS 'Phase 3C: Map payer-specific codes to standard CARC/RARC codes';

-- ============================================
-- GRANT PERMISSIONS (if needed)
-- ============================================
-- Note: Adjust permissions based on your database setup
-- GRANT SELECT ON carc_codes TO billing_users;
-- GRANT SELECT ON rarc_codes TO billing_users;
-- GRANT SELECT, INSERT, UPDATE ON denial_categories TO billing_managers;
