-- =============================================================================
-- PHASE 3C: DENIAL MANAGEMENT & APPEAL TRACKING
-- Migration: 0016_add_denial_management_tables.sql
-- Created: 2025-12-27
-- Description: Complete denial workflow tracking, appeal management, and
--              denial analytics for comprehensive denial management system
-- Compliance: CMS appeal requirements, HIPAA standards
-- =============================================================================

-- ============================================
-- TABLE 1: CLAIM DENIALS
-- ============================================
-- Purpose: Master table tracking all denied or partially denied claims
CREATE TABLE IF NOT EXISTS "claim_denials" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Claim reference
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "payer_id" bigint REFERENCES "payers"("id"),

  -- Denial identification
  "denial_id" varchar(50) UNIQUE NOT NULL,
  "denial_date" date NOT NULL,

  -- ERA reference
  "era_payment_id" bigint REFERENCES "era_payments"("id"),
  "check_number" varchar(50),

  -- Denial type
  "denial_type" varchar(50) NOT NULL,
  "denial_status" varchar(50) DEFAULT 'IDENTIFIED' NOT NULL,

  -- Financial impact (in cents)
  "billed_amount" bigint NOT NULL,
  "denied_amount" bigint NOT NULL,
  "allowed_amount" bigint,
  "paid_amount" bigint,
  "adjustment_amount" bigint,

  -- Categorization
  "denial_category_id" bigint REFERENCES "denial_categories"("id"),
  "primary_denial_reason" varchar(10),

  -- Preventability
  "is_preventable" boolean,
  "preventable_reason" text,
  "root_cause" text,

  -- Appealability
  "is_appealable" boolean DEFAULT true,
  "appeal_deadline" date,
  "days_until_deadline" bigint,

  -- Appeal decision
  "will_appeal" boolean,
  "appeal_decision_date" date,
  "appeal_decision_by_id" text REFERENCES "users"("id"),
  "appeal_decision_reason" text,

  -- Assignment
  "assigned_to_id" text REFERENCES "users"("id"),
  "assigned_at" timestamp,
  "assigned_by_id" text REFERENCES "users"("id"),

  -- Resolution
  "resolved_date" date,
  "resolved_by_id" text REFERENCES "users"("id"),
  "resolution_type" varchar(50),
  "resolution_amount" bigint,
  "resolution_notes" text,

  -- Priority
  "priority_score" bigint,
  "priority_level" varchar(20),

  -- Education
  "requires_provider_education" boolean DEFAULT false,
  "education_completed" boolean DEFAULT false,
  "education_notes" text,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "identified_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_claim_denials_claim" ON "claim_denials"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_claim_denials_patient" ON "claim_denials"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_claim_denials_payer" ON "claim_denials"("payer_id");
CREATE INDEX IF NOT EXISTS "idx_claim_denials_status" ON "claim_denials"("denial_status");
CREATE INDEX IF NOT EXISTS "idx_claim_denials_category" ON "claim_denials"("denial_category_id");
CREATE INDEX IF NOT EXISTS "idx_claim_denials_assigned" ON "claim_denials"("assigned_to_id");
CREATE INDEX IF NOT EXISTS "idx_claim_denials_deadline" ON "claim_denials"("appeal_deadline") WHERE "appeal_deadline" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_claim_denials_priority" ON "claim_denials"("priority_level");
CREATE INDEX IF NOT EXISTS "idx_claim_denials_date" ON "claim_denials"("denial_date");

-- ============================================
-- TABLE 2: DENIAL REASONS
-- ============================================
-- Purpose: Link denials to specific CARC/RARC codes
CREATE TABLE IF NOT EXISTS "denial_reasons" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "denial_id" bigint NOT NULL REFERENCES "claim_denials"("id") ON DELETE CASCADE,

  -- Code references
  "carc_code_id" bigint REFERENCES "carc_codes"("id"),
  "carc_code" varchar(10) NOT NULL,
  "rarc_codes" jsonb,

  -- Adjustment details
  "group_code" varchar(2) NOT NULL,
  "adjustment_amount" bigint,
  "adjustment_quantity" decimal(10, 2),

  -- Service line reference
  "service_line_number" bigint,
  "procedure_code" varchar(20),
  "service_date" date,

  -- Details
  "payer_explanation" text,
  "is_primary_reason" boolean DEFAULT false,
  "is_appealable" boolean,
  "recommended_action" text,

  -- Metadata
  "metadata" jsonb,

  -- Audit
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_denial_reasons_denial" ON "denial_reasons"("denial_id");
CREATE INDEX IF NOT EXISTS "idx_denial_reasons_carc" ON "denial_reasons"("carc_code");
CREATE INDEX IF NOT EXISTS "idx_denial_reasons_primary" ON "denial_reasons"("is_primary_reason") WHERE "is_primary_reason" = true;

-- ============================================
-- TABLE 3: APPEAL CASES
-- ============================================
-- Purpose: Track appeal submissions and outcomes
CREATE TABLE IF NOT EXISTS "appeal_cases" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Appeal identification
  "appeal_id" varchar(50) UNIQUE NOT NULL,
  "denial_id" bigint NOT NULL REFERENCES "claim_denials"("id"),
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),

  -- Appeal level
  "appeal_level" varchar(50) NOT NULL,
  "appeal_type" varchar(50),

  -- Submission
  "submitted_date" date,
  "submitted_by_id" text REFERENCES "users"("id"),
  "submission_method" varchar(50),
  "tracking_number" varchar(100),
  "confirmation_number" varchar(100),

  -- Deadlines
  "original_deadline" date NOT NULL,
  "extended_deadline" date,
  "payer_response_deadline" date,

  -- Status
  "appeal_status" varchar(50) DEFAULT 'PREPARING' NOT NULL,
  "current_step" varchar(100),
  "status_date" timestamp DEFAULT now() NOT NULL,

  -- Outcome
  "decision_date" date,
  "decision_type" varchar(50),
  "decision_reason" text,
  "decision_received_date" date,

  -- Financial (in cents)
  "appealed_amount" bigint NOT NULL,
  "recovered_amount" bigint,
  "final_denied_amount" bigint,

  -- Supporting info
  "appeal_basis" text NOT NULL,
  "medical_necessity_rationale" text,
  "policy_reference" text,

  -- Contact
  "appeal_contact_name" varchar(255),
  "appeal_contact_phone" varchar(20),
  "appeal_contact_email" varchar(255),

  -- Next steps
  "next_appeal_level" varchar(50),
  "will_escalate" boolean,
  "escalation_deadline" date,

  -- Communication
  "communication_log" jsonb,

  -- Documents
  "has_medical_records" boolean DEFAULT false,
  "has_clinical_notes" boolean DEFAULT false,
  "has_physician_statement" boolean DEFAULT false,
  "has_policy_documentation" boolean DEFAULT false,

  -- Assignment
  "assigned_to_id" text REFERENCES "users"("id"),
  "assigned_at" timestamp,

  -- Metrics
  "preparation_time_days" bigint,
  "decision_time_days" bigint,
  "total_cycle_time_days" bigint,

  -- Metadata
  "metadata" jsonb,
  "internal_notes" text,

  -- Audit
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_appeal_cases_denial" ON "appeal_cases"("denial_id");
CREATE INDEX IF NOT EXISTS "idx_appeal_cases_claim" ON "appeal_cases"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_appeal_cases_status" ON "appeal_cases"("appeal_status");
CREATE INDEX IF NOT EXISTS "idx_appeal_cases_level" ON "appeal_cases"("appeal_level");
CREATE INDEX IF NOT EXISTS "idx_appeal_cases_assigned" ON "appeal_cases"("assigned_to_id");
CREATE INDEX IF NOT EXISTS "idx_appeal_cases_deadline" ON "appeal_cases"("original_deadline");
CREATE INDEX IF NOT EXISTS "idx_appeal_cases_submitted" ON "appeal_cases"("submitted_date");

-- ============================================
-- TABLE 4: APPEAL DOCUMENTS
-- ============================================
-- Purpose: Track appeal supporting documents
CREATE TABLE IF NOT EXISTS "appeal_documents" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "appeal_id" bigint NOT NULL REFERENCES "appeal_cases"("id") ON DELETE CASCADE,

  -- Document details
  "document_type" varchar(50) NOT NULL,
  "document_name" varchar(255) NOT NULL,
  "document_description" text,

  -- File info
  "file_path" text,
  "file_url" text,
  "file_size" bigint,
  "file_type" varchar(50),
  "mime_type" varchar(100),

  -- Metadata
  "document_date" date,
  "author" varchar(255),
  "is_required" boolean DEFAULT false,
  "is_submitted" boolean DEFAULT false,
  "submitted_date" timestamp,

  -- Version control
  "version" bigint DEFAULT 1,
  "supersedes_document_id" bigint,

  -- Security
  "is_sensitive" boolean DEFAULT true,
  "access_restricted" boolean DEFAULT false,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "uploaded_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_appeal_documents_appeal" ON "appeal_documents"("appeal_id");
CREATE INDEX IF NOT EXISTS "idx_appeal_documents_type" ON "appeal_documents"("document_type");
CREATE INDEX IF NOT EXISTS "idx_appeal_documents_required" ON "appeal_documents"("is_required") WHERE "is_required" = true;

-- ============================================
-- TABLE 5: APPEAL TIMELINE
-- ============================================
-- Purpose: Track milestones in appeal process
CREATE TABLE IF NOT EXISTS "appeal_timeline" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "appeal_id" bigint NOT NULL REFERENCES "appeal_cases"("id") ON DELETE CASCADE,

  -- Milestone
  "milestone_type" varchar(50) NOT NULL,
  "milestone_date" timestamp DEFAULT now() NOT NULL,
  "due_date" date,

  -- Status
  "is_completed" boolean DEFAULT true,
  "completed_on_time" boolean,
  "days_overdue" bigint,

  -- Details
  "description" text NOT NULL,
  "responsible_party" varchar(255),
  "action_taken" text,

  -- Notifications
  "notification_sent" boolean DEFAULT false,
  "notification_date" timestamp,

  -- Metadata
  "metadata" jsonb,

  -- Audit
  "created_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_appeal_timeline_appeal" ON "appeal_timeline"("appeal_id");
CREATE INDEX IF NOT EXISTS "idx_appeal_timeline_type" ON "appeal_timeline"("milestone_type");
CREATE INDEX IF NOT EXISTS "idx_appeal_timeline_date" ON "appeal_timeline"("milestone_date");

-- ============================================
-- TABLE 6: DENIAL ANALYTICS
-- ============================================
-- Purpose: Pre-calculated denial metrics for reporting
CREATE TABLE IF NOT EXISTS "denial_analytics" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Time period
  "period_type" varchar(20) NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,

  -- Dimensions
  "payer_id" bigint REFERENCES "payers"("id"),
  "denial_category_id" bigint REFERENCES "denial_categories"("id"),
  "carc_code" varchar(10),

  -- Volume metrics
  "total_denials" bigint DEFAULT 0,
  "full_denials" bigint DEFAULT 0,
  "partial_denials" bigint DEFAULT 0,
  "preventable_denials" bigint DEFAULT 0,

  -- Financial (in cents)
  "total_denied_amount" bigint DEFAULT 0,
  "total_appealed_amount" bigint DEFAULT 0,
  "total_recovered_amount" bigint DEFAULT 0,
  "total_written_off_amount" bigint DEFAULT 0,

  -- Appeal metrics
  "total_appeals" bigint DEFAULT 0,
  "appeals_won" bigint DEFAULT 0,
  "appeals_lost" bigint DEFAULT 0,
  "appeals_pending" bigint DEFAULT 0,

  -- Rates (0-10000 = 0.00%-100.00%)
  "denial_rate" bigint,
  "appeal_rate" bigint,
  "appeal_success_rate" bigint,
  "preventable_rate" bigint,
  "recovery_rate" bigint,

  -- Timing (days)
  "avg_appeal_cycle_time" bigint,
  "avg_time_to_appeal" bigint,
  "avg_decision_time" bigint,

  -- Trending
  "trend_direction" varchar(10),
  "trend_percentage" bigint,

  -- Metadata
  "calculation_date" timestamp DEFAULT now() NOT NULL,
  "metadata" jsonb,

  -- Audit
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_denial_analytics_period" ON "denial_analytics"("period_type", "period_start", "period_end");
CREATE INDEX IF NOT EXISTS "idx_denial_analytics_payer" ON "denial_analytics"("payer_id");
CREATE INDEX IF NOT EXISTS "idx_denial_analytics_category" ON "denial_analytics"("denial_category_id");
CREATE INDEX IF NOT EXISTS "idx_denial_analytics_carc" ON "denial_analytics"("carc_code");

-- ============================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================

COMMENT ON TABLE "claim_denials" IS 'Phase 3C: Master table tracking all denied claims with workflow status';
COMMENT ON TABLE "denial_reasons" IS 'Phase 3C: Links denials to specific CARC/RARC codes with adjustment details';
COMMENT ON TABLE "appeal_cases" IS 'Phase 3C: Tracks appeal submissions, status, and outcomes';
COMMENT ON TABLE "appeal_documents" IS 'Phase 3C: Stores references to appeal supporting documents';
COMMENT ON TABLE "appeal_timeline" IS 'Phase 3C: Tracks milestones and deadlines in appeal process';
COMMENT ON TABLE "denial_analytics" IS 'Phase 3C: Pre-calculated denial metrics for dashboard and reporting';
