-- Migration: Add Billing Module Tables
-- Module G - HIGH Priority
-- Created: 2024-12-27
-- Purpose: Claims, payments, NOE, AR aging for revenue cycle management

-- ============================================
-- PAYERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "payers" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "payer_name" varchar(255) NOT NULL,
  "payer_type" varchar(50),
  "payer_id" varchar(100),
  "address_line1" varchar(255),
  "address_line2" varchar(255),
  "city" varchar(100),
  "state" varchar(2),
  "zip_code" varchar(10),
  "phone" varchar(50),
  "fax" varchar(50),
  "email" varchar(255),
  "contact_name" varchar(255),
  "electronic_billing_enabled" boolean DEFAULT false,
  "clearinghouse" varchar(100),
  "is_active" boolean DEFAULT true NOT NULL,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- NOTICE OF ELECTION (NOE) TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "notice_of_election" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "noe_date" date NOT NULL,
  "effective_date" date NOT NULL,
  "noe_status" varchar(50) DEFAULT 'PENDING' NOT NULL,
  "noe_timeliness" varchar(50),
  "benefit_period" varchar(50),
  "submission_date" date,
  "acceptance_date" date,
  "rejection_date" date,
  "rejection_reason" text,
  "noe_control_number" varchar(100),
  "payer_id" bigint REFERENCES "payers"("id"),
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- CLAIMS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "claims" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "payer_id" bigint REFERENCES "payers"("id"),
  "claim_number" varchar(100) UNIQUE,
  "claim_type" varchar(50),
  "claim_status" varchar(50) DEFAULT 'DRAFT' NOT NULL,
  "service_start_date" date NOT NULL,
  "service_end_date" date NOT NULL,
  "bill_type" varchar(4),
  "total_charges" integer,
  "total_paid" integer,
  "total_adjustments" integer,
  "balance" integer,
  "submission_date" date,
  "submission_method" varchar(50),
  "clearinghouse_trace_number" varchar(100),
  "paid_date" date,
  "check_number" varchar(100),
  "denial_reason" text,
  "denial_date" date,
  "notes" text,
  "metadata" jsonb,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- CLAIM SERVICE LINES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "claim_service_lines" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "line_number" integer NOT NULL,
  "service_date" date NOT NULL,
  "revenue_code" varchar(4) NOT NULL,
  "level_of_care" varchar(50),
  "units" integer NOT NULL,
  "charges" integer NOT NULL,
  "hcpcs_code" varchar(10),
  "allowed_amount" integer,
  "paid_amount" integer,
  "adjustment_amount" integer,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- PAYMENTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "payments" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "payer_id" bigint REFERENCES "payers"("id"),
  "payment_date" date NOT NULL,
  "payment_amount" integer NOT NULL,
  "payment_method" varchar(50),
  "payment_status" varchar(50) DEFAULT 'PENDING' NOT NULL,
  "check_number" varchar(100),
  "reference_number" varchar(100),
  "deposit_date" date,
  "deposit_account" varchar(100),
  "unapplied_amount" integer,
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- PAYMENT APPLICATIONS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "payment_applications" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "payment_id" bigint NOT NULL REFERENCES "payments"("id"),
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "applied_amount" integer NOT NULL,
  "adjustment_amount" integer,
  "write_off_amount" integer,
  "adjustment_reason_codes" jsonb,
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- BILLING PERIODS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "billing_periods" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "level_of_care" varchar(50) NOT NULL,
  "billed" boolean DEFAULT false NOT NULL,
  "claim_id" bigint REFERENCES "claims"("id"),
  "expected_revenue" integer,
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- AR AGING TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "ar_aging" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "balance" integer NOT NULL,
  "days_outstanding" integer,
  "aging_bucket" varchar(50),
  "calculated_date" date NOT NULL,
  "calculation_basis" varchar(50),
  "follow_up_required" boolean DEFAULT false,
  "follow_up_date" date,
  "follow_up_notes" text,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- CONTRACTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "contracts" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "payer_id" bigint NOT NULL REFERENCES "payers"("id"),
  "contract_name" varchar(255),
  "contract_number" varchar(100),
  "effective_date" date NOT NULL,
  "termination_date" date,
  "auto_renew" boolean DEFAULT false,
  "renewal_notice_days" integer,
  "rates" jsonb,
  "payment_terms" varchar(100),
  "contract_type" varchar(50),
  "is_active" boolean DEFAULT true NOT NULL,
  "notes" text,
  "contract_document_url" text,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

-- Payers indexes
CREATE INDEX IF NOT EXISTS "idx_payers_type" ON "payers"("payer_type");
CREATE INDEX IF NOT EXISTS "idx_payers_active" ON "payers"("is_active");

-- NOE indexes
CREATE INDEX IF NOT EXISTS "idx_noe_patient" ON "notice_of_election"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_noe_status" ON "notice_of_election"("noe_status");
CREATE INDEX IF NOT EXISTS "idx_noe_effective_date" ON "notice_of_election"("effective_date");

-- Claims indexes
CREATE INDEX IF NOT EXISTS "idx_claims_patient" ON "claims"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_claims_payer" ON "claims"("payer_id");
CREATE INDEX IF NOT EXISTS "idx_claims_status" ON "claims"("claim_status");
CREATE INDEX IF NOT EXISTS "idx_claims_service_dates" ON "claims"("service_start_date", "service_end_date");
CREATE INDEX IF NOT EXISTS "idx_claims_number" ON "claims"("claim_number");

-- Claim service lines indexes
CREATE INDEX IF NOT EXISTS "idx_claim_lines_claim" ON "claim_service_lines"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_claim_lines_date" ON "claim_service_lines"("service_date");

-- Payments indexes
CREATE INDEX IF NOT EXISTS "idx_payments_payer" ON "payments"("payer_id");
CREATE INDEX IF NOT EXISTS "idx_payments_status" ON "payments"("payment_status");
CREATE INDEX IF NOT EXISTS "idx_payments_date" ON "payments"("payment_date");

-- Payment applications indexes
CREATE INDEX IF NOT EXISTS "idx_payment_apps_payment" ON "payment_applications"("payment_id");
CREATE INDEX IF NOT EXISTS "idx_payment_apps_claim" ON "payment_applications"("claim_id");

-- Billing periods indexes
CREATE INDEX IF NOT EXISTS "idx_billing_periods_patient" ON "billing_periods"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_billing_periods_billed" ON "billing_periods"("billed");
CREATE INDEX IF NOT EXISTS "idx_billing_periods_dates" ON "billing_periods"("period_start", "period_end");

-- AR aging indexes
CREATE INDEX IF NOT EXISTS "idx_ar_aging_claim" ON "ar_aging"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_ar_aging_bucket" ON "ar_aging"("aging_bucket");
CREATE INDEX IF NOT EXISTS "idx_ar_aging_follow_up" ON "ar_aging"("follow_up_required");

-- Contracts indexes
CREATE INDEX IF NOT EXISTS "idx_contracts_payer" ON "contracts"("payer_id");
CREATE INDEX IF NOT EXISTS "idx_contracts_active" ON "contracts"("is_active");
CREATE INDEX IF NOT EXISTS "idx_contracts_dates" ON "contracts"("effective_date", "termination_date");
