-- Migration: Add Staff Management Module Tables
-- Module H - MEDIUM Priority
-- Created: 2024-12-27
-- Purpose: Employee tracking, credential expiration alerts, caseload management

-- ============================================
-- STAFF PROFILES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "staff_profiles" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text UNIQUE REFERENCES "user"("id"),
  "employee_id" varchar(50) UNIQUE,
  "first_name" varchar(255) NOT NULL,
  "last_name" varchar(255) NOT NULL,
  "middle_name" varchar(255),
  "preferred_name" varchar(255),
  "job_title" varchar(255),
  "department" varchar(100),
  "employment_type" varchar(50),
  "hire_date" date,
  "termination_date" date,
  "employment_status" varchar(50) DEFAULT 'ACTIVE' NOT NULL,
  "email" varchar(255),
  "phone" varchar(50),
  "mobile" varchar(50),
  "emergency_contact_name" varchar(255),
  "emergency_contact_phone" varchar(50),
  "emergency_contact_relationship" varchar(100),
  "address_line1" varchar(255),
  "address_line2" varchar(255),
  "city" varchar(100),
  "state" varchar(2),
  "zip_code" varchar(10),
  "specialty" varchar(255),
  "years_of_experience" integer,
  "is_supervisory" boolean DEFAULT false,
  "service_territory" jsonb,
  "max_patient_load" integer,
  "notes" text,
  "metadata" jsonb,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- STAFF CREDENTIALS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "staff_credentials" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "staff_id" bigint NOT NULL REFERENCES "staff_profiles"("id"),
  "credential_type" varchar(100) NOT NULL,
  "credential_name" varchar(255) NOT NULL,
  "credential_number" varchar(100),
  "issuing_authority" varchar(255),
  "issuing_state" varchar(2),
  "issue_date" date,
  "expiration_date" date NOT NULL,
  "verification_date" date,
  "credential_status" varchar(50) DEFAULT 'ACTIVE' NOT NULL,
  "alert_days_before_expiration" integer DEFAULT 30,
  "renewal_reminder_sent" boolean DEFAULT false,
  "document_url" text,
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- STAFF CASELOAD TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "staff_caseload" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "staff_id" bigint NOT NULL REFERENCES "staff_profiles"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "assignment_role" varchar(100) NOT NULL,
  "is_primary" boolean DEFAULT false,
  "assignment_start_date" date NOT NULL,
  "assignment_end_date" date,
  "assignment_status" varchar(50) DEFAULT 'ACTIVE' NOT NULL,
  "scheduled_visits_per_week" integer,
  "actual_visits_this_week" integer DEFAULT 0,
  "transfer_reason" text,
  "transferred_to_staff_id" bigint REFERENCES "staff_profiles"("id"),
  "transfer_date" date,
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- STAFF SCHEDULE TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "staff_schedule" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "staff_id" bigint NOT NULL REFERENCES "staff_profiles"("id"),
  "schedule_type" varchar(50) NOT NULL,
  "shift_date" date NOT NULL,
  "start_time" timestamp,
  "end_time" timestamp,
  "is_on_call" boolean DEFAULT false,
  "on_call_type" varchar(50),
  "time_off_type" varchar(50),
  "time_off_status" varchar(50),
  "approved_by_id" text REFERENCES "user"("id"),
  "approval_date" date,
  "work_location" varchar(255),
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- STAFF PRODUCTIVITY TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "staff_productivity" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "staff_id" bigint NOT NULL REFERENCES "staff_profiles"("id"),
  "reporting_period_start" date NOT NULL,
  "reporting_period_end" date NOT NULL,
  "period_type" varchar(50),
  "total_visits_scheduled" integer DEFAULT 0,
  "total_visits_completed" integer DEFAULT 0,
  "total_visits_missed" integer DEFAULT 0,
  "total_visit_time_minutes" integer DEFAULT 0,
  "average_visit_duration_minutes" integer,
  "total_patients_assigned" integer DEFAULT 0,
  "new_admissions" integer DEFAULT 0,
  "discharges" integer DEFAULT 0,
  "notes_completed_on_time" integer DEFAULT 0,
  "notes_completed_late" integer DEFAULT 0,
  "average_documentation_time_hours" decimal(5,2),
  "patient_satisfaction_score" decimal(3,2),
  "quality_score" decimal(5,2),
  "compliance_incidents" integer DEFAULT 0,
  "safety_incidents" integer DEFAULT 0,
  "metrics_data" jsonb,
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- STAFF TRAINING TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "staff_training" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "staff_id" bigint NOT NULL REFERENCES "staff_profiles"("id"),
  "training_name" varchar(255) NOT NULL,
  "training_type" varchar(100) NOT NULL,
  "training_category" varchar(100),
  "training_provider" varchar(255),
  "instructor_name" varchar(255),
  "training_date" date NOT NULL,
  "completion_date" date,
  "expiration_date" date,
  "training_status" varchar(50) DEFAULT 'SCHEDULED' NOT NULL,
  "hours_completed" decimal(5,2),
  "ceu_credits" decimal(5,2),
  "score" decimal(5,2),
  "passing_score" decimal(5,2),
  "passed" boolean,
  "certificate_number" varchar(100),
  "certificate_url" text,
  "is_required" boolean DEFAULT false,
  "due_date" date,
  "notes" text,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

-- Staff profiles indexes
CREATE INDEX IF NOT EXISTS "idx_staff_profiles_user" ON "staff_profiles"("user_id");
CREATE INDEX IF NOT EXISTS "idx_staff_profiles_employee_id" ON "staff_profiles"("employee_id");
CREATE INDEX IF NOT EXISTS "idx_staff_profiles_status" ON "staff_profiles"("employment_status");
CREATE INDEX IF NOT EXISTS "idx_staff_profiles_department" ON "staff_profiles"("department");
CREATE INDEX IF NOT EXISTS "idx_staff_profiles_name" ON "staff_profiles"("last_name", "first_name");

-- Staff credentials indexes
CREATE INDEX IF NOT EXISTS "idx_staff_credentials_staff" ON "staff_credentials"("staff_id");
CREATE INDEX IF NOT EXISTS "idx_staff_credentials_type" ON "staff_credentials"("credential_type");
CREATE INDEX IF NOT EXISTS "idx_staff_credentials_expiration" ON "staff_credentials"("expiration_date");
CREATE INDEX IF NOT EXISTS "idx_staff_credentials_status" ON "staff_credentials"("credential_status");

-- Staff caseload indexes
CREATE INDEX IF NOT EXISTS "idx_staff_caseload_staff" ON "staff_caseload"("staff_id");
CREATE INDEX IF NOT EXISTS "idx_staff_caseload_patient" ON "staff_caseload"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_staff_caseload_status" ON "staff_caseload"("assignment_status");
CREATE INDEX IF NOT EXISTS "idx_staff_caseload_primary" ON "staff_caseload"("is_primary");

-- Staff schedule indexes
CREATE INDEX IF NOT EXISTS "idx_staff_schedule_staff" ON "staff_schedule"("staff_id");
CREATE INDEX IF NOT EXISTS "idx_staff_schedule_date" ON "staff_schedule"("shift_date");
CREATE INDEX IF NOT EXISTS "idx_staff_schedule_type" ON "staff_schedule"("schedule_type");
CREATE INDEX IF NOT EXISTS "idx_staff_schedule_on_call" ON "staff_schedule"("is_on_call");

-- Staff productivity indexes
CREATE INDEX IF NOT EXISTS "idx_staff_productivity_staff" ON "staff_productivity"("staff_id");
CREATE INDEX IF NOT EXISTS "idx_staff_productivity_period" ON "staff_productivity"("reporting_period_start", "reporting_period_end");
CREATE INDEX IF NOT EXISTS "idx_staff_productivity_type" ON "staff_productivity"("period_type");

-- Staff training indexes
CREATE INDEX IF NOT EXISTS "idx_staff_training_staff" ON "staff_training"("staff_id");
CREATE INDEX IF NOT EXISTS "idx_staff_training_type" ON "staff_training"("training_type");
CREATE INDEX IF NOT EXISTS "idx_staff_training_status" ON "staff_training"("training_status");
CREATE INDEX IF NOT EXISTS "idx_staff_training_date" ON "staff_training"("training_date");
CREATE INDEX IF NOT EXISTS "idx_staff_training_expiration" ON "staff_training"("expiration_date");
CREATE INDEX IF NOT EXISTS "idx_staff_training_required" ON "staff_training"("is_required");
