-- Migration: Add Phase 1 Critical Compliance Features
-- Created: 2025-12-27
-- Purpose: Cap tracking, certification workflow enhancements, UB-04 complete fields
-- Compliance: CMS Medicare hospice requirements

-- ============================================
-- CAP TRACKING TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "cap_tracking" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Cap year (Oct 1 - Sep 30)
  "cap_year" integer NOT NULL,
  "cap_year_start_date" date NOT NULL,
  "cap_year_end_date" date NOT NULL,

  -- Cap amount (in cents for precision)
  "cap_amount_cents" integer NOT NULL,
  "total_payments_cents" integer DEFAULT 0 NOT NULL,
  "remaining_cap_cents" integer NOT NULL,

  -- Cap utilization percentage
  "utilization_percentage" numeric(5,2) DEFAULT 0,

  -- Cap exceeded tracking
  "cap_exceeded" boolean DEFAULT false NOT NULL,
  "cap_exceeded_date" date,
  "cap_exceeded_amount_cents" integer,

  -- Alert thresholds tracking
  "alert_80_triggered" boolean DEFAULT false,
  "alert_80_date" timestamp,
  "alert_90_triggered" boolean DEFAULT false,
  "alert_90_date" timestamp,
  "alert_95_triggered" boolean DEFAULT false,
  "alert_95_date" timestamp,

  -- Calculation tracking
  "last_calculated_at" timestamp,
  "calculation_status" varchar(50) DEFAULT 'CURRENT',

  -- Notes and metadata
  "notes" text,
  "metadata" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,

  UNIQUE("patient_id", "cap_year")
);

-- ============================================
-- CERTIFICATION ALERTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "certification_alerts" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "certification_id" bigint NOT NULL REFERENCES "certifications"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Alert details
  "alert_type" varchar(50) NOT NULL,
  "alert_priority" varchar(50) DEFAULT 'NORMAL',

  -- Timing
  "scheduled_for" timestamp NOT NULL,
  "sent_at" timestamp,
  "alert_status" varchar(50) DEFAULT 'PENDING',

  -- Recipients
  "recipients" jsonb,

  -- Alert content
  "subject" varchar(255),
  "message" text,
  "metadata" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- ALTER CERTIFICATIONS TABLE
-- ============================================
ALTER TABLE "certifications"
  ADD COLUMN IF NOT EXISTS "certification_due_date" date,
  ADD COLUMN IF NOT EXISTS "certification_completed_date" date,
  ADD COLUMN IF NOT EXISTS "certification_timeliness" varchar(50),
  ADD COLUMN IF NOT EXISTS "days_late" integer,
  ADD COLUMN IF NOT EXISTS "noe_id" bigint REFERENCES "notice_of_election"("id");

-- ============================================
-- ALTER CLAIMS TABLE - UB-04 FIELDS
-- ============================================
ALTER TABLE "claims"
  ADD COLUMN IF NOT EXISTS "occurrence_codes" jsonb,
  ADD COLUMN IF NOT EXISTS "value_codes" jsonb,
  ADD COLUMN IF NOT EXISTS "condition_codes" varchar(2)[],
  ADD COLUMN IF NOT EXISTS "attending_physician_npi" varchar(10),
  ADD COLUMN IF NOT EXISTS "attending_physician_name" varchar(255),
  ADD COLUMN IF NOT EXISTS "attending_physician_qualifier" varchar(2),
  ADD COLUMN IF NOT EXISTS "operating_physician_npi" varchar(10),
  ADD COLUMN IF NOT EXISTS "operating_physician_name" varchar(255),
  ADD COLUMN IF NOT EXISTS "other_physician_npi" varchar(10),
  ADD COLUMN IF NOT EXISTS "other_physician_name" varchar(255),
  ADD COLUMN IF NOT EXISTS "admission_date" date,
  ADD COLUMN IF NOT EXISTS "admission_hour" varchar(2),
  ADD COLUMN IF NOT EXISTS "admission_type" varchar(1),
  ADD COLUMN IF NOT EXISTS "admission_source" varchar(1),
  ADD COLUMN IF NOT EXISTS "discharge_status" varchar(2),
  ADD COLUMN IF NOT EXISTS "discharge_hour" varchar(2),
  ADD COLUMN IF NOT EXISTS "statement_from_date" date,
  ADD COLUMN IF NOT EXISTS "statement_to_date" date,
  ADD COLUMN IF NOT EXISTS "principal_diagnosis_code" varchar(10),
  ADD COLUMN IF NOT EXISTS "principal_diagnosis_qualifier" varchar(2),
  ADD COLUMN IF NOT EXISTS "other_diagnosis_codes" jsonb,
  ADD COLUMN IF NOT EXISTS "patient_reason_diagnosis" jsonb,
  ADD COLUMN IF NOT EXISTS "external_cause_injury_codes" varchar(10)[],
  ADD COLUMN IF NOT EXISTS "remarks" text,
  ADD COLUMN IF NOT EXISTS "document_control_number" varchar(23),
  ADD COLUMN IF NOT EXISTS "employer_name" varchar(255),
  ADD COLUMN IF NOT EXISTS "treatment_authorization_codes" varchar(30);

-- ============================================
-- INDEXES FOR CAP TRACKING
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_patient" ON "cap_tracking"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_year" ON "cap_tracking"("cap_year");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_exceeded" ON "cap_tracking"("cap_exceeded");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_utilization" ON "cap_tracking"("utilization_percentage");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_alerts" ON "cap_tracking"("alert_80_triggered", "alert_90_triggered", "alert_95_triggered");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_calculation" ON "cap_tracking"("last_calculated_at", "calculation_status");

-- ============================================
-- INDEXES FOR CERTIFICATION ALERTS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_cert_alerts_certification" ON "certification_alerts"("certification_id");
CREATE INDEX IF NOT EXISTS "idx_cert_alerts_patient" ON "certification_alerts"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_cert_alerts_status" ON "certification_alerts"("alert_status");
CREATE INDEX IF NOT EXISTS "idx_cert_alerts_scheduled" ON "certification_alerts"("scheduled_for");
CREATE INDEX IF NOT EXISTS "idx_cert_alerts_type" ON "certification_alerts"("alert_type");

-- ============================================
-- INDEXES FOR CERTIFICATION ENHANCEMENTS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_certifications_due_date" ON "certifications"("certification_due_date");
CREATE INDEX IF NOT EXISTS "idx_certifications_timeliness" ON "certifications"("certification_timeliness");
CREATE INDEX IF NOT EXISTS "idx_certifications_noe" ON "certifications"("noe_id");

-- ============================================
-- INDEXES FOR UB-04 FIELDS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_claims_admission_date" ON "claims"("admission_date");
CREATE INDEX IF NOT EXISTS "idx_claims_attending_npi" ON "claims"("attending_physician_npi");
CREATE INDEX IF NOT EXISTS "idx_claims_principal_dx" ON "claims"("principal_diagnosis_code");
CREATE INDEX IF NOT EXISTS "idx_claims_discharge_status" ON "claims"("discharge_status");
