-- =============================================================================
-- PHASE 2 ELECTRONIC SUBMISSION & ENHANCED VALIDATION
-- Migration: 0013_add_phase2_submission_features.sql
-- Created: 2025-12-27
-- Description: Add CBSA tracking, claim scrubbing, clearinghouse submissions,
--              and enhanced validation features
-- Compliance: CMS Medicare hospice electronic submission requirements
-- =============================================================================

-- ============================================
-- TABLE 1: CBSA CODES LOOKUP
-- ============================================
-- Purpose: Store ZIP code to CBSA mapping for automatic Value Code 61/G8 population
-- CMS Requirement: Track Core Based Statistical Area for UB-04 Value Codes
CREATE TABLE IF NOT EXISTS "cbsa_codes" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- ZIP to CBSA mapping
  "zip_code" varchar(5) NOT NULL,
  "cbsa_code" varchar(5) NOT NULL,
  "cbsa_title" varchar(255) NOT NULL,

  -- Geographic details
  "state" varchar(2) NOT NULL,
  "county" varchar(100),
  "metropolitan_division" varchar(5),

  -- Classification
  "is_metropolitan" boolean DEFAULT true NOT NULL,
  "population" integer,

  -- Effective dates (for annual updates)
  "effective_date" date DEFAULT '2024-01-01' NOT NULL,
  "expiration_date" date,

  -- Metadata
  "notes" text,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,

  UNIQUE("zip_code", "effective_date")
);

-- ============================================
-- TABLE 2: CLEARINGHOUSE SUBMISSIONS
-- ============================================
-- Purpose: Track 837I EDI file submissions and acknowledgments
-- CMS Requirement: Electronic claim submission tracking
CREATE TABLE IF NOT EXISTS "clearinghouse_submissions" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),

  -- Submission details
  "submission_batch_id" varchar(100),
  "submission_date" timestamp NOT NULL,
  "submission_method" varchar(50) DEFAULT 'EDI_FILE' NOT NULL,

  -- File information
  "edi_file_name" varchar(255),
  "edi_file_path" text,
  "edi_control_number" varchar(50),
  "edi_content" text,

  -- Clearinghouse details
  "clearinghouse_name" varchar(100),
  "clearinghouse_id" varchar(50),

  -- Acknowledgment tracking (277)
  "acknowledgment_status" varchar(50),
  "acknowledgment_date" timestamp,
  "acknowledgment_details" jsonb,

  -- Status tracking
  "current_status" varchar(50) DEFAULT 'SUBMITTED' NOT NULL,
  "status_date" timestamp DEFAULT now() NOT NULL,

  -- Error tracking
  "errors" jsonb,
  "warnings" jsonb,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- TABLE 3: CLAIM VALIDATION RESULTS
-- ============================================
-- Purpose: Store comprehensive validation results for audit trail
-- CMS Requirement: Pre-submission validation tracking
CREATE TABLE IF NOT EXISTS "claim_validation_results" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),

  -- Validation details
  "validation_date" timestamp DEFAULT now() NOT NULL,
  "validation_type" varchar(50) NOT NULL,

  -- Results
  "passed" boolean NOT NULL,
  "errors" jsonb,
  "warnings" jsonb,

  -- Field-level details
  "fields_validated" integer,
  "fields_passed" integer,
  "fields_failed" integer,

  -- Scrubbing actions
  "data_corrections" jsonb,
  "auto_fixed" boolean DEFAULT false,

  -- Metadata
  "validator_version" varchar(20),
  "rules_applied" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- ENHANCEMENT 1: CLAIM SERVICE LINES - ADD CBSA FIELDS
-- ============================================
-- Purpose: Add CBSA tracking for Value Codes 61/G8
ALTER TABLE "claim_service_lines"
  ADD COLUMN IF NOT EXISTS "cbsa_code" varchar(5),
  ADD COLUMN IF NOT EXISTS "service_location_zip" varchar(10),
  ADD COLUMN IF NOT EXISTS "service_location_city" varchar(100),
  ADD COLUMN IF NOT EXISTS "service_location_state" varchar(2),
  ADD COLUMN IF NOT EXISTS "facility_cbsa_code" varchar(5),
  ADD COLUMN IF NOT EXISTS "facility_npi" varchar(10),
  ADD COLUMN IF NOT EXISTS "facility_name" varchar(255);

-- ============================================
-- ENHANCEMENT 2: CLAIMS - ADD SCRUBBING STATUS & EDI CONTROL NUMBERS
-- ============================================
-- Purpose: Track scrubbing status and EDI control numbers for submission
ALTER TABLE "claims"
  ADD COLUMN IF NOT EXISTS "scrubbing_status" varchar(50),
  ADD COLUMN IF NOT EXISTS "last_scrubbed_at" timestamp,
  ADD COLUMN IF NOT EXISTS "scrubbing_passed" boolean,
  ADD COLUMN IF NOT EXISTS "edi_interchange_control_number" varchar(50),
  ADD COLUMN IF NOT EXISTS "edi_transaction_set_control_number" varchar(50),
  ADD COLUMN IF NOT EXISTS "submission_ready" boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS "submission_blocked_reasons" jsonb;

-- ============================================
-- INDEXES FOR CBSA CODES
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_cbsa_codes_zip" ON "cbsa_codes"("zip_code");
CREATE INDEX IF NOT EXISTS "idx_cbsa_codes_cbsa" ON "cbsa_codes"("cbsa_code");
CREATE INDEX IF NOT EXISTS "idx_cbsa_codes_state" ON "cbsa_codes"("state");
CREATE INDEX IF NOT EXISTS "idx_cbsa_codes_effective" ON "cbsa_codes"("effective_date", "expiration_date");

-- ============================================
-- INDEXES FOR CLEARINGHOUSE SUBMISSIONS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_clearinghouse_submissions_claim" ON "clearinghouse_submissions"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_clearinghouse_submissions_batch" ON "clearinghouse_submissions"("submission_batch_id");
CREATE INDEX IF NOT EXISTS "idx_clearinghouse_submissions_status" ON "clearinghouse_submissions"("current_status");
CREATE INDEX IF NOT EXISTS "idx_clearinghouse_submissions_date" ON "clearinghouse_submissions"("submission_date");
CREATE INDEX IF NOT EXISTS "idx_clearinghouse_submissions_ack_status" ON "clearinghouse_submissions"("acknowledgment_status");

-- ============================================
-- INDEXES FOR CLAIM VALIDATION RESULTS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_validation_results_claim" ON "claim_validation_results"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_validation_results_date" ON "claim_validation_results"("validation_date");
CREATE INDEX IF NOT EXISTS "idx_validation_results_passed" ON "claim_validation_results"("passed");
CREATE INDEX IF NOT EXISTS "idx_validation_results_type" ON "claim_validation_results"("validation_type");

-- ============================================
-- INDEXES FOR SERVICE LINE CBSA FIELDS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_service_lines_cbsa" ON "claim_service_lines"("cbsa_code");
CREATE INDEX IF NOT EXISTS "idx_service_lines_facility_cbsa" ON "claim_service_lines"("facility_cbsa_code");

-- ============================================
-- INDEXES FOR CLAIM SCRUBBING STATUS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_claims_scrubbing_status" ON "claims"("scrubbing_status");
CREATE INDEX IF NOT EXISTS "idx_claims_submission_ready" ON "claims"("submission_ready");

-- =============================================================================
-- END OF MIGRATION 0013
-- =============================================================================
