-- =============================================================================
-- PHASE 3 ELIGIBILITY VERIFICATION & ERA PROCESSING
-- Migration: 0014_add_phase3_eligibility_era.sql
-- Created: 2025-12-27
-- Description: Add eligibility verification (270/271) and ERA processing (835)
--              with automated payment posting capabilities
-- Compliance: HIPAA 5010 270/271/835 standards
-- =============================================================================

-- ============================================
-- PHASE 3A: ELIGIBILITY VERIFICATION TABLES
-- ============================================

-- TABLE 1: Eligibility Requests
-- Purpose: Track 270 EDI eligibility inquiry requests
CREATE TABLE IF NOT EXISTS "eligibility_requests" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Request identification
  "request_id" varchar(50) UNIQUE NOT NULL,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "payer_id" bigint REFERENCES "payers"("id"),

  -- Request details
  "request_type" varchar(50) DEFAULT 'REAL_TIME' NOT NULL,
  "service_type" varchar(50) DEFAULT 'HOSPICE' NOT NULL,
  "request_date" timestamp DEFAULT now() NOT NULL,

  -- 270 transaction data
  "edi_270_content" text,
  "control_number" varchar(50),

  -- Subscriber information
  "subscriber_id" varchar(50),
  "subscriber_first_name" varchar(100),
  "subscriber_last_name" varchar(100),
  "subscriber_dob" date,

  -- Provider information
  "provider_npi" varchar(10),
  "provider_tax_id" varchar(20),
  "provider_name" varchar(255),

  -- Request status
  "status" varchar(50) DEFAULT 'PENDING' NOT NULL,
  "sent_at" timestamp,

  -- Submission details
  "submission_method" varchar(50),
  "clearinghouse_name" varchar(100),
  "clearinghouse_trace_id" varchar(100),

  -- Error tracking
  "error_message" text,
  "retry_count" bigint DEFAULT 0,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_eligibility_requests_patient" ON "eligibility_requests"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_eligibility_requests_status" ON "eligibility_requests"("status");
CREATE INDEX IF NOT EXISTS "idx_eligibility_requests_request_date" ON "eligibility_requests"("request_date");

-- TABLE 2: Eligibility Responses
-- Purpose: Store 271 EDI eligibility response data
CREATE TABLE IF NOT EXISTS "eligibility_responses" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Response identification
  "request_id" bigint NOT NULL REFERENCES "eligibility_requests"("id"),
  "response_id" varchar(50) UNIQUE NOT NULL,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "payer_id" bigint REFERENCES "payers"("id"),

  -- Response details
  "response_date" timestamp DEFAULT now() NOT NULL,
  "received_at" timestamp DEFAULT now() NOT NULL,

  -- 271 transaction data
  "edi_271_content" text,
  "control_number" varchar(50),

  -- Eligibility status
  "eligibility_status" varchar(50),
  "is_eligible" boolean,

  -- Coverage period
  "coverage_effective_date" date,
  "coverage_termination_date" date,

  -- Plan information
  "plan_name" varchar(255),
  "plan_number" varchar(100),
  "group_number" varchar(100),

  -- Subscriber information
  "subscriber_id" varchar(50),
  "subscriber_name" varchar(255),
  "relationship_to_subscriber" varchar(50),

  -- Coverage details
  "service_type_code" varchar(10),
  "coverage_level" varchar(50),

  -- Financial information (in cents)
  "copay_amount" bigint,
  "deductible_amount" bigint,
  "deductible_met" bigint,
  "out_of_pocket_max" bigint,
  "out_of_pocket_met" bigint,
  "coinsurance_percentage" bigint,

  -- Benefit limitations
  "limitations" text,
  "authorization_required" boolean,
  "authorization_number" varchar(100),

  -- Additional coverage info
  "additional_payer_info" jsonb,

  -- Rejection/Error details
  "rejection_reason" text,
  "follow_up_action" text,

  -- Validity tracking
  "valid_until" timestamp,
  "is_current" boolean DEFAULT true,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_eligibility_responses_patient" ON "eligibility_responses"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_eligibility_responses_request" ON "eligibility_responses"("request_id");
CREATE INDEX IF NOT EXISTS "idx_eligibility_responses_current" ON "eligibility_responses"("is_current") WHERE "is_current" = true;

-- TABLE 3: Patient Coverage
-- Purpose: Current active coverage snapshot for quick access
CREATE TABLE IF NOT EXISTS "patient_coverage" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "patient_id" bigint NOT NULL UNIQUE REFERENCES "patients"("id"),
  "payer_id" bigint REFERENCES "payers"("id"),

  -- Coverage status
  "is_active" boolean DEFAULT false NOT NULL,
  "eligibility_verified" boolean DEFAULT false,
  "last_verified_date" timestamp,

  -- Coverage dates
  "effective_date" date,
  "termination_date" date,

  -- Plan details
  "plan_name" varchar(255),
  "plan_number" varchar(100),
  "group_number" varchar(100),
  "member_id" varchar(50),

  -- Financial summary (in cents)
  "copay_amount" bigint,
  "deductible_amount" bigint,
  "deductible_remaining" bigint,
  "out_of_pocket_max" bigint,
  "out_of_pocket_remaining" bigint,

  -- Authorization requirements
  "authorization_required" boolean DEFAULT false,
  "authorization_number" varchar(100),
  "authorization_expiration" date,

  -- Service limitations
  "hospice_covered" boolean DEFAULT true,
  "limitations" text,

  -- Link to source
  "latest_response_id" bigint REFERENCES "eligibility_responses"("id"),

  -- Cache control
  "cache_expires_at" timestamp,

  -- Alerts
  "needs_reverification" boolean DEFAULT false,
  "reverification_reason" text,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_patient_coverage_patient" ON "patient_coverage"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_patient_coverage_active" ON "patient_coverage"("is_active") WHERE "is_active" = true;
CREATE INDEX IF NOT EXISTS "idx_patient_coverage_reverification" ON "patient_coverage"("needs_reverification") WHERE "needs_reverification" = true;

-- TABLE 4: Benefit Details
-- Purpose: Detailed benefit information extracted from 271 responses
CREATE TABLE IF NOT EXISTS "benefit_details" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "response_id" bigint NOT NULL REFERENCES "eligibility_responses"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Benefit identification
  "service_type_code" varchar(10),
  "coverage_level" varchar(50),
  "time_period_qualifier" varchar(10),

  -- Benefit amounts (in cents)
  "monetary_amount" bigint,
  "percentage_amount" bigint,
  "quantity" bigint,

  -- In-network vs out-of-network
  "in_network" boolean,

  -- Benefit description
  "benefit_type" varchar(100),
  "description" text,

  -- Date ranges
  "benefit_begin_date" date,
  "benefit_end_date" date,

  -- Authorization
  "authorization_required" boolean,

  -- Additional info
  "additional_info" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_benefit_details_response" ON "benefit_details"("response_id");
CREATE INDEX IF NOT EXISTS "idx_benefit_details_patient" ON "benefit_details"("patient_id");

-- ============================================
-- PHASE 3B: ERA PROCESSING TABLES
-- ============================================

-- TABLE 5: ERA Files
-- Purpose: Track received 835 EDI files
CREATE TABLE IF NOT EXISTS "era_files" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- File identification
  "file_id" varchar(50) UNIQUE NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "file_size" bigint,

  -- 835 transaction data
  "edi_835_content" text,
  "control_number" varchar(50),

  -- Payer information
  "payer_id" bigint REFERENCES "payers"("id"),
  "payer_name" varchar(255),
  "payer_identifier" varchar(50),

  -- File metadata
  "production_date" date,
  "received_date" timestamp DEFAULT now() NOT NULL,

  -- Processing status
  "status" varchar(50) DEFAULT 'PENDING' NOT NULL,
  "processed_at" timestamp,

  -- File summary
  "total_payments" bigint DEFAULT 0,
  "total_amount" bigint DEFAULT 0,
  "total_claims" bigint DEFAULT 0,

  -- Posting summary
  "auto_posted_count" bigint DEFAULT 0,
  "exception_count" bigint DEFAULT 0,

  -- Source information
  "source" varchar(50),
  "source_path" varchar(500),

  -- Error tracking
  "error_message" text,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "uploaded_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_era_files_status" ON "era_files"("status");
CREATE INDEX IF NOT EXISTS "idx_era_files_received_date" ON "era_files"("received_date");
CREATE INDEX IF NOT EXISTS "idx_era_files_payer" ON "era_files"("payer_id");

-- TABLE 6: ERA Payments
-- Purpose: Payment details extracted from 835 transactions
CREATE TABLE IF NOT EXISTS "era_payments" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- ERA file reference
  "era_file_id" bigint NOT NULL REFERENCES "era_files"("id"),

  -- Payment identification
  "payment_id" varchar(50) UNIQUE NOT NULL,
  "check_number" varchar(50),
  "check_date" date,

  -- Payer information
  "payer_id" bigint REFERENCES "payers"("id"),
  "payer_name" varchar(255),
  "payer_identifier" varchar(50),

  -- Payee (provider) information
  "payee_name" varchar(255),
  "payee_npi" varchar(10),
  "payee_tax_id" varchar(20),

  -- Payment amounts (in cents)
  "total_payment_amount" bigint NOT NULL,
  "total_billed_amount" bigint,
  "total_allowed_amount" bigint,
  "total_adjustment_amount" bigint,

  -- Payment method
  "payment_method" varchar(50),
  "payment_format" varchar(50),

  -- Claim reference
  "claim_id" bigint REFERENCES "claims"("id"),
  "patient_account_number" varchar(50),
  "patient_name" varchar(255),

  -- Claim-level information
  "claim_statement_period_start" date,
  "claim_statement_period_end" date,
  "claim_status" varchar(50),

  -- Service line details
  "service_line_count" bigint,

  -- CARC/RARC codes
  "adjustment_codes" jsonb,
  "remark_codes" jsonb,

  -- Posting status
  "posting_status" varchar(50) DEFAULT 'PENDING' NOT NULL,
  "posted_at" timestamp,
  "posted_by_id" text REFERENCES "users"("id"),

  -- Exception handling
  "is_exception" boolean DEFAULT false,
  "exception_reason" text,
  "exception_resolved_at" timestamp,

  -- Raw segment data
  "claim_payment_info" jsonb,
  "service_payment_info" jsonb,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_era_payments_file" ON "era_payments"("era_file_id");
CREATE INDEX IF NOT EXISTS "idx_era_payments_claim" ON "era_payments"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_era_payments_status" ON "era_payments"("posting_status");
CREATE INDEX IF NOT EXISTS "idx_era_payments_exception" ON "era_payments"("is_exception") WHERE "is_exception" = true;
CREATE INDEX IF NOT EXISTS "idx_era_payments_check_number" ON "era_payments"("check_number");

-- TABLE 7: Payment Postings
-- Purpose: Audit trail of automated and manual payment postings
CREATE TABLE IF NOT EXISTS "payment_postings" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Payment reference
  "era_payment_id" bigint NOT NULL REFERENCES "era_payments"("id"),
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),

  -- Posting identification
  "posting_id" varchar(50) UNIQUE NOT NULL,
  "posting_date" timestamp DEFAULT now() NOT NULL,

  -- Posting type
  "posting_type" varchar(50) NOT NULL,
  "posting_level" varchar(50),

  -- Amounts posted (in cents)
  "payment_amount" bigint NOT NULL,
  "allowed_amount" bigint,
  "billed_amount" bigint,
  "adjustment_amount" bigint,
  "contractual_adjustment" bigint,
  "patient_responsibility" bigint,
  "write_off_amount" bigint,

  -- Adjustment details
  "adjustment_reason_codes" jsonb,
  "adjustment_details" jsonb,

  -- Claim balance updates
  "previous_balance" bigint,
  "new_balance" bigint,

  -- Service line reference
  "service_line_number" bigint,
  "procedure_code" varchar(20),
  "service_date" date,

  -- Posting validation
  "is_validated" boolean DEFAULT true,
  "validation_notes" text,

  -- Reversal tracking
  "is_reversed" boolean DEFAULT false,
  "reversed_at" timestamp,
  "reversed_by_id" text REFERENCES "users"("id"),
  "reversal_reason" text,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "posted_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_payment_postings_era_payment" ON "payment_postings"("era_payment_id");
CREATE INDEX IF NOT EXISTS "idx_payment_postings_claim" ON "payment_postings"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_payment_postings_date" ON "payment_postings"("posting_date");
CREATE INDEX IF NOT EXISTS "idx_payment_postings_reversed" ON "payment_postings"("is_reversed") WHERE "is_reversed" = true;

-- TABLE 8: Posting Exceptions
-- Purpose: Track payments that couldn't be auto-posted
CREATE TABLE IF NOT EXISTS "posting_exceptions" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Payment reference
  "era_payment_id" bigint NOT NULL REFERENCES "era_payments"("id"),
  "era_file_id" bigint NOT NULL REFERENCES "era_files"("id"),

  -- Exception identification
  "exception_id" varchar(50) UNIQUE NOT NULL,
  "exception_type" varchar(50) NOT NULL,

  -- Exception details
  "exception_reason" text NOT NULL,
  "exception_severity" varchar(20) DEFAULT 'MEDIUM',

  -- Payment information
  "check_number" varchar(50),
  "payment_amount" bigint,
  "patient_account_number" varchar(50),

  -- Attempted match information
  "attempted_claim_id" bigint REFERENCES "claims"("id"),
  "match_confidence_score" decimal(5,2),

  -- Resolution status
  "status" varchar(50) DEFAULT 'PENDING' NOT NULL,
  "assigned_to_id" text REFERENCES "users"("id"),
  "assigned_at" timestamp,

  -- Resolution details
  "resolution_type" varchar(50),
  "resolution_notes" text,
  "resolved_at" timestamp,
  "resolved_by_id" text REFERENCES "users"("id"),

  -- Follow-up tracking
  "follow_up_required" boolean DEFAULT false,
  "follow_up_date" date,
  "follow_up_notes" text,

  -- SLA tracking
  "created_at" timestamp DEFAULT now() NOT NULL,
  "sla_deadline" timestamp,
  "is_overdue" boolean DEFAULT false,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_posting_exceptions_era_payment" ON "posting_exceptions"("era_payment_id");
CREATE INDEX IF NOT EXISTS "idx_posting_exceptions_status" ON "posting_exceptions"("status");
CREATE INDEX IF NOT EXISTS "idx_posting_exceptions_severity" ON "posting_exceptions"("exception_severity");
CREATE INDEX IF NOT EXISTS "idx_posting_exceptions_overdue" ON "posting_exceptions"("is_overdue") WHERE "is_overdue" = true;

-- TABLE 9: Reconciliation Batches
-- Purpose: Daily deposit reconciliation tracking
CREATE TABLE IF NOT EXISTS "reconciliation_batches" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Batch identification
  "batch_id" varchar(50) UNIQUE NOT NULL,
  "batch_date" date NOT NULL,

  -- Deposit information
  "deposit_date" date,
  "deposit_amount" bigint,
  "bank_statement_amount" bigint,

  -- ERA totals
  "era_file_count" bigint DEFAULT 0,
  "total_era_payments" bigint DEFAULT 0,
  "total_posted_payments" bigint DEFAULT 0,

  -- Reconciliation results
  "variance_amount" bigint,
  "is_reconciled" boolean DEFAULT false,
  "reconciliation_status" varchar(50) DEFAULT 'PENDING',

  -- Variance breakdown
  "unmatched_deposits" jsonb,
  "unmatched_eras" jsonb,

  -- Bank statement details
  "bank_account_number" varchar(50),
  "bank_routing_number" varchar(20),
  "bank_statement_reference" varchar(100),

  -- Reconciliation notes
  "reconciliation_notes" text,
  "variance_explanation" text,

  -- Approval tracking
  "approved_by_id" text REFERENCES "users"("id"),
  "approved_at" timestamp,

  -- Metadata
  "metadata" jsonb,

  -- Audit fields
  "reconciled_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_reconciliation_batches_date" ON "reconciliation_batches"("batch_date");
CREATE INDEX IF NOT EXISTS "idx_reconciliation_batches_status" ON "reconciliation_batches"("reconciliation_status");

-- ============================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================

COMMENT ON TABLE "eligibility_requests" IS 'Phase 3A: Tracks 270 EDI eligibility inquiry requests';
COMMENT ON TABLE "eligibility_responses" IS 'Phase 3A: Stores 271 EDI eligibility response data';
COMMENT ON TABLE "patient_coverage" IS 'Phase 3A: Current active coverage snapshot with 30-day cache';
COMMENT ON TABLE "benefit_details" IS 'Phase 3A: Detailed benefit information from 271 responses';
COMMENT ON TABLE "era_files" IS 'Phase 3B: Tracks received 835 EDI remittance files';
COMMENT ON TABLE "era_payments" IS 'Phase 3B: Payment details extracted from 835 transactions';
COMMENT ON TABLE "payment_postings" IS 'Phase 3B: Audit trail of payment postings (automated & manual)';
COMMENT ON TABLE "posting_exceptions" IS 'Phase 3B: Tracks payments requiring manual review';
COMMENT ON TABLE "reconciliation_batches" IS 'Phase 3B: Daily deposit reconciliation tracking';
