-- =============================================================================
-- PHASE 3D: REVENUE RECOGNITION & FORECASTING
-- Migration: 0017_add_revenue_recognition_tables.sql
-- Created: 2025-12-27
-- Description: Complete revenue accrual, forecasting, and cash flow projection
--              system for comprehensive financial management
-- Compliance: GAAP revenue recognition, healthcare financial reporting standards
-- =============================================================================

-- ============================================
-- TABLE 1: REVENUE ACCRUALS
-- ============================================
-- Purpose: Track expected revenue as claims progress through lifecycle
CREATE TABLE IF NOT EXISTS "revenue_accruals" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Claim and patient reference
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "payer_id" bigint REFERENCES "payers"("id"),

  -- Accrual identification
  "accrual_id" varchar(50) UNIQUE NOT NULL,
  "accrual_date" date NOT NULL,

  -- Service information
  "service_date_from" date NOT NULL,
  "service_date_to" date NOT NULL,
  "service_month" varchar(7) NOT NULL,

  -- Financial amounts (in cents)
  "billed_amount" bigint NOT NULL,
  "expected_reimbursement" bigint NOT NULL,
  "accrued_amount" bigint NOT NULL,
  "collected_amount" bigint DEFAULT 0,
  "adjusted_amount" bigint DEFAULT 0,
  "written_off_amount" bigint DEFAULT 0,

  -- Recognition method and status
  "recognition_method" varchar(50) NOT NULL,
  "recognition_status" varchar(50) DEFAULT 'ACCRUED' NOT NULL,
  "recognition_date" date,

  -- Contract and reimbursement info
  "contract_rate_type" varchar(50),
  "expected_payment_days" bigint,
  "confidence_level" varchar(20),
  "collection_probability" bigint DEFAULT 10000,

  -- Period assignment
  "revenue_period" varchar(7) NOT NULL,
  "fiscal_year" bigint NOT NULL,
  "fiscal_quarter" bigint NOT NULL,

  -- Reversal tracking
  "is_reversed" boolean DEFAULT false,
  "reversed_date" date,
  "reversal_reason" text,

  -- Metadata
  "calculation_method" text,
  "assumptions" jsonb,
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_revenue_accruals_claim" ON "revenue_accruals"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_revenue_accruals_patient" ON "revenue_accruals"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_revenue_accruals_payer" ON "revenue_accruals"("payer_id");
CREATE INDEX IF NOT EXISTS "idx_revenue_accruals_period" ON "revenue_accruals"("revenue_period");
CREATE INDEX IF NOT EXISTS "idx_revenue_accruals_status" ON "revenue_accruals"("recognition_status");
CREATE INDEX IF NOT EXISTS "idx_revenue_accruals_service_month" ON "revenue_accruals"("service_month");

-- ============================================
-- TABLE 2: REVENUE ADJUSTMENTS
-- ============================================
-- Purpose: Track all adjustments to accrued revenue
CREATE TABLE IF NOT EXISTS "revenue_adjustments" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Accrual reference
  "accrual_id" bigint NOT NULL REFERENCES "revenue_accruals"("id"),
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),

  -- Adjustment details
  "adjustment_date" date NOT NULL,
  "adjustment_type" varchar(50) NOT NULL,
  "adjustment_amount" bigint NOT NULL,

  -- Reason and source
  "reason" text NOT NULL,
  "source_type" varchar(50),
  "source_reference_id" varchar(100),

  -- Related records
  "denial_id" bigint,
  "appeal_id" bigint,
  "era_payment_id" bigint,

  -- Impact
  "impacts_current_period" boolean DEFAULT true,
  "period_impacted" varchar(7),

  -- Approval workflow
  "requires_approval" boolean DEFAULT false,
  "approved" boolean,
  "approved_by_id" text REFERENCES "users"("id"),
  "approved_at" timestamp,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_revenue_adjustments_accrual" ON "revenue_adjustments"("accrual_id");
CREATE INDEX IF NOT EXISTS "idx_revenue_adjustments_claim" ON "revenue_adjustments"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_revenue_adjustments_type" ON "revenue_adjustments"("adjustment_type");
CREATE INDEX IF NOT EXISTS "idx_revenue_adjustments_period" ON "revenue_adjustments"("period_impacted");

-- ============================================
-- TABLE 3: COLLECTION FORECASTS
-- ============================================
-- Purpose: Projected cash collections by period
CREATE TABLE IF NOT EXISTS "collection_forecasts" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Period identification
  "forecast_period" varchar(7) NOT NULL,
  "forecast_created_date" date NOT NULL,
  "forecast_type" varchar(50) NOT NULL,

  -- Dimension
  "payer_id" bigint REFERENCES "payers"("id"),
  "service_type" varchar(50),

  -- Forecasted amounts (in cents)
  "forecasted_collections" bigint NOT NULL,
  "forecasted_writeoffs" bigint,
  "forecasted_denials" bigint,
  "forecasted_appeals_recovery" bigint,

  -- Actual amounts
  "actual_collections" bigint,
  "actual_writeoffs" bigint,
  "variance_amount" bigint,
  "variance_percentage" bigint,

  -- Confidence
  "confidence_level" varchar(20),
  "confidence_percentage" bigint,
  "calculation_method" varchar(100) NOT NULL,

  -- Assumptions
  "assumptions" jsonb,
  "historical_data_range" jsonb,

  -- Status
  "forecast_status" varchar(50) DEFAULT 'DRAFT' NOT NULL,
  "locked" boolean DEFAULT false,
  "locked_at" timestamp,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_collection_forecasts_period" ON "collection_forecasts"("forecast_period");
CREATE INDEX IF NOT EXISTS "idx_collection_forecasts_payer" ON "collection_forecasts"("payer_id");

-- ============================================
-- TABLE 4: PAYER PAYMENT PATTERNS
-- ============================================
-- Purpose: Historical payment behavior analytics by payer
CREATE TABLE IF NOT EXISTS "payer_payment_patterns" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Payer reference
  "payer_id" bigint NOT NULL REFERENCES "payers"("id"),

  -- Analysis period
  "analysis_period_start" date NOT NULL,
  "analysis_period_end" date NOT NULL,
  "last_calculated" timestamp NOT NULL,

  -- Volume metrics
  "total_claims_submitted" bigint DEFAULT 0,
  "total_claims_paid" bigint DEFAULT 0,
  "total_claims_denied" bigint DEFAULT 0,
  "total_claims_pending" bigint DEFAULT 0,

  -- Financial metrics (in cents)
  "total_billed_amount" bigint DEFAULT 0,
  "total_paid_amount" bigint DEFAULT 0,
  "total_denied_amount" bigint DEFAULT 0,
  "total_adjusted_amount" bigint DEFAULT 0,

  -- Timing metrics (days)
  "avg_days_to_payment" decimal(10, 2),
  "median_days_to_payment" bigint,
  "min_days_to_payment" bigint,
  "max_days_to_payment" bigint,
  "std_dev_days" decimal(10, 2),

  -- Rate metrics (basis points)
  "collection_rate" bigint,
  "denial_rate" bigint,
  "clean_claim_rate" bigint,
  "appeal_success_rate" bigint,

  -- Payment behavior
  "payment_reliability_score" bigint,
  "payment_pattern" varchar(50),
  "preferred_payment_day" bigint,

  -- Seasonal patterns
  "seasonal_variance" boolean,
  "peak_payment_months" jsonb,
  "slow_payment_months" jsonb,

  -- Risk assessment
  "risk_level" varchar(20),
  "credit_score" bigint,
  "bad_debt_likelihood" bigint,

  -- Metadata
  "calculation_notes" text,
  "metadata" jsonb,

  -- Audit
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_payer_payment_patterns_payer" ON "payer_payment_patterns"("payer_id");

-- ============================================
-- TABLE 5: REVENUE RECOGNITION PERIODS
-- ============================================
-- Purpose: Monthly/quarterly close tracking
CREATE TABLE IF NOT EXISTS "revenue_recognition_periods" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Period identification
  "period_type" varchar(20) NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "period_label" varchar(50) NOT NULL,
  "fiscal_year" bigint NOT NULL,
  "fiscal_quarter" bigint,

  -- Period status
  "status" varchar(50) DEFAULT 'OPEN' NOT NULL,
  "closed_date" timestamp,
  "locked_date" timestamp,
  "closed_by_id" text REFERENCES "users"("id"),
  "locked_by_id" text REFERENCES "users"("id"),

  -- Revenue metrics (in cents)
  "total_billed" bigint DEFAULT 0,
  "total_accrued" bigint DEFAULT 0,
  "total_collected" bigint DEFAULT 0,
  "total_written_off" bigint DEFAULT 0,
  "total_adjustments" bigint DEFAULT 0,
  "net_revenue" bigint DEFAULT 0,

  -- Volume metrics
  "total_claims" bigint DEFAULT 0,
  "total_patients" bigint DEFAULT 0,
  "total_service_days" bigint DEFAULT 0,

  -- AR metrics (in cents)
  "beginning_ar" bigint,
  "ending_ar" bigint,
  "ar_change" bigint,

  -- DSO metrics
  "days_sales_outstanding" decimal(10, 2),
  "ar_aging_0_30" bigint,
  "ar_aging_31_60" bigint,
  "ar_aging_61_90" bigint,
  "ar_aging_91_120" bigint,
  "ar_aging_over_120" bigint,

  -- Reconciliation
  "reconciliation_complete" boolean DEFAULT false,
  "reconciliation_date" timestamp,
  "reconciliation_notes" text,
  "variances" jsonb,

  -- Metadata
  "summary_report_url" text,
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_revenue_recognition_periods_period" ON "revenue_recognition_periods"("period_label");
CREATE INDEX IF NOT EXISTS "idx_revenue_recognition_periods_status" ON "revenue_recognition_periods"("status");

-- ============================================
-- TABLE 6: CASH FLOW PROJECTIONS
-- ============================================
-- Purpose: Cash flow forecasting and working capital analysis
CREATE TABLE IF NOT EXISTS "cash_flow_projections" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Projection identification
  "projection_date" date NOT NULL,
  "projection_for_period" varchar(7) NOT NULL,
  "projection_type" varchar(50) NOT NULL,

  -- Time horizon
  "weeks_ahead" bigint,
  "months_ahead" bigint,

  -- Projected cash inflows (in cents)
  "projected_collections" bigint NOT NULL,
  "projected_appeal_recoveries" bigint,
  "projected_other_income" bigint,
  "total_projected_inflows" bigint NOT NULL,

  -- Projected cash outflows (in cents)
  "projected_payroll" bigint,
  "projected_vendor_payments" bigint,
  "projected_other_expenses" bigint,
  "total_projected_outflows" bigint,

  -- Net cash flow
  "projected_net_cash_flow" bigint NOT NULL,
  "projected_ending_cash" bigint,

  -- Working capital
  "projected_ar" bigint,
  "projected_ap" bigint,
  "projected_working_capital" bigint,

  -- Actual vs projected
  "actual_collections" bigint,
  "actual_net_cash_flow" bigint,
  "variance_amount" bigint,
  "variance_percentage" bigint,

  -- Confidence
  "confidence_level" varchar(20),
  "confidence_percentage" bigint,
  "methodology" varchar(100),
  "assumptions" jsonb,

  -- Risk factors
  "risk_factors" jsonb,
  "sensitivity_analysis" jsonb,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_cash_flow_projections_period" ON "cash_flow_projections"("projection_for_period");
CREATE INDEX IF NOT EXISTS "idx_cash_flow_projections_date" ON "cash_flow_projections"("projection_date");

-- ============================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================

COMMENT ON TABLE "revenue_accruals" IS 'Phase 3D: Track expected revenue as claims progress through lifecycle with GAAP compliance';
COMMENT ON TABLE "revenue_adjustments" IS 'Phase 3D: Track all adjustments to accrued revenue from denials, appeals, payments';
COMMENT ON TABLE "collection_forecasts" IS 'Phase 3D: Projected cash collections by period with actual vs forecast tracking';
COMMENT ON TABLE "payer_payment_patterns" IS 'Phase 3D: Historical payment behavior analytics for forecasting and risk assessment';
COMMENT ON TABLE "revenue_recognition_periods" IS 'Phase 3D: Monthly/quarterly close tracking with AR aging and DSO metrics';
COMMENT ON TABLE "cash_flow_projections" IS 'Phase 3D: Cash flow forecasting and working capital analysis with sensitivity scenarios';
