-- ============================================================================
-- Migration: 0020_add_electronic_signatures.sql
-- Description: Add 21 CFR Part 11 compliant electronic signatures tables
-- Date: 2025-12-30
-- ============================================================================
-- This migration creates tables to support FDA 21 CFR Part 11 compliance for
-- electronic records and signatures in the Chartwarden EHR system.
--
-- Key compliance features:
-- - Unique user identification and authentication binding (11.100)
-- - Immutable records with database-level protections (11.10)
-- - Cryptographic document hashing for integrity (11.70)
-- - Complete audit trail linkage (11.10(e))
-- - Signature meaning/intent documentation (11.50(a))
-- ============================================================================

-- Create enum types for electronic signatures
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'signature_type') THEN
        CREATE TYPE signature_type AS ENUM (
            'TYPED',
            'DRAWN',
            'BIOMETRIC',
            'PIN',
            'SMART_CARD',
            'DIGITAL_CERT'
        );
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'signature_meaning') THEN
        CREATE TYPE signature_meaning AS ENUM (
            'AUTHOR',
            'REVIEWER',
            'APPROVER',
            'VERIFIER',
            'AUTHENTICATOR',
            'WITNESS',
            'COSIGNER',
            'ORDERING_PROVIDER',
            'CERTIFIER',
            'ATTESTOR',
            'RECIPIENT',
            'AMENDMENT'
        );
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'signature_status') THEN
        CREATE TYPE signature_status AS ENUM (
            'VALID',
            'REVOKED',
            'EXPIRED',
            'SUPERSEDED',
            'PENDING_REVIEW'
        );
    END IF;
END$$;

-- ============================================================================
-- Table: electronic_signatures
-- Main table for 21 CFR Part 11 compliant electronic signatures
-- ============================================================================
CREATE TABLE IF NOT EXISTS electronic_signatures (
    -- Primary key
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Signer identification (21 CFR Part 11.100)
    signer_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    signer_name VARCHAR(255) NOT NULL,
    signer_email VARCHAR(255) NOT NULL,
    signer_credentials VARCHAR(255),
    signer_title VARCHAR(255),
    session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL ON UPDATE CASCADE,

    -- Signature data (21 CFR Part 11.50)
    signature_type signature_type NOT NULL,
    signature_meaning signature_meaning NOT NULL,
    signature_statement TEXT NOT NULL,
    signature_data TEXT NOT NULL,
    signature_image_format VARCHAR(50),

    -- Document binding (21 CFR Part 11.70)
    document_type VARCHAR(100) NOT NULL,
    document_id TEXT NOT NULL,
    document_version VARCHAR(50) NOT NULL DEFAULT '1.0',
    document_hash VARCHAR(64) NOT NULL,
    hash_algorithm VARCHAR(50) NOT NULL DEFAULT 'SHA-256',

    -- Timestamp & non-repudiation (21 CFR Part 11.10(e))
    signed_at TIMESTAMP NOT NULL,
    server_timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    signer_timezone VARCHAR(100),
    tsa_timestamp TIMESTAMP,
    tsa_provider VARCHAR(255),
    tsa_response TEXT,

    -- Authentication verification (21 CFR Part 11.200)
    authentication_method VARCHAR(100) NOT NULL,
    mfa_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_type VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent TEXT,
    device_fingerprint VARCHAR(255),

    -- Signature status & lifecycle
    status signature_status NOT NULL DEFAULT 'VALID',
    superseded_by_id BIGINT,
    revocation_reason TEXT,
    revoked_at TIMESTAMP,
    revoked_by_id TEXT REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,

    -- Cosignature requirements
    requires_cosigner BOOLEAN NOT NULL DEFAULT FALSE,
    required_cosigner_id TEXT REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    required_cosigner_role VARCHAR(100),
    cosigner_signature_id BIGINT,
    cosignature_deadline TIMESTAMP,

    -- Compliance metadata
    audit_log_id BIGINT,
    organization_id VARCHAR(100),
    facility_id VARCHAR(100),
    regulatory_context VARCHAR(100),
    metadata JSONB,

    -- Immutable timestamp (no updated_at per 21 CFR Part 11)
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    -- Unique constraint: prevent duplicate signatures
    CONSTRAINT unique_signature_per_document_version
        UNIQUE (signer_id, document_type, document_id, document_version, signature_meaning)
);

-- Self-referencing foreign key for superseded_by_id
ALTER TABLE electronic_signatures
    ADD CONSTRAINT fk_superseded_by
    FOREIGN KEY (superseded_by_id)
    REFERENCES electronic_signatures(id)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- Self-referencing foreign key for cosigner_signature_id
ALTER TABLE electronic_signatures
    ADD CONSTRAINT fk_cosigner_signature
    FOREIGN KEY (cosigner_signature_id)
    REFERENCES electronic_signatures(id)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- Performance indexes for electronic_signatures
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_signer_id ON electronic_signatures(signer_id);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_session_id ON electronic_signatures(session_id);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_document_type ON electronic_signatures(document_type);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_document_id ON electronic_signatures(document_id);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_status ON electronic_signatures(status);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_signed_at ON electronic_signatures(signed_at);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_meaning ON electronic_signatures(signature_meaning);

-- Composite indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_document_history
    ON electronic_signatures(document_type, document_id, signed_at);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_signer_time
    ON electronic_signatures(signer_id, signed_at);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_pending_cosign
    ON electronic_signatures(requires_cosigner, cosigner_signature_id, cosignature_deadline);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_document_status
    ON electronic_signatures(document_type, document_id, status);

-- ============================================================================
-- Table: signature_audit_events
-- Detailed audit trail for signature-related events (21 CFR Part 11.10(e))
-- ============================================================================
CREATE TABLE IF NOT EXISTS signature_audit_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Reference to signature
    signature_id BIGINT NOT NULL REFERENCES electronic_signatures(id) ON DELETE RESTRICT ON UPDATE CASCADE,

    -- Event details
    event_type VARCHAR(100) NOT NULL,
    event_description TEXT,

    -- Actor information
    actor_id TEXT REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    actor_name VARCHAR(255),
    session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL ON UPDATE CASCADE,

    -- Request context
    ip_address VARCHAR(45),
    user_agent TEXT,

    -- Additional data
    event_metadata JSONB,

    -- Immutable timestamp
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for signature_audit_events
CREATE INDEX IF NOT EXISTS idx_signature_audit_events_signature_id ON signature_audit_events(signature_id);
CREATE INDEX IF NOT EXISTS idx_signature_audit_events_actor_id ON signature_audit_events(actor_id);
CREATE INDEX IF NOT EXISTS idx_signature_audit_events_event_type ON signature_audit_events(event_type);
CREATE INDEX IF NOT EXISTS idx_signature_audit_events_created_at ON signature_audit_events(created_at);
CREATE INDEX IF NOT EXISTS idx_signature_audit_events_history ON signature_audit_events(signature_id, created_at);

-- ============================================================================
-- Table: signature_verification_tokens
-- Secure tokens for external signature verification
-- ============================================================================
CREATE TABLE IF NOT EXISTS signature_verification_tokens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Reference to signature
    signature_id BIGINT NOT NULL REFERENCES electronic_signatures(id) ON DELETE CASCADE ON UPDATE CASCADE,

    -- Token data
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP,
    max_uses BIGINT,
    use_count BIGINT NOT NULL DEFAULT 0,

    -- Creator
    created_by_id TEXT REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,

    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    revoked_at TIMESTAMP,

    -- Timestamp
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for signature_verification_tokens
CREATE INDEX IF NOT EXISTS idx_signature_verification_tokens_token ON signature_verification_tokens(token);
CREATE INDEX IF NOT EXISTS idx_signature_verification_tokens_signature_id ON signature_verification_tokens(signature_id);
CREATE INDEX IF NOT EXISTS idx_signature_verification_tokens_active ON signature_verification_tokens(is_active, expires_at);

-- ============================================================================
-- IMMUTABILITY ENFORCEMENT (21 CFR Part 11 Compliance)
-- Prevent UPDATE and DELETE on electronic_signatures to ensure non-repudiation
-- ============================================================================

-- Function to prevent updates on electronic_signatures
CREATE OR REPLACE FUNCTION prevent_electronic_signature_update()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION '21 CFR Part 11 Compliance: Electronic signatures are immutable and cannot be modified. Create a new signature with status SUPERSEDED instead.'
        USING ERRCODE = 'restrict_violation';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Function to prevent deletes on electronic_signatures
CREATE OR REPLACE FUNCTION prevent_electronic_signature_delete()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION '21 CFR Part 11 Compliance: Electronic signatures are immutable and cannot be deleted. Use revocation instead.'
        USING ERRCODE = 'restrict_violation';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers to enforce immutability
DROP TRIGGER IF EXISTS prevent_electronic_signature_update_trigger ON electronic_signatures;
CREATE TRIGGER prevent_electronic_signature_update_trigger
    BEFORE UPDATE ON electronic_signatures
    FOR EACH ROW
    EXECUTE FUNCTION prevent_electronic_signature_update();

DROP TRIGGER IF EXISTS prevent_electronic_signature_delete_trigger ON electronic_signatures;
CREATE TRIGGER prevent_electronic_signature_delete_trigger
    BEFORE DELETE ON electronic_signatures
    FOR EACH ROW
    EXECUTE FUNCTION prevent_electronic_signature_delete();

-- Similar immutability for signature_audit_events
DROP TRIGGER IF EXISTS prevent_signature_audit_update_trigger ON signature_audit_events;
CREATE TRIGGER prevent_signature_audit_update_trigger
    BEFORE UPDATE ON signature_audit_events
    FOR EACH ROW
    EXECUTE FUNCTION prevent_electronic_signature_update();

DROP TRIGGER IF EXISTS prevent_signature_audit_delete_trigger ON signature_audit_events;
CREATE TRIGGER prevent_signature_audit_delete_trigger
    BEFORE DELETE ON signature_audit_events
    FOR EACH ROW
    EXECUTE FUNCTION prevent_electronic_signature_delete();

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================
COMMENT ON TABLE electronic_signatures IS '21 CFR Part 11 compliant electronic signatures for EHR documents. Records are immutable.';
COMMENT ON TABLE signature_audit_events IS 'Audit trail for electronic signature events per 21 CFR Part 11.10(e). Records are immutable.';
COMMENT ON TABLE signature_verification_tokens IS 'Secure tokens for external verification of electronic signatures.';

COMMENT ON COLUMN electronic_signatures.document_hash IS 'SHA-256 hash of document content at time of signing for integrity verification';
COMMENT ON COLUMN electronic_signatures.signature_meaning IS 'Legal significance of signature per 21 CFR Part 11.50(a)';
COMMENT ON COLUMN electronic_signatures.authentication_method IS 'How user authenticated before signing per 21 CFR Part 11.200';
