-- ============================================================================
-- ENCOUNTERS TABLES MIGRATION
-- ============================================================================
-- Patient encounters schema for clinical encounter documentation
-- Supports admission, visit, discharge, SOAP notes, and e-signatures
-- Required for billing and regulatory compliance (21 CFR Part 11)
-- ============================================================================

-- Main encounters table
CREATE TABLE IF NOT EXISTS "encounters" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "encounters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Encounter metadata
  "encounter_type" varchar(50) NOT NULL, -- ADMISSION_VISIT, ROUTINE_VISIT, PRN_VISIT, DISCHARGE_VISIT, etc.
  "encounter_status" varchar(50) NOT NULL DEFAULT 'SCHEDULED', -- SCHEDULED, IN_PROGRESS, COMPLETED, UNSIGNED, SIGNED, COSIGNED, AMENDED, CANCELLED
  "encounter_date" timestamp NOT NULL,
  "encounter_duration_minutes" integer,

  -- Visit information
  "visit_location" varchar(100), -- PATIENT_HOME, ASSISTED_LIVING_FACILITY, NURSING_HOME, etc.
  "visit_address" text,
  "discipline" varchar(50) NOT NULL, -- REGISTERED_NURSE, SOCIAL_WORKER, CHAPLAIN, etc.

  -- Staff information
  "staff_id" text REFERENCES "users"("id"),
  "staff_name" varchar(255),
  "staff_credentials" varchar(100),
  "cosigner_id" text REFERENCES "users"("id"),
  "cosigner_name" varchar(255),

  -- GPS check-in/out (for visit verification)
  "gps_check_in" jsonb,
  "gps_check_out" jsonb,

  -- SOAP Documentation
  "subjective" text, -- Patient's report, symptoms, complaints
  "objective" text, -- Clinical findings, observations
  "assessment" text, -- Clinical assessment, diagnoses
  "plan" text, -- Treatment plan, interventions

  -- Vital signs (embedded for convenience)
  "vital_signs" jsonb,

  -- Pain assessment
  "pain_assessment" jsonb,

  -- Symptom assessment
  "symptoms" jsonb,

  -- Interventions performed
  "interventions" text,
  "medications_administered" jsonb,

  -- Patient education
  "patient_education" text,
  "education_topics" jsonb,
  "patient_understanding" varchar(50), -- GOOD, FAIR, POOR

  -- Caregiver assessment
  "caregiver_present" boolean,
  "caregiver_name" varchar(255),
  "caregiver_assessment" text,
  "caregiver_education" text,
  "caregiver_coping" varchar(50), -- COPING_WELL, STRUGGLING, etc.

  -- Psychosocial/spiritual assessment
  "emotional_status" text,
  "spiritual_concerns" text,
  "social_concerns" text,

  -- Safety assessment
  "safety_concerns" text,
  "fall_risk" varchar(50), -- LOW, MODERATE, HIGH
  "skin_integrity" text,

  -- Environment assessment
  "environment_assessment" text,
  "home_safety_issues" text,

  -- Communication
  "communication_with_physician" text,
  "communication_with_team" text,
  "orders_received" text,

  -- Clinical notes
  "clinical_notes" text,
  "follow_up_needed" text,
  "recommendations" text,

  -- Attachments
  "attachments" jsonb,

  -- Signature (21 CFR Part 11 compliance)
  "signature" jsonb,

  -- Cosignature (for students, new staff, etc.)
  "cosignature" jsonb,

  -- Amendment tracking
  "amended" boolean DEFAULT false,
  "amendment_count" integer DEFAULT 0,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp, -- Soft delete
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- Encounter Addendums table
CREATE TABLE IF NOT EXISTS "encounter_addendums" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "encounter_addendums_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "encounter_id" bigint NOT NULL REFERENCES "encounters"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Addendum details
  "addendum_date" timestamp NOT NULL,
  "addendum_reason" varchar(255),
  "addendum_content" text NOT NULL,

  -- Added by
  "added_by_id" text REFERENCES "users"("id"),
  "added_by_name" varchar(255),

  -- Signature
  "signature" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- Encounter Amendments table
CREATE TABLE IF NOT EXISTS "encounter_amendments" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "encounter_amendments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "encounter_id" bigint NOT NULL REFERENCES "encounters"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Amendment details
  "amendment_date" timestamp NOT NULL,
  "amendment_reason" varchar(255) NOT NULL,
  "field_amended" varchar(100) NOT NULL, -- Which field was changed
  "original_value" text, -- Original content
  "amended_value" text, -- New content
  "amendment_notes" text,

  -- Amended by
  "amended_by_id" text REFERENCES "users"("id"),
  "amended_by_name" varchar(255),

  -- Signature
  "signature" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- Encounter Templates table
CREATE TABLE IF NOT EXISTS "encounter_templates" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "encounter_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),

  -- Template metadata
  "template_name" varchar(255) NOT NULL,
  "template_description" text,
  "encounter_type" varchar(50), -- ROUTINE_VISIT, ADMISSION_VISIT, etc.
  "discipline" varchar(50), -- REGISTERED_NURSE, SOCIAL_WORKER, etc.

  -- Template content
  "template_content" jsonb,

  -- Template settings
  "is_active" boolean DEFAULT true,
  "is_default" boolean DEFAULT false,
  "use_count" integer DEFAULT 0,

  -- Sharing settings
  "is_public" boolean DEFAULT false, -- Available to all staff
  "created_by_id" text REFERENCES "users"("id"),
  "shared_with_disciplines" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- ============================================================================
-- PERFORMANCE INDEXES
-- ============================================================================

-- Single column indexes for foreign keys and frequently queried columns
CREATE INDEX IF NOT EXISTS "idx_encounters_patient_id" ON "encounters"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_encounters_encounter_date" ON "encounters"("encounter_date");
CREATE INDEX IF NOT EXISTS "idx_encounters_staff_id" ON "encounters"("staff_id");
CREATE INDEX IF NOT EXISTS "idx_encounters_status" ON "encounters"("encounter_status");
CREATE INDEX IF NOT EXISTS "idx_encounters_discipline" ON "encounters"("discipline");

-- Composite indexes for common query patterns
-- Most queries filter by patient_id + encounter_date (e.g., "show encounters for patient in date range")
CREATE INDEX IF NOT EXISTS "idx_encounters_patient_date" ON "encounters"("patient_id", "encounter_date");

-- Queries often filter by patient + status
CREATE INDEX IF NOT EXISTS "idx_encounters_patient_status" ON "encounters"("patient_id", "encounter_status");

-- Billing queries filter by staff + date
CREATE INDEX IF NOT EXISTS "idx_encounters_staff_date" ON "encounters"("staff_id", "encounter_date");

-- Addendums index
CREATE INDEX IF NOT EXISTS "idx_encounter_addendums_encounter_id" ON "encounter_addendums"("encounter_id");

-- Amendments index
CREATE INDEX IF NOT EXISTS "idx_encounter_amendments_encounter_id" ON "encounter_amendments"("encounter_id");

-- Templates index
CREATE INDEX IF NOT EXISTS "idx_encounter_templates_type" ON "encounter_templates"("encounter_type");
CREATE INDEX IF NOT EXISTS "idx_encounter_templates_discipline" ON "encounter_templates"("discipline");

--> statement-breakpoint

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================
COMMENT ON TABLE "encounters" IS 'Clinical encounter documentation - Critical for billing and regulatory compliance';
COMMENT ON TABLE "encounter_addendums" IS 'Additional information added after signing an encounter';
COMMENT ON TABLE "encounter_amendments" IS 'Corrections to original encounter content with audit trail';
COMMENT ON TABLE "encounter_templates" IS 'Reusable templates for common encounter types';

COMMENT ON COLUMN "encounters"."encounter_type" IS 'Type of encounter: ADMISSION_VISIT, ROUTINE_VISIT, PRN_VISIT, DISCHARGE_VISIT, RECERTIFICATION_VISIT, DEATH_VISIT, CONTINUOUS_CARE';
COMMENT ON COLUMN "encounters"."encounter_status" IS 'Status: SCHEDULED, IN_PROGRESS, COMPLETED, UNSIGNED, SIGNED, COSIGNED, AMENDED, CANCELLED';
COMMENT ON COLUMN "encounters"."discipline" IS 'Clinical discipline: REGISTERED_NURSE, LICENSED_PRACTICAL_NURSE, CERTIFIED_NURSING_ASSISTANT, SOCIAL_WORKER, CHAPLAIN, AIDE, PHYSICIAN, NURSE_PRACTITIONER';
COMMENT ON COLUMN "encounters"."signature" IS 'Electronic signature per 21 CFR Part 11 compliance';
