-- Migration: 0024_medications_schema.sql
-- Date: 2025-12-31
-- Description: Create medications schema with NDC codes, dosage, route, frequency, and status tracking
--
-- Medication status types:
-- - ACTIVE: Currently active medication
-- - DISCONTINUED: Permanently stopped medication
-- - PAUSED: Temporarily paused medication (can be resumed)
-- - HELD: Medication temporarily on hold (clinical reason)
-- - COMPLETED: Medication course completed
--
-- Compliance: HIPAA requirements for medication tracking, controlled substance logging

-- =====================================================
-- STEP 1: Create medications table
-- =====================================================

CREATE TABLE IF NOT EXISTS "medications" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Medication identification
  "medication_name" varchar(255) NOT NULL,
  "generic_name" varchar(255),
  "ndc_code" varchar(20), -- National Drug Code (NDC) - FDA standard identifier (format: 5-4-2 or 4-4-2)

  -- Status and route
  "medication_status" varchar(50) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, DISCONTINUED, PAUSED, HELD, COMPLETED
  "medication_route" varchar(50), -- ORAL, IV, IM, SQ, RECTAL, TOPICAL, SUBLINGUAL, TRANSDERMAL, INHALATION, etc.

  -- Dosing information
  "dosage" varchar(100),
  "frequency" varchar(100), -- BID, TID, QID, PRN, Q4H, Q6H, Q8H, Q12H, DAILY, etc.
  "instructions" text,

  -- Timing
  "start_date" date NOT NULL,
  "end_date" date,
  "discontinued_date" date,
  "discontinuation_reason" text,

  -- Controlled substance tracking
  "controlled_schedule" varchar(50), -- SCHEDULE_II, SCHEDULE_III, SCHEDULE_IV, SCHEDULE_V
  "is_hospice_related" boolean DEFAULT true,

  -- Ordering information
  "prescriber_id" text REFERENCES "users"("id"),
  "order_id" bigint,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp, -- Soft delete
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for medications
CREATE INDEX IF NOT EXISTS "idx_medications_patient_id" ON "medications"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_medications_status" ON "medications"("medication_status");
CREATE INDEX IF NOT EXISTS "idx_medications_start_date" ON "medications"("start_date");
CREATE INDEX IF NOT EXISTS "idx_medications_prescriber_id" ON "medications"("prescriber_id");
CREATE INDEX IF NOT EXISTS "idx_medications_ndc_code" ON "medications"("ndc_code");
CREATE INDEX IF NOT EXISTS "idx_medications_patient_status" ON "medications"("patient_id", "medication_status");
CREATE INDEX IF NOT EXISTS "idx_medications_patient_date" ON "medications"("patient_id", "start_date");

-- Add comments for documentation
COMMENT ON TABLE "medications" IS 'Patient medications with NDC codes, dosage, route, frequency, and status tracking';
COMMENT ON COLUMN "medications"."ndc_code" IS 'National Drug Code - FDA identifier in 5-4-2 or 4-4-2 format (e.g., 12345-6789-01)';
COMMENT ON COLUMN "medications"."medication_status" IS 'ACTIVE, DISCONTINUED, PAUSED, HELD, COMPLETED';
COMMENT ON COLUMN "medications"."medication_route" IS 'Administration route: ORAL, IV, IM, SQ, RECTAL, TOPICAL, etc.';
COMMENT ON COLUMN "medications"."frequency" IS 'Dosing frequency: BID, TID, QID, PRN, Q4H, DAILY, etc.';
COMMENT ON COLUMN "medications"."controlled_schedule" IS 'DEA schedule: SCHEDULE_II, SCHEDULE_III, SCHEDULE_IV, SCHEDULE_V';

-- =====================================================
-- STEP 2: Create MAR entries table (Medication Administration Record)
-- =====================================================

CREATE TABLE IF NOT EXISTS "mar_entries" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "medication_id" bigint NOT NULL REFERENCES "medications"("id"),

  -- Timing
  "scheduled_time" timestamp NOT NULL,
  "actual_time" timestamp,

  -- Administration details
  "mar_status" varchar(50) NOT NULL, -- GIVEN, NOT_GIVEN, REFUSED, HELD, LATE, MISSED
  "dosage_given" varchar(100),
  "route_used" varchar(50),

  -- Person who administered
  "administered_by_id" text REFERENCES "users"("id"),
  "administered_by_name" varchar(255),

  -- Additional documentation
  "reason_not_given" text, -- Required if NOT_GIVEN, REFUSED, or HELD
  "patient_response" text, -- Patient's response to medication

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for MAR entries
CREATE INDEX IF NOT EXISTS "idx_mar_entries_patient_id" ON "mar_entries"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_mar_entries_medication_id" ON "mar_entries"("medication_id");
CREATE INDEX IF NOT EXISTS "idx_mar_entries_scheduled_time" ON "mar_entries"("scheduled_time");
CREATE INDEX IF NOT EXISTS "idx_mar_entries_status" ON "mar_entries"("mar_status");
CREATE INDEX IF NOT EXISTS "idx_mar_entries_patient_time" ON "mar_entries"("patient_id", "scheduled_time");
CREATE INDEX IF NOT EXISTS "idx_mar_entries_medication_time" ON "mar_entries"("medication_id", "scheduled_time");

-- Add comments for documentation
COMMENT ON TABLE "mar_entries" IS 'Medication Administration Record - documents each medication administration';
COMMENT ON COLUMN "mar_entries"."mar_status" IS 'GIVEN, NOT_GIVEN, REFUSED, HELD, LATE, MISSED';
COMMENT ON COLUMN "mar_entries"."reason_not_given" IS 'Required when status is NOT_GIVEN, REFUSED, or HELD';

-- =====================================================
-- STEP 3: Create comfort kits table
-- =====================================================

CREATE TABLE IF NOT EXISTS "comfort_kits" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Kit identification
  "kit_number" varchar(50),
  "issue_date" date NOT NULL,
  "expiration_date" date,

  -- Status
  "status" varchar(50) DEFAULT 'ACTIVE', -- ACTIVE, EXPIRED, DESTROYED, RETURNED

  -- Kit contents (array of medications)
  "medications" jsonb,

  -- Location tracking
  "location" varchar(255), -- Where kit is stored (patient home, facility, etc.)

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for comfort kits
CREATE INDEX IF NOT EXISTS "idx_comfort_kits_patient_id" ON "comfort_kits"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_comfort_kits_status" ON "comfort_kits"("status");

-- Add comments for documentation
COMMENT ON TABLE "comfort_kits" IS 'Emergency medication kits for hospice symptom management';
COMMENT ON COLUMN "comfort_kits"."status" IS 'ACTIVE, EXPIRED, DESTROYED, RETURNED';
COMMENT ON COLUMN "comfort_kits"."medications" IS 'JSON array of medications in the kit';

-- =====================================================
-- STEP 4: Create comfort kit usage log table
-- =====================================================

CREATE TABLE IF NOT EXISTS "comfort_kit_usage_log" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "comfort_kit_id" bigint NOT NULL REFERENCES "comfort_kits"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Usage details
  "medication_used" varchar(255),
  "quantity_used" varchar(100),

  "usage_date" timestamp NOT NULL,
  "usage_reason" text, -- Symptom being treated

  -- Who administered
  "administered_by_id" text REFERENCES "users"("id"),
  "administered_by_name" varchar(255),

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for comfort kit usage log
CREATE INDEX IF NOT EXISTS "idx_comfort_kit_usage_log_kit_id" ON "comfort_kit_usage_log"("comfort_kit_id");
CREATE INDEX IF NOT EXISTS "idx_comfort_kit_usage_log_patient_id" ON "comfort_kit_usage_log"("patient_id");

-- Add comments for documentation
COMMENT ON TABLE "comfort_kit_usage_log" IS 'Tracks medication usage from comfort kits for inventory and clinical documentation';

-- =====================================================
-- STEP 5: Create controlled substance log table
-- =====================================================

CREATE TABLE IF NOT EXISTS "controlled_substance_log" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "medication_id" bigint REFERENCES "medications"("id"),

  -- Log entry details
  "log_date" timestamp NOT NULL,
  "action" varchar(50) NOT NULL, -- DISPENSED, DESTROYED, RETURNED, WASTED

  -- Medication details
  "medication_name" varchar(255),
  "quantity" varchar(100),
  "lot_number" varchar(100),

  -- Witness requirement (2-person verification for DEA compliance)
  "witness_id" text REFERENCES "users"("id"),
  "witness_name" varchar(255),

  -- Additional documentation
  "notes" text,

  -- Audit fields
  "logged_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for controlled substance log
CREATE INDEX IF NOT EXISTS "idx_controlled_substance_log_patient_id" ON "controlled_substance_log"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_controlled_substance_log_medication_id" ON "controlled_substance_log"("medication_id");
CREATE INDEX IF NOT EXISTS "idx_controlled_substance_log_action" ON "controlled_substance_log"("action");
CREATE INDEX IF NOT EXISTS "idx_controlled_substance_log_date" ON "controlled_substance_log"("log_date");

-- Add comments for documentation
COMMENT ON TABLE "controlled_substance_log" IS 'DEA-required tracking for Schedule II-V medications';
COMMENT ON COLUMN "controlled_substance_log"."action" IS 'DISPENSED, DESTROYED, RETURNED, WASTED';
COMMENT ON COLUMN "controlled_substance_log"."witness_id" IS '2-person verification required by DEA for controlled substance handling';

-- =====================================================
-- STEP 6: Create medication reconciliation table
-- =====================================================

CREATE TABLE IF NOT EXISTS "medication_reconciliation" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Reconciliation details
  "reconciliation_date" date NOT NULL,
  "reconciliation_type" varchar(50), -- ADMISSION, TRANSFER, DISCHARGE, ROUTINE

  -- Reconciliation findings
  "medications_reviewed" jsonb,

  "discrepancies_found" text,
  "actions_taken" text,

  -- Who performed reconciliation
  "performed_by_id" text REFERENCES "users"("id"),
  "performed_by_name" varchar(255),

  -- Signature
  "signature" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for medication reconciliation
CREATE INDEX IF NOT EXISTS "idx_medication_reconciliation_patient_id" ON "medication_reconciliation"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_medication_reconciliation_date" ON "medication_reconciliation"("reconciliation_date");
CREATE INDEX IF NOT EXISTS "idx_medication_reconciliation_type" ON "medication_reconciliation"("reconciliation_type");

-- Add comments for documentation
COMMENT ON TABLE "medication_reconciliation" IS 'CMS-required medication reconciliation at admission, transfer, and discharge';
COMMENT ON COLUMN "medication_reconciliation"."reconciliation_type" IS 'ADMISSION, TRANSFER, DISCHARGE, ROUTINE';
COMMENT ON COLUMN "medication_reconciliation"."medications_reviewed" IS 'JSON array of medications reviewed during reconciliation';
