-- Migration: Add Physician Certifications Schema
-- Created: 2025-12-31
-- Purpose: Create tables for Medicare certifications, Face-to-Face encounters, orders, and recertification tracking
-- Compliance: CMS Medicare hospice requirements, 21 CFR Part 11 for electronic signatures

-- ============================================
-- CERTIFICATIONS TABLE
-- ============================================
-- Medicare certification periods (required for reimbursement)
-- Types: INITIAL_90 (first 90 days), SUBSEQUENT_90, SUBSEQUENT_60
CREATE TABLE IF NOT EXISTS "certifications" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Certification period details
  "certification_period" varchar(50) NOT NULL, -- INITIAL_90, SUBSEQUENT_90, SUBSEQUENT_60
  "certification_status" varchar(50) DEFAULT 'PENDING' NOT NULL, -- PENDING, ACTIVE, COMPLETED, EXPIRED, REVOKED

  "start_date" date NOT NULL,
  "end_date" date NOT NULL,

  -- Clinical documentation (required for Medicare)
  "terminal_illness_narrative" text NOT NULL,
  "clinical_progression" text,
  "decline_indicators" text,

  -- Physician signature (21 CFR Part 11 compliance)
  "physician_signature" jsonb,

  -- Compliance tracking (CMS 2-day certification requirement)
  "certification_due_date" date, -- Start date + 2 days
  "certification_completed_date" date,
  "certification_timeliness" varchar(50), -- TIMELY, LATE
  "days_late" integer,

  -- Link to Notice of Election
  "noe_id" bigint REFERENCES "notice_of_election"("id"),

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp, -- Soft delete
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- FACE-TO-FACE ENCOUNTERS TABLE
-- ============================================
-- Required within 30 days prior to recertification for Medicare
-- Must be performed by physician, NP, or PA
CREATE TABLE IF NOT EXISTS "face_to_face_encounters" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "certification_id" bigint REFERENCES "certifications"("id"),

  -- Encounter details
  "encounter_date" date NOT NULL,
  "performed_by_id" text REFERENCES "user"("id"),
  "performed_by_name" varchar(255),
  "performed_by_type" varchar(50), -- PHYSICIAN, NP, PA

  -- Visit information
  "visit_type" varchar(50), -- IN_PERSON, TELEHEALTH
  "findings" text NOT NULL,
  "terminal_prognosis_confirmed" boolean DEFAULT true,

  -- Attestation (can be signed by hospice physician if not performed by attending)
  "attestation" jsonb,
  "attestation_date" date,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- ORDERS TABLE
-- ============================================
-- Physician orders for medications, treatments, DME, etc.
-- Required for all patient care interventions
CREATE TABLE IF NOT EXISTS "orders" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Order details
  "order_type" varchar(50) NOT NULL, -- MEDICATION, TREATMENT, DME, LABORATORY, IMAGING, CONSULTATION, etc.
  "order_status" varchar(50) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE, COMPLETED, DISCONTINUED, EXPIRED, PENDING
  "order_priority" varchar(50), -- ROUTINE, URGENT, STAT

  "order_description" text NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date,

  -- Ordering provider
  "ordered_by_id" text REFERENCES "user"("id"),
  "physician_signature" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- VERBAL ORDERS TRACKING TABLE
-- ============================================
-- CMS requires verbal orders to be signed within 48 hours
-- Tracks read-back verification and signature collection
CREATE TABLE IF NOT EXISTS "verbal_orders_tracking" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "order_id" bigint NOT NULL REFERENCES "orders"("id"),

  -- Order reception details
  "received_by_id" text REFERENCES "user"("id"),
  "received_date" timestamp NOT NULL,
  "physician_name" varchar(255),

  -- Read-back verification (safety requirement)
  "read_back_verified" boolean DEFAULT false,

  -- Signature tracking (48-hour requirement)
  "written_signature_obtained" boolean DEFAULT false,
  "signature_obtained_date" date,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- RECERTIFICATION SCHEDULE TABLE
-- ============================================
-- Tracks upcoming recertification due dates and Face-to-Face requirements
-- Used for alerts and compliance tracking
CREATE TABLE IF NOT EXISTS "recertification_schedule" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Recertification timing
  "next_recertification_date" date NOT NULL,
  "certification_period_type" varchar(50), -- INITIAL_90, SUBSEQUENT_90, SUBSEQUENT_60

  -- Face-to-Face tracking
  "f2f_required" boolean DEFAULT false,
  "f2f_due_date" date, -- 30 days before recertification
  "f2f_completed" boolean DEFAULT false,

  -- Alert tracking
  "alert_sent" boolean DEFAULT false,

  -- Audit fields
  "created_by_id" text REFERENCES "user"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- INDEXES FOR CERTIFICATIONS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_certifications_patient_id" ON "certifications"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_certifications_period" ON "certifications"("certification_period");
CREATE INDEX IF NOT EXISTS "idx_certifications_status" ON "certifications"("certification_status");
CREATE INDEX IF NOT EXISTS "idx_certifications_start_date" ON "certifications"("start_date");
CREATE INDEX IF NOT EXISTS "idx_certifications_end_date" ON "certifications"("end_date");
CREATE INDEX IF NOT EXISTS "idx_certifications_due_date" ON "certifications"("certification_due_date");

-- Composite indexes for common query patterns
CREATE INDEX IF NOT EXISTS "idx_certifications_patient_status" ON "certifications"("patient_id", "certification_status");
CREATE INDEX IF NOT EXISTS "idx_certifications_patient_period" ON "certifications"("patient_id", "certification_period");
CREATE INDEX IF NOT EXISTS "idx_certifications_status_due_date" ON "certifications"("certification_status", "certification_due_date");

-- ============================================
-- INDEXES FOR FACE-TO-FACE ENCOUNTERS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_f2f_encounters_patient_id" ON "face_to_face_encounters"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_f2f_encounters_certification_id" ON "face_to_face_encounters"("certification_id");
CREATE INDEX IF NOT EXISTS "idx_f2f_encounters_date" ON "face_to_face_encounters"("encounter_date");
CREATE INDEX IF NOT EXISTS "idx_f2f_encounters_performed_by" ON "face_to_face_encounters"("performed_by_id");

-- ============================================
-- INDEXES FOR ORDERS
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_orders_patient_id" ON "orders"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_orders_type" ON "orders"("order_type");
CREATE INDEX IF NOT EXISTS "idx_orders_status" ON "orders"("order_status");
CREATE INDEX IF NOT EXISTS "idx_orders_start_date" ON "orders"("start_date");
CREATE INDEX IF NOT EXISTS "idx_orders_ordered_by" ON "orders"("ordered_by_id");

-- Composite indexes
CREATE INDEX IF NOT EXISTS "idx_orders_patient_status" ON "orders"("patient_id", "order_status");
CREATE INDEX IF NOT EXISTS "idx_orders_patient_type" ON "orders"("patient_id", "order_type");

-- ============================================
-- INDEXES FOR VERBAL ORDERS TRACKING
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_verbal_orders_order_id" ON "verbal_orders_tracking"("order_id");
CREATE INDEX IF NOT EXISTS "idx_verbal_orders_received_by" ON "verbal_orders_tracking"("received_by_id");
CREATE INDEX IF NOT EXISTS "idx_verbal_orders_signature_pending" ON "verbal_orders_tracking"("written_signature_obtained") WHERE "written_signature_obtained" = false;

-- ============================================
-- INDEXES FOR RECERTIFICATION SCHEDULE
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_recert_schedule_patient_id" ON "recertification_schedule"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_recert_schedule_next_date" ON "recertification_schedule"("next_recertification_date");
CREATE INDEX IF NOT EXISTS "idx_recert_schedule_f2f_required" ON "recertification_schedule"("f2f_required");
CREATE INDEX IF NOT EXISTS "idx_recert_schedule_f2f_due" ON "recertification_schedule"("f2f_due_date") WHERE "f2f_required" = true;
