-- Migration: 0026_patient_addresses_schema.sql
-- Date: 2025-12-31
-- Description: Create patient_addresses table with address types (PRIMARY, BILLING, MAILING)
--
-- Address types:
-- - PRIMARY: Patient's primary residence (used for CBSA determination)
-- - BILLING: Address for billing/invoices (may be family member)
-- - MAILING: Address for correspondence (may differ from primary)
-- - FACILITY: Care facility address (nursing home, ALF, etc.)
-- - TEMPORARY: Temporary address (respite, vacation, etc.)
--
-- Compliance: Medicare billing requires accurate address for CBSA determination

-- =====================================================
-- STEP 1: Create patient_addresses table
-- =====================================================

CREATE TABLE IF NOT EXISTS "patient_addresses" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Address type
  "address_type" varchar(50) DEFAULT 'PRIMARY' NOT NULL, -- PRIMARY, BILLING, MAILING, FACILITY, TEMPORARY

  -- Address components
  "address_line_1" varchar(255) NOT NULL,
  "address_line_2" varchar(255),
  "city" varchar(100) NOT NULL,
  "state" varchar(2) NOT NULL, -- Two-letter state code (e.g., CA, TX, NY)
  "zip_code" varchar(10) NOT NULL, -- Format: 12345 or 12345-6789
  "county" varchar(100), -- County name for CBSA lookup

  -- Geographic data for CBSA determination
  "cbsa_code" varchar(10), -- Core Based Statistical Area code
  "latitude" varchar(20),
  "longitude" varchar(20),

  -- Contact information at this address
  "phone_number" varchar(20), -- Format: (XXX) XXX-XXXX or +1XXXXXXXXXX
  "alternate_phone" varchar(20),

  -- Status flags
  "is_primary" boolean DEFAULT false, -- True if this is the primary address for its type
  "is_verified" boolean DEFAULT false, -- Address has been verified (USPS, etc.)
  "is_active" boolean DEFAULT true, -- Address is currently active

  -- Effective dates (for tracking address history)
  "effective_from" timestamp,
  "effective_to" timestamp,

  -- Notes
  "notes" varchar(500),

  -- Audit fields
  "deleted_at" timestamp, -- Soft delete
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- =====================================================
-- STEP 2: Create indexes for patient_addresses
-- =====================================================

CREATE INDEX IF NOT EXISTS "idx_patient_addresses_patient_id" ON "patient_addresses"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_patient_addresses_type" ON "patient_addresses"("address_type");
CREATE INDEX IF NOT EXISTS "idx_patient_addresses_zip_code" ON "patient_addresses"("zip_code");
CREATE INDEX IF NOT EXISTS "idx_patient_addresses_state" ON "patient_addresses"("state");
CREATE INDEX IF NOT EXISTS "idx_patient_addresses_cbsa_code" ON "patient_addresses"("cbsa_code");
CREATE INDEX IF NOT EXISTS "idx_patient_addresses_patient_type" ON "patient_addresses"("patient_id", "address_type");
CREATE INDEX IF NOT EXISTS "idx_patient_addresses_patient_active" ON "patient_addresses"("patient_id", "is_active");

-- =====================================================
-- STEP 3: Add comments for documentation
-- =====================================================

COMMENT ON TABLE "patient_addresses" IS 'Patient addresses with multiple types (primary, billing, mailing) for Medicare billing compliance';
COMMENT ON COLUMN "patient_addresses"."address_type" IS 'Type of address: PRIMARY, BILLING, MAILING, FACILITY, TEMPORARY';
COMMENT ON COLUMN "patient_addresses"."state" IS 'Two-letter US state code (e.g., CA, TX, NY)';
COMMENT ON COLUMN "patient_addresses"."zip_code" IS 'US ZIP code in format 12345 or 12345-6789';
COMMENT ON COLUMN "patient_addresses"."county" IS 'County name for CBSA lookup and Medicare reimbursement';
COMMENT ON COLUMN "patient_addresses"."cbsa_code" IS 'Core Based Statistical Area code - affects Medicare hospice reimbursement rates';
COMMENT ON COLUMN "patient_addresses"."is_primary" IS 'True if this is the primary address for the patient (one per type)';
COMMENT ON COLUMN "patient_addresses"."is_verified" IS 'Address has been verified via USPS or other verification service';

-- =====================================================
-- STEP 4: Migrate data from old address table (if exists)
-- =====================================================

-- Check if old address table exists and migrate data
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'address') THEN
    INSERT INTO "patient_addresses" (
      patient_id,
      address_type,
      address_line_1,
      address_line_2,
      city,
      state,
      zip_code,
      phone_number,
      alternate_phone,
      is_primary,
      is_active,
      created_at,
      updated_at
    )
    SELECT
      patient_id,
      'PRIMARY' as address_type,
      COALESCE(address_line_1, 'Unknown') as address_line_1,
      address_line_2,
      COALESCE(city, 'Unknown') as city,
      COALESCE(SUBSTRING(state, 1, 2), 'XX') as state,
      COALESCE(SUBSTRING(zip_code, 1, 10), '00000') as zip_code,
      CASE
        WHEN phone_number IS NOT NULL THEN CAST(phone_number AS varchar(20))
        ELSE NULL
      END as phone_number,
      CASE
        WHEN alternate_phone IS NOT NULL THEN CAST(alternate_phone AS varchar(20))
        ELSE NULL
      END as alternate_phone,
      true as is_primary,
      true as is_active,
      created_at,
      updated_at
    FROM "address"
    WHERE patient_id IS NOT NULL
    ON CONFLICT DO NOTHING;

    RAISE NOTICE 'Migrated data from old address table to patient_addresses';
  END IF;
END $$;
