-- Migration: Enhanced Billing Claims Schema
-- Module G - HIGH Priority Enhancement
-- Created: 2024-12-31
-- Purpose: Add billing codes reference, claim submission history, status tracking,
--          diagnosis codes, and procedure codes for comprehensive claims management

-- ============================================
-- BILLING CODES REFERENCE TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "billing_codes" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "code" varchar(20) NOT NULL,
  "code_type" varchar(30) NOT NULL,
  "short_description" varchar(255) NOT NULL,
  "long_description" text,
  "category" varchar(100),
  "subcategory" varchar(100),
  "effective_date" date,
  "termination_date" date,
  "default_rate" integer,
  "rate_type" varchar(20),
  "hospice_applicable" boolean DEFAULT false,
  "level_of_care" varchar(50),
  "usage_count" integer DEFAULT 0,
  "last_used_at" timestamp,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- CLAIM SUBMISSION HISTORY TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "claim_submission_history" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "submission_number" integer NOT NULL,
  "submission_type" varchar(30) NOT NULL,
  "submission_date" timestamp NOT NULL,
  "submission_method" varchar(30) NOT NULL,
  "clearinghouse_id" varchar(50),
  "edi_interchange_control_number" varchar(50),
  "edi_group_control_number" varchar(50),
  "edi_transaction_control_number" varchar(50),
  "clearinghouse_trace_number" varchar(100),
  "clearinghouse_response_date" timestamp,
  "clearinghouse_status" varchar(50),
  "payer_claim_number" varchar(100),
  "payer_response_date" timestamp,
  "payer_status" varchar(50),
  "response_code" varchar(20),
  "response_message" text,
  "rejection_reasons" jsonb,
  "submitted_charges" integer,
  "outbound_file_reference" varchar(255),
  "inbound_file_reference" varchar(255),
  "submitted_by_id" text REFERENCES "user"("id"),
  "notes" text,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- CLAIM STATUS HISTORY TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "claim_status_history" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "previous_status" varchar(50),
  "new_status" varchar(50) NOT NULL,
  "status_date" timestamp NOT NULL,
  "change_reason" varchar(100),
  "change_source" varchar(50),
  "submission_history_id" bigint REFERENCES "claim_submission_history"("id"),
  "charges_at_change" integer,
  "paid_at_change" integer,
  "balance_at_change" integer,
  "notes" text,
  "metadata" jsonb,
  "changed_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- CLAIM DIAGNOSIS CODES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "claim_diagnosis_codes" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "diagnosis_code" varchar(10) NOT NULL,
  "diagnosis_code_qualifier" varchar(2) DEFAULT '0',
  "sequence_number" integer NOT NULL,
  "diagnosis_type" varchar(30) NOT NULL,
  "poa_indicator" varchar(1),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- CLAIM PROCEDURE CODES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "claim_procedure_codes" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "claim_id" bigint NOT NULL REFERENCES "claims"("id"),
  "service_line_id" bigint REFERENCES "claim_service_lines"("id"),
  "procedure_code" varchar(10) NOT NULL,
  "procedure_code_type" varchar(10) NOT NULL,
  "modifier_1" varchar(2),
  "modifier_2" varchar(2),
  "modifier_3" varchar(2),
  "modifier_4" varchar(2),
  "procedure_date" date,
  "units" integer DEFAULT 1,
  "charges" integer,
  "sequence_number" integer NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

-- Billing codes indexes
CREATE INDEX IF NOT EXISTS "idx_billing_codes_code" ON "billing_codes"("code");
CREATE INDEX IF NOT EXISTS "idx_billing_codes_type" ON "billing_codes"("code_type");
CREATE INDEX IF NOT EXISTS "idx_billing_codes_active" ON "billing_codes"("is_active");
CREATE INDEX IF NOT EXISTS "idx_billing_codes_hospice" ON "billing_codes"("hospice_applicable") WHERE "hospice_applicable" = true;
CREATE UNIQUE INDEX IF NOT EXISTS "idx_billing_codes_unique" ON "billing_codes"("code", "code_type");

-- Claim submission history indexes
CREATE INDEX IF NOT EXISTS "idx_claim_submission_claim" ON "claim_submission_history"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_claim_submission_date" ON "claim_submission_history"("submission_date");
CREATE INDEX IF NOT EXISTS "idx_claim_submission_status" ON "claim_submission_history"("clearinghouse_status", "payer_status");
CREATE INDEX IF NOT EXISTS "idx_claim_submission_payer_claim" ON "claim_submission_history"("payer_claim_number");

-- Claim status history indexes
CREATE INDEX IF NOT EXISTS "idx_claim_status_claim" ON "claim_status_history"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_claim_status_date" ON "claim_status_history"("status_date");
CREATE INDEX IF NOT EXISTS "idx_claim_status_new" ON "claim_status_history"("new_status");

-- Claim diagnosis codes indexes
CREATE INDEX IF NOT EXISTS "idx_claim_dx_claim" ON "claim_diagnosis_codes"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_claim_dx_code" ON "claim_diagnosis_codes"("diagnosis_code");
CREATE INDEX IF NOT EXISTS "idx_claim_dx_sequence" ON "claim_diagnosis_codes"("claim_id", "sequence_number");

-- Claim procedure codes indexes
CREATE INDEX IF NOT EXISTS "idx_claim_px_claim" ON "claim_procedure_codes"("claim_id");
CREATE INDEX IF NOT EXISTS "idx_claim_px_code" ON "claim_procedure_codes"("procedure_code");
CREATE INDEX IF NOT EXISTS "idx_claim_px_service_line" ON "claim_procedure_codes"("service_line_id");

-- ============================================
-- SEED DATA: Common Hospice Revenue Codes
-- ============================================
INSERT INTO "billing_codes" ("code", "code_type", "short_description", "long_description", "hospice_applicable", "level_of_care", "is_active")
VALUES
  ('0651', 'REVENUE', 'Routine Home Care', 'Hospice Routine Home Care - Revenue Code for per diem billing', true, 'ROUTINE_HOME_CARE', true),
  ('0652', 'REVENUE', 'Continuous Home Care', 'Hospice Continuous Home Care - Revenue Code for hourly billing (minimum 8 hours)', true, 'CONTINUOUS_HOME_CARE', true),
  ('0655', 'REVENUE', 'Inpatient Respite Care', 'Hospice Inpatient Respite Care - Revenue Code for facility-based respite', true, 'INPATIENT_RESPITE', true),
  ('0656', 'REVENUE', 'General Inpatient Care', 'Hospice General Inpatient Care - Revenue Code for acute symptom management', true, 'GENERAL_INPATIENT', true),
  ('0657', 'REVENUE', 'Physician Services', 'Hospice Physician Services - Revenue Code for attending physician services', true, NULL, true),
  ('0658', 'REVENUE', 'Physician Assistant Services', 'Hospice Nurse Practitioner/Physician Assistant Services', true, NULL, true),
  ('0659', 'REVENUE', 'Other Hospice', 'Other Hospice Services - General hospice revenue code', true, NULL, true)
ON CONFLICT DO NOTHING;

-- ============================================
-- SEED DATA: Common Hospice HCPCS Codes
-- ============================================
INSERT INTO "billing_codes" ("code", "code_type", "short_description", "long_description", "hospice_applicable", "level_of_care", "is_active")
VALUES
  ('Q5001', 'HCPCS', 'Hospice RHC', 'Hospice or Home Health Care Provided in Patient Home/Residence - RHC', true, 'ROUTINE_HOME_CARE', true),
  ('Q5002', 'HCPCS', 'Hospice RHC ALF', 'Hospice or Home Health Care in Assisted Living Facility - RHC', true, 'ROUTINE_HOME_CARE', true),
  ('Q5003', 'HCPCS', 'Hospice CHC', 'Hospice Care Provided in Nursing Long Term Care Facility - CHC', true, 'CONTINUOUS_HOME_CARE', true),
  ('Q5004', 'HCPCS', 'Hospice IRC', 'Hospice Care in Skilled Nursing Facility - Inpatient Respite', true, 'INPATIENT_RESPITE', true),
  ('Q5005', 'HCPCS', 'Hospice GIP', 'Hospice Care in Inpatient Hospital - General Inpatient', true, 'GENERAL_INPATIENT', true),
  ('Q5006', 'HCPCS', 'Hospice GIP Hospice Facility', 'Hospice Care in Hospice Facility - General Inpatient', true, 'GENERAL_INPATIENT', true),
  ('Q5007', 'HCPCS', 'Hospice IRC Hospice Facility', 'Hospice Care in Hospice Facility - Inpatient Respite', true, 'INPATIENT_RESPITE', true),
  ('Q5008', 'HCPCS', 'Hospice RHC SNF', 'Hospice Care in Skilled Nursing Facility - RHC', true, 'ROUTINE_HOME_CARE', true),
  ('Q5009', 'HCPCS', 'Hospice RHC Hospice Facility', 'Hospice Care in Hospice Facility - RHC', true, 'ROUTINE_HOME_CARE', true),
  ('Q5010', 'HCPCS', 'Hospice Home CHC', 'Hospice Home Care Provided in Patient Home - CHC', true, 'CONTINUOUS_HOME_CARE', true),
  ('G0155', 'HCPCS', 'Clinical SW Services', 'Services of clinical social worker in home health or hospice settings', true, NULL, true),
  ('G0154', 'HCPCS', 'PT Services', 'Direct skilled nursing services of a licensed nurse (LPN or RN)', true, NULL, true)
ON CONFLICT DO NOTHING;

-- ============================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================
COMMENT ON TABLE "billing_codes" IS 'Reference table for billing codes (ICD-10, CPT, HCPCS, revenue codes) used in claims';
COMMENT ON TABLE "claim_submission_history" IS 'Tracks all submission attempts for claims with EDI details and payer responses';
COMMENT ON TABLE "claim_status_history" IS 'Audit trail of all status changes for claims throughout their lifecycle';
COMMENT ON TABLE "claim_diagnosis_codes" IS 'Links ICD-10 diagnosis codes to claims with proper sequencing';
COMMENT ON TABLE "claim_procedure_codes" IS 'Links CPT/HCPCS procedure codes to claims with modifiers';
