-- ============================================================================
-- IDG (INTERDISCIPLINARY GROUP) MEETINGS TABLES MIGRATION
-- ============================================================================
-- IDG team meetings schema for hospice care coordination
-- Medicare requires all patients to be reviewed by IDG at least every 14 days
-- Supports meeting management, attendee tracking, patient reviews, and compliance
-- ============================================================================

-- Main IDG Meetings table
CREATE TABLE IF NOT EXISTS "idg_meetings" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idg_meetings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),

  -- Meeting metadata
  "meeting_type" varchar(50) NOT NULL, -- INITIAL, ROUTINE, RECERTIFICATION, EMERGENCY, SPECIAL
  "meeting_status" varchar(50) NOT NULL DEFAULT 'SCHEDULED', -- SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED, RESCHEDULED
  "meeting_date" date NOT NULL,
  "meeting_time" time,
  "meeting_duration_minutes" integer,

  -- Meeting location
  "location" varchar(255),
  "virtual_meeting" boolean DEFAULT false,
  "meeting_link" varchar(500),

  -- Meeting facilitator
  "facilitator_id" text REFERENCES "users"("id"),
  "facilitator_name" varchar(255),

  -- Agenda
  "agenda" text,
  "topics" jsonb,

  -- General discussion
  "general_discussion" text,
  "quality_issues" text,
  "operational_issues" text,
  "staff_concerns" text,

  -- Action items
  "action_items" jsonb,

  -- Follow-up from previous meeting
  "follow_up_items" text,

  -- Patient census at time of meeting
  "patient_census" integer,
  "new_admissions_count" integer,
  "discharges_count" integer,
  "deaths_count" integer,

  -- Meeting outcomes
  "meeting_outcomes" text,
  "decisions_made" text,

  -- Next meeting
  "next_meeting_date" date,
  "next_meeting_agenda" text,

  -- Compliance tracking
  "all_patients_reviewed" boolean DEFAULT false,
  "patients_reviewed_count" integer,
  "patients_missed_count" integer,

  -- Documentation
  "meeting_notes" text,
  "minutes_prepared_by_id" text REFERENCES "users"("id"),
  "minutes_approved" boolean DEFAULT false,
  "minutes_approved_by_id" text REFERENCES "users"("id"),
  "minutes_approved_date" date,

  -- Attachments
  "attachments" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- IDG Attendees table - Track who attended each meeting
CREATE TABLE IF NOT EXISTS "idg_attendees" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idg_attendees_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "idg_meeting_id" bigint NOT NULL REFERENCES "idg_meetings"("id"),

  -- Attendee information
  "staff_id" text REFERENCES "users"("id"),
  "staff_name" varchar(255) NOT NULL,
  "discipline" varchar(50) NOT NULL, -- PHYSICIAN, REGISTERED_NURSE, SOCIAL_WORKER, CHAPLAIN, etc.
  "role" varchar(100), -- Medical Director, Team Leader, etc.

  -- Attendance details
  "attended" boolean DEFAULT true,
  "attendance_type" varchar(50), -- IN_PERSON, VIRTUAL, PHONE
  "arrival_time" time,
  "departure_time" time,

  -- Absence tracking
  "absent_reason" varchar(255),
  "proxy_attendee" varchar(255),

  -- Contribution
  "presented_cases" boolean DEFAULT false,
  "case_count" integer,
  "notes" text,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- IDG Patient Reviews table - Individual patient discussions during IDG meetings
-- CRITICAL: All patients must be reviewed at least every 14 days per Medicare rules
CREATE TABLE IF NOT EXISTS "idg_patient_reviews" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idg_patient_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "idg_meeting_id" bigint NOT NULL REFERENCES "idg_meetings"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Review metadata
  "review_status" varchar(50) NOT NULL DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED, SKIPPED, DEFERRED
  "review_date" date NOT NULL,
  "review_order" integer, -- Order in which patients were reviewed
  "review_duration_minutes" integer,

  -- Presented by
  "presented_by_id" text REFERENCES "users"("id"),
  "presented_by_name" varchar(255),
  "presenter_discipline" varchar(50),

  -- Patient status at time of review
  "days_since_admission" integer,
  "days_since_last_visit" integer,
  "days_since_last_review" integer,
  "current_level_of_care" varchar(50),

  -- Clinical update
  "clinical_summary" text,
  "current_condition" text,
  "recent_changes" text,
  "symptoms" text,
  "pain_management" text,

  -- Functional status
  "functional_status" text,
  "adl_status" text,
  "cognitive_status" varchar(50),
  "mobility_status" varchar(50),

  -- Psychosocial/spiritual
  "psychosocial_issues" text,
  "spiritual_issues" text,
  "family_dynamics" text,
  "caregiver_status" text,
  "caregiver_burden" varchar(50),

  -- Care plan review
  "care_plan_reviewed" boolean DEFAULT false,
  "care_plan_changes" text,
  "goals_reviewed" boolean DEFAULT false,
  "goals_updated" text,

  -- Medication review
  "medications_reviewed" boolean DEFAULT false,
  "medication_changes" text,
  "medication_issues" text,

  -- Service coordination
  "current_services" text,
  "service_frequency" text,
  "service_changes_needed" text,
  "dme_needs" text,
  "supply_needs" text,

  -- Disciplines reporting
  "nursing_update" text,
  "social_work_update" text,
  "chaplain_update" text,
  "aide_update" text,
  "therapy_update" text,
  "volunteer_update" text,
  "physician_update" text,

  -- Issues and concerns
  "safety_concerns" text,
  "compliance_issues" text,
  "barriers_to_care" text,
  "family_concerns" text,

  -- Prognosis and planning
  "prognosis_update" text,
  "decline_indicators" text,
  "imminent_death_indicators" text,
  "bereavement_planning" text,
  "discharge_planning" text,

  -- Recertification
  "recertification_due" boolean DEFAULT false,
  "recertification_date" date,
  "recertification_status" varchar(50),
  "f2f_status" varchar(50),

  -- Quality measures
  "hope_assessment_status" varchar(50),
  "hope_assessment_due" boolean DEFAULT false,
  "documentation_issues" text,

  -- Team recommendations
  "team_recommendations" text,
  "action_items" jsonb,

  -- Follow-up needed
  "follow_up_needed" boolean DEFAULT false,
  "follow_up_items" text,
  "next_review_date" date,

  -- IDG decisions
  "level_of_care_change" boolean DEFAULT false,
  "new_level_of_care" varchar(50),
  "continue_care" boolean DEFAULT true,
  "discharge_recommended" boolean DEFAULT false,
  "discharge_reason" varchar(255),

  -- Orders needed
  "physician_orders_needed" boolean DEFAULT false,
  "orders_description" text,
  "orders_obtained" boolean DEFAULT false,

  -- Additional notes
  "additional_notes" text,
  "special_considerations" text,

  -- Completion
  "review_completed" boolean DEFAULT false,
  "completed_date" timestamp,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- IDG Compliance Tracking table - Track 14-day review compliance
-- Medicare requirement: All patients must be reviewed by IDG every 14 days
CREATE TABLE IF NOT EXISTS "idg_compliance_tracking" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idg_compliance_tracking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Current status
  "last_review_date" date,
  "last_review_meeting_id" bigint REFERENCES "idg_meetings"("id"),
  "days_since_last_review" integer,

  -- Next review due
  "next_review_due_date" date,
  "days_until_next_review" integer,

  -- Compliance status
  "is_compliant" boolean DEFAULT true,
  "is_overdue" boolean DEFAULT false,
  "days_overdue" integer,

  -- Alert tracking
  "alert_sent" boolean DEFAULT false,
  "alert_sent_date" date,
  "alert_recipients" jsonb,

  -- Review history count
  "total_reviews" integer DEFAULT 0,
  "missed_reviews" integer DEFAULT 0,
  "compliance_rate" integer, -- Percentage 0-100

  -- Patient status
  "patient_status" varchar(50),
  "admission_date" date,
  "days_in_hospice" integer,

  -- Notes
  "compliance_notes" text,
  "exception_reason" text,

  -- Audit fields
  "last_calculated_date" date,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint

-- ============================================================================
-- PERFORMANCE INDEXES
-- ============================================================================

-- IDG Meetings indexes
CREATE INDEX IF NOT EXISTS "idx_idg_meetings_date" ON "idg_meetings"("meeting_date");
CREATE INDEX IF NOT EXISTS "idx_idg_meetings_status" ON "idg_meetings"("meeting_status");
CREATE INDEX IF NOT EXISTS "idx_idg_meetings_type" ON "idg_meetings"("meeting_type");
CREATE INDEX IF NOT EXISTS "idx_idg_meetings_facilitator" ON "idg_meetings"("facilitator_id");

-- IDG Attendees indexes
CREATE INDEX IF NOT EXISTS "idx_idg_attendees_meeting_id" ON "idg_attendees"("idg_meeting_id");
CREATE INDEX IF NOT EXISTS "idx_idg_attendees_staff_id" ON "idg_attendees"("staff_id");
CREATE INDEX IF NOT EXISTS "idx_idg_attendees_discipline" ON "idg_attendees"("discipline");

-- IDG Patient Reviews indexes
CREATE INDEX IF NOT EXISTS "idx_idg_patient_reviews_meeting_id" ON "idg_patient_reviews"("idg_meeting_id");
CREATE INDEX IF NOT EXISTS "idx_idg_patient_reviews_patient_id" ON "idg_patient_reviews"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_idg_patient_reviews_date" ON "idg_patient_reviews"("review_date");
CREATE INDEX IF NOT EXISTS "idx_idg_patient_reviews_status" ON "idg_patient_reviews"("review_status");
-- Composite index for patient review history queries
CREATE INDEX IF NOT EXISTS "idx_idg_patient_reviews_patient_date" ON "idg_patient_reviews"("patient_id", "review_date");

-- IDG Compliance Tracking indexes
CREATE INDEX IF NOT EXISTS "idx_idg_compliance_patient_id" ON "idg_compliance_tracking"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_idg_compliance_overdue" ON "idg_compliance_tracking"("is_overdue");
CREATE INDEX IF NOT EXISTS "idx_idg_compliance_due_date" ON "idg_compliance_tracking"("next_review_due_date");
-- Composite index for compliance dashboards
CREATE INDEX IF NOT EXISTS "idx_idg_compliance_status" ON "idg_compliance_tracking"("is_compliant", "is_overdue");

--> statement-breakpoint

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================
COMMENT ON TABLE "idg_meetings" IS 'Interdisciplinary Group team meetings - Required for hospice care coordination';
COMMENT ON TABLE "idg_attendees" IS 'Meeting attendee tracking with discipline and attendance type';
COMMENT ON TABLE "idg_patient_reviews" IS 'Individual patient reviews during IDG meetings - 14-day compliance requirement';
COMMENT ON TABLE "idg_compliance_tracking" IS 'Track 14-day IDG review compliance per CMS requirements';

COMMENT ON COLUMN "idg_meetings"."meeting_type" IS 'Meeting type: INITIAL, ROUTINE, RECERTIFICATION, EMERGENCY, SPECIAL';
COMMENT ON COLUMN "idg_meetings"."meeting_status" IS 'Status: SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED, RESCHEDULED';
COMMENT ON COLUMN "idg_attendees"."discipline" IS 'Clinical discipline: PHYSICIAN, REGISTERED_NURSE, SOCIAL_WORKER, CHAPLAIN, AIDE, etc.';
COMMENT ON COLUMN "idg_attendees"."attendance_type" IS 'How attendee participated: IN_PERSON, VIRTUAL, PHONE';
COMMENT ON COLUMN "idg_patient_reviews"."review_status" IS 'Review status: PENDING, IN_PROGRESS, COMPLETED, SKIPPED, DEFERRED';
COMMENT ON COLUMN "idg_patient_reviews"."days_since_last_review" IS 'Days since last IDG review - must be <= 14 for compliance';
COMMENT ON COLUMN "idg_compliance_tracking"."is_overdue" IS 'True if patient has not been reviewed within 14 days';
COMMENT ON COLUMN "idg_compliance_tracking"."compliance_rate" IS 'Percentage of on-time reviews (0-100)';
