-- Migration: 0029_care_planning_schema.sql
-- Date: 2025-12-31
-- Description: Create care planning schema with care plans, problems, goals, interventions, and progress tracking
--
-- Care plan status types:
-- - DRAFT: Care plan is being developed
-- - ACTIVE: Care plan is in effect
-- - REVISED: Care plan has been superseded by a new version
-- - INACTIVE: Care plan is no longer in use
-- - ARCHIVED: Care plan is archived for historical reference
-- - PENDING_SIGNATURE: Care plan awaiting required signatures
-- - SIGNED: Care plan is fully signed and approved
--
-- Compliance: Medicare requirement for all hospice patients, 21 CFR Part 11 electronic signatures

-- =====================================================
-- STEP 1: Create care_plans table
-- =====================================================

CREATE TABLE IF NOT EXISTS "care_plans" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Care plan metadata
  "care_plan_status" varchar(50) DEFAULT 'DRAFT' NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "effective_date" date NOT NULL,
  "review_date" date,
  "next_review_date" date,

  -- Patient/family goals
  "patient_goals" text,
  "family_goals" text,
  "goals_of_care" text,

  -- Hospice philosophy of care
  "philosophy_of_care" text,
  "approach_to_care" text,

  -- IDG team members
  "team_members" jsonb,

  -- Advance directives
  "advance_directives_on_file" boolean,
  "advance_directive_types" jsonb,
  "code_status" varchar(50),
  "dnr_status" varchar(50),

  -- Bereavement plan
  "bereavement_plan" text,
  "bereavement_risk_level" varchar(50),

  -- Volunteer services
  "volunteer_services" text,
  "volunteer_hours_weekly" integer,

  -- Clinical summary
  "clinical_summary" text,
  "prognosis" text,
  "terminal_diagnosis" text,
  "related_diagnoses" jsonb,

  -- Functional status summary
  "functional_status_summary" text,
  "mobility_status" varchar(100),
  "cognitive_status" varchar(100),

  -- Pain and symptom management approach
  "pain_management_approach" text,
  "symptom_management_approach" text,

  -- Psychosocial and spiritual care
  "psychosocial_plan" text,
  "spiritual_plan" text,
  "cultural_considerations" text,

  -- Safety plan
  "safety_plan" text,
  "fall_prevention" text,
  "infection_control" text,

  -- Equipment and supplies
  "dme_plan" text,
  "supplies_needed" text,

  -- Discharge planning
  "discharge_planning" text,
  "discharge_criteria" text,

  -- Overall plan summary
  "plan_summary" text,
  "special_instructions" text,

  -- Signatures (21 CFR Part 11 compliance)
  "physician_signature" jsonb,
  "rn_signature" jsonb,
  "patient_signature" jsonb,

  -- Recertification
  "recertification_date" date,
  "recertified_by_id" text REFERENCES "users"("id"),

  -- Revision tracking
  "previous_version_id" bigint REFERENCES "care_plans"("id"),
  "revision_reason" text,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for care_plans
CREATE INDEX IF NOT EXISTS "idx_care_plans_patient_id" ON "care_plans"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_care_plans_status" ON "care_plans"("care_plan_status");
CREATE INDEX IF NOT EXISTS "idx_care_plans_effective_date" ON "care_plans"("effective_date");
CREATE INDEX IF NOT EXISTS "idx_care_plans_patient_status" ON "care_plans"("patient_id", "care_plan_status");
CREATE INDEX IF NOT EXISTS "idx_care_plans_patient_date" ON "care_plans"("patient_id", "effective_date");

-- Add comments for documentation
COMMENT ON TABLE "care_plans" IS 'Patient care plans - Medicare requirement for all hospice patients';
COMMENT ON COLUMN "care_plans"."care_plan_status" IS 'DRAFT, ACTIVE, REVISED, INACTIVE, ARCHIVED, PENDING_SIGNATURE, SIGNED';
COMMENT ON COLUMN "care_plans"."team_members" IS 'JSON array of IDG team members assigned to patient';
COMMENT ON COLUMN "care_plans"."physician_signature" IS '21 CFR Part 11 compliant electronic signature with hash, timestamp, and credentials';
COMMENT ON COLUMN "care_plans"."rn_signature" IS '21 CFR Part 11 compliant electronic signature with hash, timestamp, and credentials';

-- =====================================================
-- STEP 2: Create problems table
-- =====================================================

CREATE TABLE IF NOT EXISTS "problems" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "care_plan_id" bigint REFERENCES "care_plans"("id"),

  -- Problem details
  "problem_category" varchar(50) NOT NULL,
  "problem_description" text NOT NULL,
  "problem_status" varchar(50) DEFAULT 'ACTIVE' NOT NULL,
  "problem_priority" varchar(50) DEFAULT 'MEDIUM',

  -- Clinical information
  "onset_date" date,
  "identified_date" date NOT NULL,
  "resolved_date" date,
  "etiology" text,
  "signs_symptoms" text,

  -- Related information
  "related_diagnoses" text,
  "contributing_factors" text,

  -- Discipline responsible
  "primary_discipline" varchar(50),
  "identified_by_id" text REFERENCES "users"("id"),

  -- Notes
  "notes" text,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for problems
CREATE INDEX IF NOT EXISTS "idx_problems_patient_id" ON "problems"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_problems_care_plan_id" ON "problems"("care_plan_id");
CREATE INDEX IF NOT EXISTS "idx_problems_status" ON "problems"("problem_status");
CREATE INDEX IF NOT EXISTS "idx_problems_priority" ON "problems"("problem_priority");
CREATE INDEX IF NOT EXISTS "idx_problems_category" ON "problems"("problem_category");
CREATE INDEX IF NOT EXISTS "idx_problems_patient_status" ON "problems"("patient_id", "problem_status");

-- Add comments for documentation
COMMENT ON TABLE "problems" IS 'Patient problems/needs identified during care planning';
COMMENT ON COLUMN "problems"."problem_category" IS 'PHYSICAL, PSYCHOLOGICAL, SOCIAL, SPIRITUAL, ENVIRONMENTAL, CAREGIVER';
COMMENT ON COLUMN "problems"."problem_status" IS 'ACTIVE, RESOLVED, ONGOING, WORSENING, IMPROVING, STABLE';
COMMENT ON COLUMN "problems"."problem_priority" IS 'HIGH, MEDIUM, LOW';

-- =====================================================
-- STEP 3: Create goals table
-- =====================================================

CREATE TABLE IF NOT EXISTS "goals" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "care_plan_id" bigint REFERENCES "care_plans"("id"),
  "problem_id" bigint REFERENCES "problems"("id"),

  -- Goal details
  "goal_description" text NOT NULL,
  "goal_status" varchar(50) DEFAULT 'NOT_STARTED' NOT NULL,
  "progress_level" varchar(50),

  -- Timeframe
  "target_date" date,
  "start_date" date,
  "achieved_date" date,
  "discontinued_date" date,

  -- Measurement
  "measurable_outcome" text,
  "outcome_criteria" text,
  "evaluation_method" text,

  -- Progress notes
  "progress_notes" text,
  "barriers_to_achievement" text,
  "modifications_needed" text,

  -- Responsibility
  "primary_discipline" varchar(50),
  "responsible_staff_id" text REFERENCES "users"("id"),

  -- Patient/family involvement
  "patient_agreement" boolean,
  "family_agreement" boolean,

  -- Revision tracking
  "revised" boolean DEFAULT false,
  "revision_reason" text,
  "previous_version_id" bigint REFERENCES "goals"("id"),

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for goals
CREATE INDEX IF NOT EXISTS "idx_goals_patient_id" ON "goals"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_goals_care_plan_id" ON "goals"("care_plan_id");
CREATE INDEX IF NOT EXISTS "idx_goals_problem_id" ON "goals"("problem_id");
CREATE INDEX IF NOT EXISTS "idx_goals_status" ON "goals"("goal_status");
CREATE INDEX IF NOT EXISTS "idx_goals_progress" ON "goals"("progress_level");
CREATE INDEX IF NOT EXISTS "idx_goals_target_date" ON "goals"("target_date");
CREATE INDEX IF NOT EXISTS "idx_goals_patient_status" ON "goals"("patient_id", "goal_status");

-- Add comments for documentation
COMMENT ON TABLE "goals" IS 'Patient-centered goals linked to care plans and problems';
COMMENT ON COLUMN "goals"."goal_status" IS 'NOT_STARTED, IN_PROGRESS, ACHIEVED, PARTIALLY_ACHIEVED, NOT_ACHIEVED, DISCONTINUED, REVISED';
COMMENT ON COLUMN "goals"."progress_level" IS 'NO_PROGRESS, MINIMAL_PROGRESS, MODERATE_PROGRESS, SIGNIFICANT_PROGRESS, GOAL_ACHIEVED, REGRESSION';
COMMENT ON COLUMN "goals"."measurable_outcome" IS 'Specific, measurable outcome to track goal achievement';

-- =====================================================
-- STEP 4: Create interventions table
-- =====================================================

CREATE TABLE IF NOT EXISTS "interventions" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "care_plan_id" bigint REFERENCES "care_plans"("id"),
  "problem_id" bigint REFERENCES "problems"("id"),
  "goal_id" bigint REFERENCES "goals"("id"),

  -- Intervention details
  "intervention_category" varchar(50) NOT NULL,
  "intervention_description" text NOT NULL,
  "intervention_status" varchar(50) DEFAULT 'PLANNED' NOT NULL,

  -- Frequency and duration
  "frequency" varchar(100),
  "duration" varchar(100),
  "start_date" date,
  "end_date" date,

  -- Discipline and responsibility
  "discipline" varchar(50) NOT NULL,
  "responsible_staff_id" text REFERENCES "users"("id"),
  "requires_order" boolean DEFAULT false,
  "order_obtained" boolean DEFAULT false,

  -- Rationale and expected outcome
  "rationale" text,
  "expected_outcome" text,
  "patient_response" text,

  -- Implementation tracking
  "last_performed_date" date,
  "next_scheduled_date" date,
  "times_performed" integer DEFAULT 0,

  -- Effectiveness evaluation
  "effectiveness_rating" varchar(50),
  "evaluation_notes" text,

  -- Patient education related
  "education_provided" boolean DEFAULT false,
  "education_topics" jsonb,
  "patient_understanding" varchar(50),

  -- Special instructions
  "special_instructions" text,
  "precautions" text,

  -- Discontinuation
  "discontinued_date" date,
  "discontinuation_reason" text,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for interventions
CREATE INDEX IF NOT EXISTS "idx_interventions_patient_id" ON "interventions"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_interventions_care_plan_id" ON "interventions"("care_plan_id");
CREATE INDEX IF NOT EXISTS "idx_interventions_problem_id" ON "interventions"("problem_id");
CREATE INDEX IF NOT EXISTS "idx_interventions_goal_id" ON "interventions"("goal_id");
CREATE INDEX IF NOT EXISTS "idx_interventions_status" ON "interventions"("intervention_status");
CREATE INDEX IF NOT EXISTS "idx_interventions_category" ON "interventions"("intervention_category");
CREATE INDEX IF NOT EXISTS "idx_interventions_discipline" ON "interventions"("discipline");
CREATE INDEX IF NOT EXISTS "idx_interventions_next_scheduled" ON "interventions"("next_scheduled_date");
CREATE INDEX IF NOT EXISTS "idx_interventions_patient_status" ON "interventions"("patient_id", "intervention_status");

-- Add comments for documentation
COMMENT ON TABLE "interventions" IS 'Actions to address patient problems and achieve goals';
COMMENT ON COLUMN "interventions"."intervention_category" IS 'NURSING, PHYSICIAN, SOCIAL_WORK, SPIRITUAL, THERAPY, AIDE, VOLUNTEER, MEDICATION, DME, EDUCATION, COORDINATION';
COMMENT ON COLUMN "interventions"."intervention_status" IS 'PLANNED, IN_PROGRESS, COMPLETED, DISCONTINUED, ON_HOLD';
COMMENT ON COLUMN "interventions"."frequency" IS 'Visit/action frequency: 3x weekly, daily, PRN, weekly, etc.';
COMMENT ON COLUMN "interventions"."duration" IS 'Duration of each intervention: 30 minutes, 1 hour, ongoing, etc.';
COMMENT ON COLUMN "interventions"."effectiveness_rating" IS 'VERY_EFFECTIVE, EFFECTIVE, SOMEWHAT_EFFECTIVE, NOT_EFFECTIVE';
COMMENT ON COLUMN "interventions"."times_performed" IS 'Counter for tracking implementation progress';

-- =====================================================
-- STEP 5: Create care_plan_revisions table
-- =====================================================

CREATE TABLE IF NOT EXISTS "care_plan_revisions" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "care_plan_id" bigint NOT NULL REFERENCES "care_plans"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Revision details
  "revision_date" date NOT NULL,
  "revision_number" integer NOT NULL,
  "revision_type" varchar(50) NOT NULL,
  "revision_reason" text NOT NULL,

  -- What changed
  "changes_summary" text,
  "problems_added" jsonb,
  "problems_resolved" jsonb,
  "goals_added" jsonb,
  "goals_achieved" jsonb,
  "interventions_added" jsonb,
  "interventions_discontinued" jsonb,

  -- Clinical status changes
  "change_in_condition" text,
  "change_in_goals_of_care" text,
  "new_orders" text,

  -- Team input
  "idg_review_date" date,
  "idg_recommendations" text,
  "physician_input" text,
  "patient_family_input" text,

  -- Signatures
  "revised_by_id" text REFERENCES "users"("id"),
  "revised_by_name" varchar(255),
  "signature" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for care_plan_revisions
CREATE INDEX IF NOT EXISTS "idx_care_plan_revisions_care_plan_id" ON "care_plan_revisions"("care_plan_id");
CREATE INDEX IF NOT EXISTS "idx_care_plan_revisions_patient_id" ON "care_plan_revisions"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_care_plan_revisions_date" ON "care_plan_revisions"("revision_date");
CREATE INDEX IF NOT EXISTS "idx_care_plan_revisions_type" ON "care_plan_revisions"("revision_type");

-- Add comments for documentation
COMMENT ON TABLE "care_plan_revisions" IS 'Tracks all changes to care plans for audit and compliance';
COMMENT ON COLUMN "care_plan_revisions"."revision_type" IS 'MAJOR_REVISION, MINOR_REVISION, RECERTIFICATION, SCHEDULED_REVIEW, UNSCHEDULED_REVIEW';
COMMENT ON COLUMN "care_plan_revisions"."idg_review_date" IS 'Date care plan was reviewed by Interdisciplinary Group';

-- =====================================================
-- STEP 6: Create care_plan_templates table
-- =====================================================

CREATE TABLE IF NOT EXISTS "care_plan_templates" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Template metadata
  "template_name" varchar(255) NOT NULL,
  "template_description" text,
  "diagnosis_category" varchar(100),
  "icd10_codes" jsonb,

  -- Template content
  "template_content" jsonb,

  -- Template settings
  "is_active" boolean DEFAULT true,
  "use_count" integer DEFAULT 0,
  "is_public" boolean DEFAULT false,

  -- Sharing
  "created_by_id" text REFERENCES "users"("id"),
  "shared_with_roles" jsonb,

  -- Audit fields
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create indexes for care_plan_templates
CREATE INDEX IF NOT EXISTS "idx_care_plan_templates_name" ON "care_plan_templates"("template_name");
CREATE INDEX IF NOT EXISTS "idx_care_plan_templates_diagnosis" ON "care_plan_templates"("diagnosis_category");
CREATE INDEX IF NOT EXISTS "idx_care_plan_templates_active" ON "care_plan_templates"("is_active");

-- Add comments for documentation
COMMENT ON TABLE "care_plan_templates" IS 'Reusable care plan templates for common diagnoses';
COMMENT ON COLUMN "care_plan_templates"."template_content" IS 'JSON structure containing predefined problems, goals, and interventions';
COMMENT ON COLUMN "care_plan_templates"."use_count" IS 'Number of times this template has been used to create care plans';
