-- ============================================================================
-- HOPE 2.0 (Hospice Outcomes and Patient Evaluation) Assessment Schema
-- ============================================================================
-- CMS HOPE 2.0 compliant assessment schema effective October 1, 2025
-- Replaces HIS (Hospice Item Set) for quality reporting
-- Sections: A (Admin), F (Preferences), I (Diagnoses), J (Health Conditions),
--           M (Skin Conditions), N (Medications), Z (Record Admin)
-- ============================================================================

-- Drop existing tables if they exist (for clean migration)
DROP TABLE IF EXISTS "hope_symptom_tracking" CASCADE;
DROP TABLE IF EXISTS "hope_compliance_metrics" CASCADE;
DROP TABLE IF EXISTS "hope_submissions" CASCADE;
DROP TABLE IF EXISTS "hope_assessments" CASCADE;

--> statement-breakpoint

-- ============================================================================
-- HOPE ASSESSMENTS V2 - Main Assessment Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS "hope_assessments" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Assessment metadata
  "assessment_type" varchar(50) NOT NULL, -- ADMISSION, HUV1, HUV2, DISCHARGE
  "assessment_status" varchar(50) NOT NULL DEFAULT 'NOT_STARTED', -- NOT_STARTED, IN_PROGRESS, COMPLETED, SIGNED, SUBMITTED, ACCEPTED, REJECTED, OVERDUE
  "assessment_date" timestamp NOT NULL,
  "due_date" timestamp,
  "completed_date" timestamp,
  "hospice_stay_id" bigint, -- Links to hospice admission episode

  -- ============================================================================
  -- SECTION A: Administrative Information
  -- ============================================================================
  -- A0050: Type of Record
  "a0050_record_type" varchar(20), -- 1=Add, 2=Modify, 3=Inactivate
  -- A0100: Facility Provider Numbers
  "a0100a_npi" varchar(20), -- National Provider Identifier
  "a0100b_cms_certification_number" varchar(20), -- CCN
  -- A0200: Type of Assessment
  "a0200_assessment_type_code" varchar(20), -- 01=Admission, 02=HUV, 09=Discharge
  -- A0220: Admission Date
  "a0220_admission_date" date,
  -- A0250: Reason for Assessment
  "a0250_assessment_reason" varchar(50), -- 01=Admission, 02=Scheduled, 03=Unscheduled, etc.
  -- A0270: Discharge Date
  "a0270_discharge_date" date,
  -- A0310: HOPE Assessment Reference Date
  "a0310_assessment_reference_date" date NOT NULL,
  -- A0410: Unit of Service
  "a0410_unit_of_service" varchar(20), -- 01=Routine Home Care, 02=Continuous Home Care, etc.
  -- A1005: Ethnicity
  "a1005_ethnicity" varchar(50), -- A=Hispanic, B=Not Hispanic, C=Unknown
  -- A1010: Race
  "a1010_race" jsonb, -- Array of race codes (A-F)
  -- A1110: Language
  "a1110a_primary_language" varchar(100),
  "a1110b_language_need_interpreter" boolean,

  -- ============================================================================
  -- SECTION F: Preferences for Customary Routine and Activities
  -- ============================================================================
  -- F2100: Life Story/Goals
  "f2100_life_story_discussed" boolean,
  "f2100_goals_documented" boolean,
  -- F2200: Hospitalization Preference
  "f2200_hospitalization_preference" varchar(50), -- 0=No preference, 1=Prefer hospital, 2=Prefer home, 9=Unknown
  "f2200_preference_documented" boolean,
  "f2200_preference_date" timestamp,
  -- F2300: Code Status/Advance Directives
  "f2300_code_status" varchar(50), -- DNR, FULL_CODE, LIMITED_CODE, etc.
  "f2300_advance_directive_exists" boolean,
  "f2300_polst_exists" boolean,
  "f2300_healthcare_proxy" boolean,
  -- F3000: Spiritual/Existential Concerns
  "f3000_spiritual_concerns_present" boolean,
  "f3000_spiritual_needs_addressed" boolean,
  "f3000_chaplain_referral" boolean,
  "f3000_spiritual_assessment" text,
  -- F3100: Caregiver Assessment
  "f3100_caregiver_available" boolean,
  "f3100_caregiver_relationship" varchar(100),
  "f3100_caregiver_hours_per_week" integer,
  "f3100_caregiver_support_adequate" boolean,
  "f3100_caregiver_stress_level" varchar(50), -- NONE, MILD, MODERATE, SEVERE
  "f3100_caregiver_training_needed" boolean,
  "f3100_caregiver_assessment_notes" text,

  -- ============================================================================
  -- SECTION I: Active Diagnoses
  -- ============================================================================
  -- I0010: Principal Diagnosis
  "i0010_principal_diagnosis_icd10" varchar(20) NOT NULL,
  "i0010_principal_diagnosis_description" text,
  -- I0020: Other Diagnoses
  "i0020_other_diagnoses" jsonb, -- Array of {icd10, description, is_related}
  -- I0100: Cancer Diagnosis Details
  "i0100_cancer_primary_site" varchar(100),
  "i0100_cancer_stage" varchar(50),
  "i0100_cancer_metastatic" boolean,
  "i0100_cancer_metastatic_sites" jsonb, -- Array of metastatic sites
  -- I0200: Comorbidities
  "i0200_comorbidities" jsonb, -- Array of comorbid conditions
  -- I0300: Prognosis Indicator
  "i0300_prognosis_months" integer, -- Expected prognosis in months

  -- ============================================================================
  -- SECTION J: Health Conditions
  -- ============================================================================
  -- J0100: Pain Assessment (0-10 scale)
  "j0100_pain_presence" varchar(20), -- 0=No, 1=Yes, 9=Unable to respond
  "j0100_pain_frequency" varchar(50), -- 0=No pain, 1=Less than daily, 2=Daily, 3=Constant
  "j0100_pain_severity_current" integer, -- 0-10 scale
  "j0100_pain_severity_worst" integer, -- 0-10 scale
  "j0100_pain_interference" integer, -- 0-10 scale
  "j0100_pain_acceptable_level" integer, -- Patient's acceptable pain level
  -- J0200: Pain Site Information
  "j0200_pain_sites" jsonb, -- Array of {site, type, description}
  -- J0300: Pain Management
  "j0300_pain_med_effectiveness" varchar(50), -- 0=Not effective, 1=Partially, 2=Mostly, 3=Fully
  "j0300_nonpharm_interventions" jsonb, -- Array of non-pharmacological interventions
  -- J0500: Shortness of Breath (Dyspnea)
  "j0500_dyspnea_presence" boolean,
  "j0500_dyspnea_severity" varchar(50), -- NONE, MILD, MODERATE, SEVERE
  "j0500_dyspnea_at_rest" boolean,
  "j0500_dyspnea_with_activity" boolean,
  "j0500_dyspnea_frequency" varchar(50), -- NEVER, RARELY, OCCASIONALLY, FREQUENTLY, CONSTANTLY
  -- J0600: Nausea/Vomiting
  "j0600_nausea_presence" boolean,
  "j0600_nausea_severity" varchar(50), -- NONE, MILD, MODERATE, SEVERE
  "j0600_nausea_frequency" varchar(50),
  "j0600_vomiting_presence" boolean,
  "j0600_vomiting_frequency" varchar(50),
  -- J0700: Constipation
  "j0700_constipation_presence" boolean,
  "j0700_constipation_severity" varchar(50),
  "j0700_bowel_program" boolean,
  "j0700_last_bowel_movement" date,
  -- J0800: Fatigue/Weakness
  "j0800_fatigue_presence" boolean,
  "j0800_fatigue_severity" varchar(50), -- NONE, MILD, MODERATE, SEVERE
  "j0800_fatigue_interference" integer, -- 0-10 scale
  -- J0900: Appetite/Nutrition
  "j0900_appetite_status" varchar(50), -- GOOD, FAIR, POOR, NONE
  "j0900_weight_change" varchar(50), -- STABLE, GAINING, LOSING
  "j0900_oral_intake_status" varchar(50),
  "j0900_nutritional_concerns" text,
  -- J1000: Anxiety/Depression
  "j1000_phq2_little_interest" integer, -- 0-3 scale (PHQ-2 item 1)
  "j1000_phq2_feeling_down" integer, -- 0-3 scale (PHQ-2 item 2)
  "j1000_phq2_total_score" integer, -- 0-6 total
  "j1000_anxiety_presence" boolean,
  "j1000_anxiety_severity" varchar(50),
  -- J1100: Cognitive Status (BIMS)
  "j1100_bims_repetition_score" integer, -- 0-2 (repeat 3 words)
  "j1100_bims_year_score" integer, -- 0-1
  "j1100_bims_month_score" integer, -- 0-1
  "j1100_bims_day_score" integer, -- 0-1
  "j1100_bims_recall_score" integer, -- 0-6 (recall 3 words: 0, 1, or 2 each)
  "j1100_bims_total_score" integer, -- 0-15 total
  "j1100_cognitive_status" varchar(50), -- INTACT, BORDERLINE_INTACT, MODERATELY_IMPAIRED, SEVERELY_IMPAIRED
  -- J1200: Behavioral Symptoms
  "j1200_wandering" boolean,
  "j1200_verbal_behaviors" boolean,
  "j1200_physical_behaviors" boolean,
  "j1200_socially_inappropriate" boolean,
  "j1200_resists_care" boolean,
  -- J1300: Functional Status
  "j1300_adl_bed_mobility" integer, -- 0-4 scale (0=Independent, 4=Total dependence)
  "j1300_adl_transfer" integer,
  "j1300_adl_locomotion" integer,
  "j1300_adl_dressing" integer,
  "j1300_adl_eating" integer,
  "j1300_adl_toileting" integer,
  "j1300_adl_personal_hygiene" integer,
  "j1300_adl_bathing" integer,
  "j1300_fall_risk" boolean,
  "j1300_fall_risk_interventions" jsonb,
  -- J1400: Vital Signs
  "j1400_vital_signs" jsonb, -- {bp_systolic, bp_diastolic, pulse, resp_rate, temp, o2_sat, weight}
  "j1400_oxygen_dependent" boolean,
  "j1400_oxygen_liters" integer,
  "j1400_oxygen_method" varchar(50), -- NASAL_CANNULA, MASK, HIGH_FLOW, etc.

  -- ============================================================================
  -- SECTION M: Skin Conditions (New in HOPE 2.0)
  -- ============================================================================
  -- M0100: Skin Integrity
  "m0100_skin_intact" boolean,
  "m0100_skin_at_risk" boolean,
  "m0100_skin_risk_factors" jsonb, -- Array of risk factors
  -- M0200: Pressure Ulcers/Injuries
  "m0200_pressure_ulcer_present" boolean,
  "m0200_pressure_ulcers" jsonb, -- Array of {stage, location, size, healing_status}
  "m0200_new_pressure_ulcer" boolean,
  "m0200_worsened_pressure_ulcer" boolean,
  -- M0300: Other Wounds
  "m0300_other_wounds_present" boolean,
  "m0300_other_wounds" jsonb, -- Array of {type, location, size, description}
  -- M0400: Skin Treatments
  "m0400_skin_treatments" jsonb, -- Array of treatments and interventions
  "m0400_wound_care_orders" text,
  -- M0500: Braden Scale (Pressure Ulcer Risk)
  "m0500_braden_sensory" integer, -- 1-4
  "m0500_braden_moisture" integer, -- 1-4
  "m0500_braden_activity" integer, -- 1-4
  "m0500_braden_mobility" integer, -- 1-4
  "m0500_braden_nutrition" integer, -- 1-4
  "m0500_braden_friction" integer, -- 1-3
  "m0500_braden_total_score" integer, -- 6-23 (<=12 high risk, 13-14 moderate, 15-18 mild, >18 no risk)

  -- ============================================================================
  -- SECTION N: Medications (Enhanced in HOPE 2.0)
  -- ============================================================================
  -- N0100: High-Risk Drug Classes
  "n0100_opioid_medications" boolean,
  "n0100_antipsychotic_medications" boolean,
  "n0100_anticoagulant_medications" boolean,
  "n0100_insulin_medications" boolean,
  -- N0200: Medication Management
  "n0200_medication_regimen_review" boolean,
  "n0200_medication_reconciliation" boolean,
  "n0200_medication_education" boolean,
  "n0200_polypharmacy" boolean, -- 5+ medications
  "n0200_medication_concerns" text,
  -- N0300: Symptom Control Medications
  "n0300_symptom_medications" jsonb, -- Array of {symptom, medication, effectiveness}
  -- N0400: Medication Route
  "n0400_route_oral" boolean,
  "n0400_route_sublingual" boolean,
  "n0400_route_transdermal" boolean,
  "n0400_route_iv" boolean,
  "n0400_route_subcutaneous" boolean,
  "n0400_route_rectal" boolean,
  "n0400_route_intramuscular" boolean,

  -- ============================================================================
  -- SECTION Z: Record Administration
  -- ============================================================================
  -- Z0100: Assessor Information
  "z0100_assessor_signature_date" date,
  "z0100_assessor_title" varchar(100),
  "z0100_assessor_credentials" varchar(100),
  -- Z0200: Submission Information
  "z0200_submitted_to_iqies" boolean DEFAULT false,
  "z0200_submission_id" varchar(100),
  "z0200_submission_date" timestamp,
  "z0200_submission_status" varchar(50), -- PENDING, SUBMITTED, ACCEPTED, REJECTED
  "z0200_rejection_reason" text,
  -- Z0300: Record Status
  "z0300_record_status" varchar(50) DEFAULT 'ACTIVE', -- ACTIVE, MODIFIED, INACTIVATED
  "z0300_inactivation_reason" text,

  -- ============================================================================
  -- SFV (Symptom Follow-up Visit) Tracking
  -- ============================================================================
  "sfv_triggered" boolean DEFAULT false,
  "sfv_trigger_date" timestamp,
  "sfv_trigger_symptoms" text, -- CSV of symptoms that triggered SFV
  "sfv_due_date" timestamp, -- Within 48 hours of trigger
  "sfv_completed" boolean DEFAULT false,
  "sfv_completed_date" timestamp,

  -- ============================================================================
  -- Comprehensive Assessment Notes
  -- ============================================================================
  "clinical_notes" text,
  "plan_of_care_updates" text,
  "interdisciplinary_notes" text,
  "family_conference_notes" text,

  -- ============================================================================
  -- Electronic Signature (21 CFR Part 11 Compliance)
  -- ============================================================================
  "signature" jsonb, -- {signer_id, signer_name, signed_at, signature_data}
  "cosignature" jsonb, -- For cases requiring co-signature

  -- ============================================================================
  -- Audit Fields
  -- ============================================================================
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT NOW() NOT NULL,
  "updated_at" timestamp DEFAULT NOW() NOT NULL
);

--> statement-breakpoint

-- ============================================================================
-- HOPE SUBMISSIONS - Tracks submissions to CMS iQIES
-- ============================================================================
CREATE TABLE IF NOT EXISTS "hope_submissions" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "hope_assessment_id" bigint NOT NULL REFERENCES "hope_assessments"("id"),
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Submission details
  "submission_date" timestamp NOT NULL,
  "submission_type" varchar(50) NOT NULL, -- INITIAL, CORRECTION, INACTIVATION
  "submission_status" varchar(50) DEFAULT 'PENDING' NOT NULL, -- PENDING, SUBMITTED, ACCEPTED, REJECTED

  -- iQIES tracking (new system replacing QIES for HOPE 2.0)
  "iqies_submission_id" varchar(255),
  "iqies_tracking_number" varchar(255),
  "iqies_response_date" timestamp,
  "iqies_response_code" varchar(50),
  "iqies_response_message" text,

  -- Submission payload
  "submission_payload" jsonb, -- Full HOPE data submitted
  "response_payload" jsonb, -- iQIES response

  -- Error tracking
  "error_code" varchar(50),
  "error_message" text,
  "error_details" jsonb,
  "validation_errors" jsonb, -- Array of validation errors from VUT

  -- Retry tracking
  "retry_count" integer DEFAULT 0,
  "last_retry_date" timestamp,
  "next_retry_date" timestamp,

  -- Audit fields
  "submitted_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT NOW() NOT NULL,
  "updated_at" timestamp DEFAULT NOW() NOT NULL
);

--> statement-breakpoint

-- ============================================================================
-- HOPE COMPLIANCE METRICS - Tracks 90% compliance threshold requirement
-- ============================================================================
CREATE TABLE IF NOT EXISTS "hope_compliance_metrics" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Reporting period
  "reporting_period_start" timestamp NOT NULL,
  "reporting_period_end" timestamp NOT NULL,
  "reporting_year" integer NOT NULL,
  "reporting_quarter" integer, -- 1-4

  -- Assessment type metrics
  "assessment_type" varchar(50) NOT NULL, -- ADMISSION, HUV1, HUV2, DISCHARGE

  -- Compliance calculations
  "total_required" integer NOT NULL,
  "total_completed" integer NOT NULL,
  "total_completed_timely" integer NOT NULL, -- Submitted within 30-day deadline
  "total_overdue" integer NOT NULL,
  "total_missing" integer NOT NULL,

  -- Compliance rates (percentages 0-100)
  "completion_rate" integer,
  "timeliness_rate" integer,
  "compliance_rate" integer, -- Must be >= 90% to avoid penalty

  -- Penalty tracking (4% Medicare payment reduction if non-compliant)
  "meets_threshold" boolean DEFAULT false, -- True if >= 90%
  "penalty_applied" boolean DEFAULT false,
  "penalty_percentage" integer, -- 4% if non-compliant

  -- Status breakdown
  "status_breakdown" jsonb, -- {submitted: n, accepted: n, rejected: n, pending: n}

  -- Notes
  "notes" text,
  "action_plan" text,

  -- Audit fields
  "calculated_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT NOW() NOT NULL,
  "updated_at" timestamp DEFAULT NOW() NOT NULL
);

--> statement-breakpoint

-- ============================================================================
-- HOPE SYMPTOM TRACKING - Tracks symptoms for SFV triggers
-- ============================================================================
CREATE TABLE IF NOT EXISTS "hope_symptom_tracking" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "hope_assessment_id" bigint REFERENCES "hope_assessments"("id"),

  -- Symptom details
  "symptom_code" varchar(50) NOT NULL, -- PAIN, DYSPNEA, NAUSEA, CONSTIPATION, FATIGUE, ANXIETY, etc.
  "symptom_name" varchar(100) NOT NULL,
  "symptom_severity" varchar(50) NOT NULL, -- NONE, MILD, MODERATE, SEVERE, VERY_SEVERE
  "symptom_frequency" varchar(50), -- NEVER, RARELY, OCCASIONALLY, FREQUENTLY, CONSTANTLY
  "symptom_date" timestamp NOT NULL,
  "symptom_score" integer, -- 0-10 scale where applicable

  -- SFV trigger tracking (required within 48hrs for moderate/severe)
  "triggers_sfv" boolean DEFAULT false,
  "sfv_required_by" timestamp,
  "sfv_completed" boolean DEFAULT false,
  "sfv_completed_date" timestamp,
  "sfv_assessment_id" bigint REFERENCES "hope_assessments"("id"),

  -- Intervention tracking
  "intervention_provided" boolean DEFAULT false,
  "intervention_type" varchar(100),
  "intervention_details" text,
  "intervention_effective" boolean,

  -- Resolution tracking
  "resolved" boolean DEFAULT false,
  "resolved_date" timestamp,
  "resolution_notes" text,

  -- Clinical notes
  "assessment_notes" text,

  -- Audit fields
  "reported_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT NOW() NOT NULL,
  "updated_at" timestamp DEFAULT NOW() NOT NULL
);

--> statement-breakpoint

-- ============================================================================
-- HOPE SECTION RESPONSES - Stores structured responses for each section
-- ============================================================================
CREATE TABLE IF NOT EXISTS "hope_section_responses" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "hope_assessment_id" bigint NOT NULL REFERENCES "hope_assessments"("id"),

  -- Section identification
  "section_code" varchar(20) NOT NULL, -- A, F, I, J, M, N, Z
  "section_name" varchar(100) NOT NULL,
  "section_version" varchar(20) DEFAULT '2.0',

  -- Response data
  "items" jsonb NOT NULL, -- Array of {item_code, item_label, response, skip_pattern}

  -- Section status
  "status" varchar(50) DEFAULT 'NOT_STARTED', -- NOT_STARTED, IN_PROGRESS, COMPLETED, VALIDATED
  "completed_date" timestamp,
  "validated" boolean DEFAULT false,
  "validation_errors" jsonb, -- Array of validation errors

  -- Audit fields
  "completed_by_id" text REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT NOW() NOT NULL,
  "updated_at" timestamp DEFAULT NOW() NOT NULL
);

--> statement-breakpoint

-- ============================================================================
-- PERFORMANCE INDEXES
-- ============================================================================

-- hope_assessments indexes
CREATE INDEX IF NOT EXISTS "idx_hope_v2_patient_id" ON "hope_assessments"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_assessment_date" ON "hope_assessments"("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_assessment_type" ON "hope_assessments"("assessment_type");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_status" ON "hope_assessments"("assessment_status");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_due_date" ON "hope_assessments"("due_date");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_reference_date" ON "hope_assessments"("a0310_assessment_reference_date");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_principal_diagnosis" ON "hope_assessments"("i0010_principal_diagnosis_icd10");

-- Composite indexes for common query patterns
CREATE INDEX IF NOT EXISTS "idx_hope_v2_patient_date" ON "hope_assessments"("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_patient_type_status" ON "hope_assessments"("patient_id", "assessment_type", "assessment_status");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_status_due_date" ON "hope_assessments"("assessment_status", "due_date");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_sfv_triggered" ON "hope_assessments"("sfv_triggered", "sfv_trigger_date");
CREATE INDEX IF NOT EXISTS "idx_hope_v2_submission" ON "hope_assessments"("z0200_submitted_to_iqies", "z0200_submission_status");

-- hope_submissions indexes
CREATE INDEX IF NOT EXISTS "idx_hope_submissions_assessment_id" ON "hope_submissions"("hope_assessment_id");
CREATE INDEX IF NOT EXISTS "idx_hope_submissions_patient_id" ON "hope_submissions"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_hope_submissions_status" ON "hope_submissions"("submission_status");
CREATE INDEX IF NOT EXISTS "idx_hope_submissions_date" ON "hope_submissions"("submission_date");

-- hope_compliance_metrics indexes
CREATE INDEX IF NOT EXISTS "idx_hope_compliance_period" ON "hope_compliance_metrics"("reporting_year", "reporting_quarter");
CREATE INDEX IF NOT EXISTS "idx_hope_compliance_type" ON "hope_compliance_metrics"("assessment_type");
CREATE INDEX IF NOT EXISTS "idx_hope_compliance_threshold" ON "hope_compliance_metrics"("meets_threshold");

-- hope_symptom_tracking indexes
CREATE INDEX IF NOT EXISTS "idx_hope_symptom_patient" ON "hope_symptom_tracking"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_hope_symptom_assessment" ON "hope_symptom_tracking"("hope_assessment_id");
CREATE INDEX IF NOT EXISTS "idx_hope_symptom_sfv" ON "hope_symptom_tracking"("triggers_sfv", "sfv_required_by");
CREATE INDEX IF NOT EXISTS "idx_hope_symptom_code" ON "hope_symptom_tracking"("symptom_code");
CREATE INDEX IF NOT EXISTS "idx_hope_symptom_severity" ON "hope_symptom_tracking"("symptom_severity");

-- hope_section_responses indexes
CREATE INDEX IF NOT EXISTS "idx_hope_section_assessment" ON "hope_section_responses"("hope_assessment_id");
CREATE INDEX IF NOT EXISTS "idx_hope_section_code" ON "hope_section_responses"("section_code");
CREATE INDEX IF NOT EXISTS "idx_hope_section_status" ON "hope_section_responses"("status");

--> statement-breakpoint

-- ============================================================================
-- TABLE AND COLUMN COMMENTS
-- ============================================================================

COMMENT ON TABLE "hope_assessments" IS 'HOPE 2.0 (Hospice Outcomes and Patient Evaluation) patient assessments - CMS quality reporting requirement effective October 1, 2025';
COMMENT ON COLUMN "hope_assessments"."assessment_type" IS 'Assessment type: ADMISSION (within 5 days), HUV1 (days 6-15), HUV2 (days 16-30), DISCHARGE';
COMMENT ON COLUMN "hope_assessments"."a0310_assessment_reference_date" IS 'ARD - the reference date for all time-sensitive items in the assessment';
COMMENT ON COLUMN "hope_assessments"."i0010_principal_diagnosis_icd10" IS 'Principal hospice diagnosis ICD-10 code';
COMMENT ON COLUMN "hope_assessments"."j1100_bims_total_score" IS 'Brief Interview for Mental Status total score (0-15): 13-15=Intact, 8-12=Moderately impaired, 0-7=Severely impaired';
COMMENT ON COLUMN "hope_assessments"."m0500_braden_total_score" IS 'Braden Scale total (6-23): <=12=High risk, 13-14=Moderate, 15-18=Mild, >18=No risk';
COMMENT ON COLUMN "hope_assessments"."sfv_triggered" IS 'True if moderate or severe symptoms trigger Symptom Follow-up Visit requirement within 48 hours';

COMMENT ON TABLE "hope_submissions" IS 'Tracks HOPE assessment submissions to CMS iQIES system (replaces QIES for HOPE 2.0)';
COMMENT ON TABLE "hope_compliance_metrics" IS 'Tracks hospice compliance with 90% HOPE submission threshold - non-compliance results in 4% Medicare payment reduction';
COMMENT ON TABLE "hope_symptom_tracking" IS 'Tracks individual symptoms for SFV (Symptom Follow-up Visit) triggering and resolution';
COMMENT ON TABLE "hope_section_responses" IS 'Stores structured responses for each HOPE section (A, F, I, J, M, N, Z)';
