-- Migration: 0034_cap_tracking_schema.sql
-- Date: 2025-12-31
-- Description: Medicare hospice cap tracking schema
--
-- Medicare hospice cap requirements:
-- - Cap year runs Oct 1 - Sep 30 (federal fiscal year)
-- - FY 2025 cap: $34,465.34 per beneficiary
-- - Hospice must track payments to ensure they don't exceed cap
-- - Alerts at 80%, 90%, 95% utilization thresholds
--
-- Compliance: 42 CFR 418.309, Medicare hospice cap calculation

-- =====================================================
-- STEP 1: Create cap_tracking table
-- =====================================================

CREATE TABLE IF NOT EXISTS "cap_tracking" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),

  -- Cap year (Oct 1 - Sep 30)
  "cap_year" integer NOT NULL, -- e.g., 2025 for cap year 2024-2025
  "cap_year_start_date" date NOT NULL, -- Oct 1
  "cap_year_end_date" date NOT NULL, -- Sep 30

  -- Cap amount (in cents for precision)
  "cap_amount_cents" integer NOT NULL, -- $34,465.34 = 3446534 cents
  "total_payments_cents" integer NOT NULL DEFAULT 0, -- Total payments applied in cap year
  "remaining_cap_cents" integer NOT NULL, -- Remaining cap amount

  -- Cap utilization percentage (for easier querying)
  "utilization_percentage" numeric(5, 2) DEFAULT 0, -- e.g., 85.50 for 85.5%

  -- Cap exceeded tracking
  "cap_exceeded" boolean NOT NULL DEFAULT false,
  "cap_exceeded_date" date,
  "cap_exceeded_amount_cents" integer, -- Amount over cap

  -- Alert thresholds tracking
  "alert_80_triggered" boolean DEFAULT false,
  "alert_80_date" timestamp,
  "alert_90_triggered" boolean DEFAULT false,
  "alert_90_date" timestamp,
  "alert_95_triggered" boolean DEFAULT false,
  "alert_95_date" timestamp,

  -- Calculation tracking
  "last_calculated_at" timestamp,
  "calculation_status" varchar(50) DEFAULT 'CURRENT', -- CURRENT, PENDING_RECALC, ERROR

  -- Notes and metadata
  "notes" text,
  "metadata" jsonb,

  -- Audit fields
  "created_by_id" text REFERENCES "users"("id"),
  "updated_by_id" text REFERENCES "users"("id"),
  "deleted_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- =====================================================
-- STEP 2: Create unique constraint and indexes
-- =====================================================

-- Unique constraint: one record per patient per cap year
CREATE UNIQUE INDEX IF NOT EXISTS "unique_patient_cap_year" ON "cap_tracking"("patient_id", "cap_year");

-- Performance indexes
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_patient_id" ON "cap_tracking"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_cap_year" ON "cap_tracking"("cap_year");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_cap_exceeded" ON "cap_tracking"("cap_exceeded");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_utilization" ON "cap_tracking"("utilization_percentage");
CREATE INDEX IF NOT EXISTS "idx_cap_tracking_deleted_at" ON "cap_tracking"("deleted_at");

-- =====================================================
-- STEP 3: Add comments for documentation
-- =====================================================

COMMENT ON TABLE "cap_tracking" IS 'Medicare hospice cap tracking per beneficiary per cap year (Oct 1 - Sep 30)';
COMMENT ON COLUMN "cap_tracking"."cap_year" IS 'Federal fiscal year (e.g., 2025 = Oct 1, 2024 - Sep 30, 2025)';
COMMENT ON COLUMN "cap_tracking"."cap_amount_cents" IS 'Annual cap amount in cents (FY 2025: $34,465.34 = 3446534)';
COMMENT ON COLUMN "cap_tracking"."total_payments_cents" IS 'Sum of Medicare payments for this patient in the cap year';
COMMENT ON COLUMN "cap_tracking"."remaining_cap_cents" IS 'cap_amount_cents - total_payments_cents';
COMMENT ON COLUMN "cap_tracking"."utilization_percentage" IS 'Percentage of cap utilized (for threshold alerting)';
COMMENT ON COLUMN "cap_tracking"."cap_exceeded" IS 'True if total_payments_cents > cap_amount_cents';
COMMENT ON COLUMN "cap_tracking"."calculation_status" IS 'CURRENT (up-to-date), PENDING_RECALC (needs recalc), ERROR (calculation failed)';
