-- Wong-Baker FACES Pain Rating Scale Schema Migration
-- Visual pain assessment tool using facial expressions
-- Designed for pediatric patients, adults with language barriers, and those who prefer visual scales

CREATE TABLE IF NOT EXISTS "wong_baker_faces_scales" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "patient_id" bigint NOT NULL REFERENCES "patients"("id"),
  "encounter_id" bigint,
  "note_id" bigint,

  -- Assessment metadata
  "assessment_date" timestamp DEFAULT now() NOT NULL,
  "assessment_type" varchar(50),
  "assessment_context" varchar(100),
  "assessed_by_id" bigint,

  -- Patient population context
  "patient_population" varchar(50),
  "patient_age_years" integer,

  -- Wong-Baker FACES scoring
  "face_selected" integer NOT NULL,
  "pain_score" integer NOT NULL,
  "face_image_ref" varchar(100),
  "patient_description" text,

  -- Pain interpretation
  "pain_severity" varchar(50),
  "pain_present" boolean DEFAULT false,

  -- Clinical context
  "pain_status" varchar(50),
  "pain_location" varchar(255),
  "pain_location_notes" text,
  "suspected_cause" varchar(255),
  "suspected_cause_notes" text,
  "pain_duration" varchar(100),
  "pain_onset" varchar(255),

  -- Assessment appropriateness
  "scale_comprehension" varchar(50),
  "comprehension_notes" text,
  "assistance_needed" boolean DEFAULT false,
  "assistance_type" varchar(100),
  "alternative_scale_recommended" boolean DEFAULT false,
  "recommended_alternative" varchar(100),

  -- Intervention tracking
  "intervention_provided" boolean DEFAULT false,
  "intervention_type" varchar(100),
  "medication_administered" varchar(255),
  "medication_dose" varchar(100),
  "medication_route" varchar(50),
  "medication_time" timestamp,
  "non_pharm_interventions" jsonb,
  "reassessment_time" timestamp,
  "reassessment_score" integer,
  "reassessment_face" integer,
  "intervention_effectiveness" varchar(50),

  -- Hospice care specific fields
  "comfort_goal_met" boolean,
  "comfort_goal_notes" text,
  "acceptable_pain_face" integer,
  "acceptable_pain_score" integer,
  "caregiver_present" boolean,
  "caregiver_observations" text,
  "caregiver_education_provided" boolean,
  "parent_involved" boolean,
  "parent_pain_estimate" integer,
  "care_plan_update_needed" boolean,
  "care_plan_recommendations" text,

  -- Clinical notes and summary
  "clinical_notes" text,
  "assessment_summary" text,
  "follow_up_plan" text,

  -- Signature and compliance (21 CFR Part 11)
  "signature_id" bigint,
  "signed_at" timestamp,
  "signed_by_id" bigint,

  -- Amendment tracking
  "amended" boolean DEFAULT false,
  "amendment_reason" text,
  "amended_at" timestamp,
  "amended_by_id" bigint,

  -- Audit fields
  "created_by_id" bigint,
  "updated_by_id" bigint,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

-- Performance indexes for common queries
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_patient_id" ON "wong_baker_faces_scales" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_assessment_date" ON "wong_baker_faces_scales" ("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_pain_score" ON "wong_baker_faces_scales" ("pain_score");
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_patient_date" ON "wong_baker_faces_scales" ("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_patient_score" ON "wong_baker_faces_scales" ("patient_id", "pain_score");
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_face_selected" ON "wong_baker_faces_scales" ("face_selected");
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_population" ON "wong_baker_faces_scales" ("patient_population");
CREATE INDEX IF NOT EXISTS "idx_wong_baker_faces_severity" ON "wong_baker_faces_scales" ("pain_severity");

-- Add constraint for valid face_selected values (0-5)
ALTER TABLE "wong_baker_faces_scales" ADD CONSTRAINT "chk_face_selected" CHECK ("face_selected" >= 0 AND "face_selected" <= 5);

-- Add constraint for valid pain_score values (0, 2, 4, 6, 8, 10)
ALTER TABLE "wong_baker_faces_scales" ADD CONSTRAINT "chk_pain_score" CHECK ("pain_score" IN (0, 2, 4, 6, 8, 10));

-- Add constraint for valid reassessment_face values (0-5 or NULL)
ALTER TABLE "wong_baker_faces_scales" ADD CONSTRAINT "chk_reassessment_face" CHECK ("reassessment_face" IS NULL OR ("reassessment_face" >= 0 AND "reassessment_face" <= 5));

-- Add constraint for valid reassessment_score values (0, 2, 4, 6, 8, 10 or NULL)
ALTER TABLE "wong_baker_faces_scales" ADD CONSTRAINT "chk_reassessment_score" CHECK ("reassessment_score" IS NULL OR "reassessment_score" IN (0, 2, 4, 6, 8, 10));

-- Add constraint for valid acceptable_pain_face values (0-5 or NULL)
ALTER TABLE "wong_baker_faces_scales" ADD CONSTRAINT "chk_acceptable_pain_face" CHECK ("acceptable_pain_face" IS NULL OR ("acceptable_pain_face" >= 0 AND "acceptable_pain_face" <= 5));

-- Add constraint for valid acceptable_pain_score values (0, 2, 4, 6, 8, 10 or NULL)
ALTER TABLE "wong_baker_faces_scales" ADD CONSTRAINT "chk_acceptable_pain_score" CHECK ("acceptable_pain_score" IS NULL OR "acceptable_pain_score" IN (0, 2, 4, 6, 8, 10));

-- Add constraint for valid parent_pain_estimate values (0-10 or NULL)
ALTER TABLE "wong_baker_faces_scales" ADD CONSTRAINT "chk_parent_pain_estimate" CHECK ("parent_pain_estimate" IS NULL OR ("parent_pain_estimate" >= 0 AND "parent_pain_estimate" <= 10));
