-- Scheduling Conflicts Schema Migration
-- Adds conflict tracking for visit scheduling to detect and manage
-- double-bookings, time overlaps, and other scheduling conflicts

-- Create scheduling_conflicts table
CREATE TABLE IF NOT EXISTS "scheduling_conflicts" (
    "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Conflicting visits (references scheduled_visits)
    "visit_id_1" BIGINT NOT NULL,
    "visit_id_2" BIGINT NOT NULL,

    -- Staff and patient involved (may be same or different)
    "staff_id" BIGINT,
    "patient_id" BIGINT,

    -- Conflict details
    "conflict_type" VARCHAR(50) NOT NULL,
    "conflict_severity" VARCHAR(50) DEFAULT 'MEDIUM' NOT NULL,
    "conflict_status" VARCHAR(50) DEFAULT 'DETECTED' NOT NULL,

    -- Conflict time window
    "conflict_date" DATE NOT NULL,
    "conflict_start_time" TIME,
    "conflict_end_time" TIME,
    "overlap_minutes" INTEGER,

    -- Description of the conflict
    "conflict_description" TEXT,

    -- Resolution
    "resolution_type" VARCHAR(100),
    "resolution_notes" TEXT,
    "resolved_by_id" TEXT,
    "resolved_at" TIMESTAMP,

    -- Auto-detection metadata
    "detected_by" VARCHAR(100) DEFAULT 'SYSTEM',
    "detection_rule" VARCHAR(100),

    -- Notification tracking
    "notification_sent" BOOLEAN DEFAULT false,
    "notification_sent_at" TIMESTAMP,
    "notification_recipients" JSONB,

    -- Additional data
    "metadata" JSONB,

    -- Audit fields
    "created_by_id" TEXT,
    "updated_by_id" TEXT,
    "deleted_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
    "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Add foreign key constraints
ALTER TABLE "scheduling_conflicts"
    ADD CONSTRAINT "scheduling_conflicts_visit_id_1_fk"
    FOREIGN KEY ("visit_id_1") REFERENCES "scheduled_visits"("id") ON DELETE CASCADE;

ALTER TABLE "scheduling_conflicts"
    ADD CONSTRAINT "scheduling_conflicts_visit_id_2_fk"
    FOREIGN KEY ("visit_id_2") REFERENCES "scheduled_visits"("id") ON DELETE CASCADE;

ALTER TABLE "scheduling_conflicts"
    ADD CONSTRAINT "scheduling_conflicts_staff_id_fk"
    FOREIGN KEY ("staff_id") REFERENCES "staff_profiles"("id") ON DELETE SET NULL;

ALTER TABLE "scheduling_conflicts"
    ADD CONSTRAINT "scheduling_conflicts_patient_id_fk"
    FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE SET NULL;

ALTER TABLE "scheduling_conflicts"
    ADD CONSTRAINT "scheduling_conflicts_resolved_by_fk"
    FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE SET NULL;

ALTER TABLE "scheduling_conflicts"
    ADD CONSTRAINT "scheduling_conflicts_created_by_fk"
    FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL;

ALTER TABLE "scheduling_conflicts"
    ADD CONSTRAINT "scheduling_conflicts_updated_by_fk"
    FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL;

-- Create indexes for common query patterns
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_visit_id_1" ON "scheduling_conflicts" ("visit_id_1");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_visit_id_2" ON "scheduling_conflicts" ("visit_id_2");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_staff_id" ON "scheduling_conflicts" ("staff_id");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_patient_id" ON "scheduling_conflicts" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_conflict_date" ON "scheduling_conflicts" ("conflict_date");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_conflict_status" ON "scheduling_conflicts" ("conflict_status");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_conflict_type" ON "scheduling_conflicts" ("conflict_type");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_conflict_severity" ON "scheduling_conflicts" ("conflict_severity");
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_deleted_at" ON "scheduling_conflicts" ("deleted_at") WHERE "deleted_at" IS NULL;

-- Create composite index for unresolved conflicts query
CREATE INDEX IF NOT EXISTS "idx_scheduling_conflicts_unresolved"
    ON "scheduling_conflicts" ("conflict_status", "deleted_at")
    WHERE "deleted_at" IS NULL AND "conflict_status" IN ('DETECTED', 'FLAGGED', 'ACKNOWLEDGED');

-- Add comment for documentation
COMMENT ON TABLE "scheduling_conflicts" IS 'Tracks scheduling conflicts such as double-bookings and time overlaps for visit scheduling management';
COMMENT ON COLUMN "scheduling_conflicts"."conflict_type" IS 'Type: DOUBLE_BOOKING, TIME_OVERLAP, STAFF_UNAVAILABLE, TRAVEL_TIME, SKILL_MISMATCH';
COMMENT ON COLUMN "scheduling_conflicts"."conflict_severity" IS 'Severity: CRITICAL, HIGH, MEDIUM, LOW';
COMMENT ON COLUMN "scheduling_conflicts"."conflict_status" IS 'Status: DETECTED, FLAGGED, ACKNOWLEDGED, RESOLVED, IGNORED';
COMMENT ON COLUMN "scheduling_conflicts"."resolution_type" IS 'Resolution: RESCHEDULE_VISIT_1, RESCHEDULE_VISIT_2, REASSIGN_STAFF, CANCEL_VISIT, COMBINE_VISITS, MANUAL';
