-- Migration: 0039_bereavement_enhancements
-- Description: Enhance bereavement schema with comprehensive services management
-- Date: 2025-12-31

-- ============================================================================
-- ENHANCE BEREAVEMENT_CONTACTS TABLE
-- Add grief assessment, consent tracking, and preferred contact times
-- ============================================================================

ALTER TABLE bereavement_contacts
ADD COLUMN IF NOT EXISTS preferred_contact_times text,
ADD COLUMN IF NOT EXISTS grief_assessment_score integer,
ADD COLUMN IF NOT EXISTS grief_assessment_tool varchar(100),
ADD COLUMN IF NOT EXISTS grief_assessment_date date,
ADD COLUMN IF NOT EXISTS grief_stage varchar(50),
ADD COLUMN IF NOT EXISTS grief_notes text,
ADD COLUMN IF NOT EXISTS consent_status varchar(50) DEFAULT 'PENDING',
ADD COLUMN IF NOT EXISTS consent_date date,
ADD COLUMN IF NOT EXISTS consent_signature jsonb,
ADD COLUMN IF NOT EXISTS privacy_preferences jsonb,
ADD COLUMN IF NOT EXISTS can_share_info boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS can_contact_via_phone boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS can_contact_via_email boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS can_contact_via_mail boolean DEFAULT true;

-- Add comments for new columns
COMMENT ON COLUMN bereavement_contacts.grief_assessment_score IS 'Standardized grief assessment score (e.g., 0-100)';
COMMENT ON COLUMN bereavement_contacts.grief_assessment_tool IS 'Assessment tool used: PG-13, ICG, TRIG, etc.';
COMMENT ON COLUMN bereavement_contacts.consent_status IS 'PENDING, GRANTED, DECLINED, WITHDRAWN';
COMMENT ON COLUMN bereavement_contacts.privacy_preferences IS 'JSON object with granular privacy settings';

-- ============================================================================
-- CREATE BEREAVEMENT_FOLLOW_UPS TABLE
-- Track scheduled and completed follow-ups at specific milestones
-- Standard milestones: 1 week, 1 month, 3 months, 6 months, 1 year
-- ============================================================================

CREATE TABLE IF NOT EXISTS bereavement_follow_ups (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bereavement_case_id bigint NOT NULL REFERENCES bereavement_cases(id),
    bereavement_contact_id bigint REFERENCES bereavement_contacts(id),

    -- Follow-up milestone
    milestone_type varchar(50) NOT NULL, -- 1_WEEK, 1_MONTH, 3_MONTHS, 6_MONTHS, 1_YEAR, CUSTOM
    milestone_description text,

    -- Scheduling
    scheduled_date date NOT NULL,
    reminder_sent boolean DEFAULT false,
    reminder_sent_date date,

    -- Contact details
    contact_method varchar(50), -- PHONE_CALL, HOME_VISIT, LETTER, EMAIL, SYMPATHY_CARD

    -- Completion
    follow_up_status varchar(50) DEFAULT 'SCHEDULED', -- SCHEDULED, COMPLETED, MISSED, RESCHEDULED, CANCELLED, DECLINED
    completed_date date,
    completed_by_id text REFERENCES "user"(id),

    -- Outcome
    contact_outcome varchar(50), -- SUCCESSFUL, NO_ANSWER, LEFT_MESSAGE, DECLINED, OTHER
    family_wellbeing_assessment varchar(50), -- COPING_WELL, MILD_DISTRESS, MODERATE_DISTRESS, SEVERE_DISTRESS, CRISIS
    wellbeing_score integer, -- 1-10 scale

    -- Issues and referrals
    issues_identified text,
    additional_support_needed boolean DEFAULT false,
    support_type_needed text,
    referrals_made text,
    external_referrals jsonb,

    -- Documentation
    follow_up_notes text,
    family_feedback text,

    -- Next steps
    follow_up_required boolean DEFAULT false,
    next_follow_up_date date,
    next_follow_up_notes text,

    -- Signature
    signature jsonb,

    -- Metadata
    metadata jsonb,

    -- Audit fields
    created_by_id text REFERENCES "user"(id),
    updated_by_id text REFERENCES "user"(id),
    deleted_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

-- Create indexes for follow-ups
CREATE INDEX IF NOT EXISTS idx_bereavement_follow_ups_case_id ON bereavement_follow_ups(bereavement_case_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_follow_ups_contact_id ON bereavement_follow_ups(bereavement_contact_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_follow_ups_scheduled_date ON bereavement_follow_ups(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_bereavement_follow_ups_status ON bereavement_follow_ups(follow_up_status);
CREATE INDEX IF NOT EXISTS idx_bereavement_follow_ups_milestone ON bereavement_follow_ups(milestone_type);

-- Add table comment
COMMENT ON TABLE bereavement_follow_ups IS 'Tracks scheduled and completed follow-up contacts at specific milestones (1 week, 1 month, 3 months, 6 months, 1 year)';

-- ============================================================================
-- CREATE BEREAVEMENT_RESOURCES TABLE
-- Track support resources provided to bereaved families
-- ============================================================================

CREATE TABLE IF NOT EXISTS bereavement_resources (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bereavement_case_id bigint NOT NULL REFERENCES bereavement_cases(id),
    bereavement_contact_id bigint REFERENCES bereavement_contacts(id),

    -- Resource details
    resource_type varchar(100) NOT NULL, -- LITERATURE, BROCHURE, SUPPORT_GROUP, REFERRAL, MEMORIAL_SERVICE, SYMPATHY_CARD, COUNSELING_SESSION, BOOK, WEBSITE, HOTLINE
    resource_name varchar(255) NOT NULL,
    resource_description text,

    -- Resource specifics
    resource_url text,
    resource_phone varchar(50),
    resource_address text,
    resource_contact varchar(255),

    -- Provision details
    date_provided date NOT NULL,
    provided_by_id text REFERENCES "user"(id),
    delivery_method varchar(50), -- IN_PERSON, MAILED, EMAILED, PHONE

    -- Recurring resources
    is_recurring boolean DEFAULT false,
    recurrence_frequency varchar(50), -- WEEKLY, BIWEEKLY, MONTHLY, AS_NEEDED
    next_occurrence_date date,

    -- Feedback and utilization
    resource_utilized boolean,
    utilization_date date,
    family_feedback text,
    feedback_rating integer, -- 1-5 star rating
    was_helpful boolean,

    -- External referral tracking
    is_external_referral boolean DEFAULT false,
    external_organization varchar(255),
    referral_status varchar(50), -- PENDING, ACCEPTED, COMPLETED, DECLINED
    referral_outcome text,

    -- Notes
    notes text,
    follow_up_needed boolean DEFAULT false,
    follow_up_notes text,

    -- Metadata
    metadata jsonb,

    -- Audit fields
    created_by_id text REFERENCES "user"(id),
    updated_by_id text REFERENCES "user"(id),
    deleted_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

-- Create indexes for resources
CREATE INDEX IF NOT EXISTS idx_bereavement_resources_case_id ON bereavement_resources(bereavement_case_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_resources_contact_id ON bereavement_resources(bereavement_contact_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_resources_type ON bereavement_resources(resource_type);
CREATE INDEX IF NOT EXISTS idx_bereavement_resources_date ON bereavement_resources(date_provided);

-- Add table comment
COMMENT ON TABLE bereavement_resources IS 'Tracks support resources provided to bereaved families (literature, referrals, support groups, etc.)';

-- ============================================================================
-- CREATE BEREAVEMENT_MEMORIAL_SERVICES TABLE
-- Track memorial services and events
-- ============================================================================

CREATE TABLE IF NOT EXISTS bereavement_memorial_services (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Service details
    service_name varchar(255) NOT NULL,
    service_type varchar(100), -- ANNUAL_MEMORIAL, HOLIDAY_REMEMBRANCE, CANDLE_LIGHTING, BUTTERFLY_RELEASE, TREE_PLANTING, CUSTOM
    service_description text,

    -- Date and location
    service_date date NOT NULL,
    service_time varchar(20),
    duration_minutes integer,
    location text,
    is_virtual boolean DEFAULT false,
    virtual_link text,

    -- Organizers
    coordinator_id text REFERENCES "user"(id),
    coordinator_name varchar(255),

    -- Service program
    program_details text,
    speakers jsonb,
    music_selections text,
    readings text,

    -- Capacity and registration
    max_attendees integer,
    registration_required boolean DEFAULT false,
    registration_deadline date,

    -- Service status
    service_status varchar(50) DEFAULT 'PLANNED', -- PLANNED, CONFIRMED, IN_PROGRESS, COMPLETED, CANCELLED
    actual_attendee_count integer,

    -- Post-service
    service_notes text,
    feedback_summary text,

    -- Metadata
    metadata jsonb,

    -- Audit fields
    created_by_id text REFERENCES "user"(id),
    updated_by_id text REFERENCES "user"(id),
    deleted_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

-- Create indexes for memorial services
CREATE INDEX IF NOT EXISTS idx_bereavement_memorial_services_date ON bereavement_memorial_services(service_date);
CREATE INDEX IF NOT EXISTS idx_bereavement_memorial_services_status ON bereavement_memorial_services(service_status);
CREATE INDEX IF NOT EXISTS idx_bereavement_memorial_services_type ON bereavement_memorial_services(service_type);

-- Add table comment
COMMENT ON TABLE bereavement_memorial_services IS 'Tracks memorial services and remembrance events for bereaved families';

-- ============================================================================
-- CREATE BEREAVEMENT_MEMORIAL_ATTENDEES TABLE
-- Track attendance at memorial services
-- ============================================================================

CREATE TABLE IF NOT EXISTS bereavement_memorial_attendees (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    memorial_service_id bigint NOT NULL REFERENCES bereavement_memorial_services(id),
    bereavement_case_id bigint REFERENCES bereavement_cases(id),
    bereavement_contact_id bigint REFERENCES bereavement_contacts(id),

    -- Attendee info
    attendee_name varchar(255),
    attendee_email varchar(255),
    attendee_phone varchar(50),
    relationship_to_deceased varchar(100),
    patient_remembered varchar(255),

    -- Registration
    registration_date date,
    guest_count integer DEFAULT 1,

    -- Special requests
    special_requests text,
    accessibility_needs text,
    dietary_restrictions text,

    -- Attendance
    rsvp_status varchar(50) DEFAULT 'PENDING', -- PENDING, CONFIRMED, DECLINED, WAITLIST
    attended boolean,
    attendance_notes text,

    -- Feedback
    provided_feedback boolean DEFAULT false,
    feedback text,
    feedback_date date,

    -- Metadata
    metadata jsonb,

    -- Audit fields
    created_by_id text REFERENCES "user"(id),
    updated_by_id text REFERENCES "user"(id),
    deleted_at timestamp,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

-- Create indexes for memorial attendees
CREATE INDEX IF NOT EXISTS idx_bereavement_memorial_attendees_service_id ON bereavement_memorial_attendees(memorial_service_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_memorial_attendees_case_id ON bereavement_memorial_attendees(bereavement_case_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_memorial_attendees_contact_id ON bereavement_memorial_attendees(bereavement_contact_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_memorial_attendees_rsvp ON bereavement_memorial_attendees(rsvp_status);

-- Add table comment
COMMENT ON TABLE bereavement_memorial_attendees IS 'Tracks attendance and registration for memorial services';

-- ============================================================================
-- CREATE INDEXES ON EXISTING BEREAVEMENT TABLES
-- Optimize query performance for common access patterns
-- ============================================================================

-- Bereavement cases indexes
CREATE INDEX IF NOT EXISTS idx_bereavement_cases_patient_id ON bereavement_cases(patient_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_cases_status ON bereavement_cases(case_status);
CREATE INDEX IF NOT EXISTS idx_bereavement_cases_death_date ON bereavement_cases(date_of_death);
CREATE INDEX IF NOT EXISTS idx_bereavement_cases_counselor ON bereavement_cases(assigned_counselor_id);

-- Bereavement contacts indexes
CREATE INDEX IF NOT EXISTS idx_bereavement_contacts_case_id ON bereavement_contacts(bereavement_case_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_contacts_primary ON bereavement_contacts(is_primary_contact);

-- Bereavement plans indexes
CREATE INDEX IF NOT EXISTS idx_bereavement_plans_case_id ON bereavement_plans(bereavement_case_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_plans_status ON bereavement_plans(plan_status);

-- Bereavement encounters indexes
CREATE INDEX IF NOT EXISTS idx_bereavement_encounters_case_id ON bereavement_encounters(bereavement_case_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_encounters_contact_id ON bereavement_encounters(bereavement_contact_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_encounters_date ON bereavement_encounters(encounter_date);

-- Risk assessments indexes
CREATE INDEX IF NOT EXISTS idx_bereavement_risk_assessments_case_id ON bereavement_risk_assessments(bereavement_case_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_risk_assessments_contact_id ON bereavement_risk_assessments(bereavement_contact_id);
CREATE INDEX IF NOT EXISTS idx_bereavement_risk_assessments_level ON bereavement_risk_assessments(risk_level);
