-- Migration: Comprehensive Body Systems Assessment Schemas
-- Description: Creates five comprehensive medical body system assessment tables
-- for cardiac, endocrine, hematological, integumentary, and respiratory systems

-- =========================================
-- CARDIAC SYSTEM ASSESSMENTS
-- =========================================
CREATE TABLE IF NOT EXISTS "cardiac_system_assessments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),
  "encounter_id" BIGINT,
  "note_id" BIGINT,

  -- Assessment metadata
  "assessment_date" TIMESTAMP DEFAULT NOW() NOT NULL,
  "assessment_type" VARCHAR(50),
  "assessed_by_id" BIGINT,

  -- Overall cardiac status
  "overall_status" VARCHAR(50),
  "cardiac_history" TEXT,
  "known_conditions" JSONB,

  -- Heart rate and rhythm
  "heart_rate" INTEGER,
  "heart_rate_location" VARCHAR(50),
  "heart_rhythm" VARCHAR(50),
  "rhythm_description" VARCHAR(255),
  "pulse_quality" VARCHAR(50),
  "pulse_deficit" BOOLEAN DEFAULT FALSE,
  "pulse_deficit_value" INTEGER,
  "heart_rate_notes" TEXT,

  -- Heart sounds
  "s1_sound" VARCHAR(50),
  "s2_sound" VARCHAR(50),
  "s3_sound" BOOLEAN DEFAULT FALSE,
  "s4_sound" BOOLEAN DEFAULT FALSE,
  "extra_sounds" VARCHAR(255),
  "heart_sounds_notes" TEXT,

  -- Murmurs
  "murmur_present" BOOLEAN DEFAULT FALSE,
  "murmur_type" VARCHAR(50),
  "murmur_grade" VARCHAR(20),
  "murmur_location" VARCHAR(100),
  "murmur_radiation" VARCHAR(255),
  "murmur_quality" VARCHAR(100),
  "murmur_timing" VARCHAR(100),
  "murmur_notes" TEXT,

  -- Blood pressure
  "bp_systolic" INTEGER,
  "bp_diastolic" INTEGER,
  "bp_position" VARCHAR(50),
  "bp_location" VARCHAR(50),
  "bp_classification" VARCHAR(50),
  "orthostatic_bp_checked" BOOLEAN DEFAULT FALSE,
  "orthostatic_systolic_supine" INTEGER,
  "orthostatic_systolic_standing" INTEGER,
  "orthostatic_diastolic_supine" INTEGER,
  "orthostatic_diastolic_standing" INTEGER,
  "orthostatic_positive" BOOLEAN DEFAULT FALSE,
  "mean_arterial_pressure" INTEGER,
  "bp_notes" TEXT,

  -- Peripheral pulses
  "pulse_carotid_right" VARCHAR(10),
  "pulse_carotid_left" VARCHAR(10),
  "pulse_brachial_right" VARCHAR(10),
  "pulse_brachial_left" VARCHAR(10),
  "pulse_radial_right" VARCHAR(10),
  "pulse_radial_left" VARCHAR(10),
  "pulse_femoral_right" VARCHAR(10),
  "pulse_femoral_left" VARCHAR(10),
  "pulse_popliteal_right" VARCHAR(10),
  "pulse_popliteal_left" VARCHAR(10),
  "pulse_dorsalis_pedis_right" VARCHAR(10),
  "pulse_dorsalis_pedis_left" VARCHAR(10),
  "pulse_posterior_tibial_right" VARCHAR(10),
  "pulse_posterior_tibial_left" VARCHAR(10),
  "peripheral_pulses_notes" TEXT,

  -- Edema assessment
  "edema_present" BOOLEAN DEFAULT FALSE,
  "edema_type" VARCHAR(50),
  "edema_severity" VARCHAR(20),
  "edema_location" JSONB,
  "edema_bilateral" BOOLEAN DEFAULT TRUE,
  "edema_duration" VARCHAR(100),
  "edema_notes" TEXT,

  -- Perfusion and circulation
  "capillary_refill_seconds" DECIMAL(3,1),
  "capillary_refill_location" VARCHAR(50),
  "skin_color_extremities" VARCHAR(100),
  "skin_temperature_extremities" VARCHAR(50),
  "hair_distribution_lower_ext" VARCHAR(50),
  "nail_condition" VARCHAR(255),
  "perfusion_notes" TEXT,

  -- Jugular venous assessment
  "jvd_present" BOOLEAN DEFAULT FALSE,
  "jvd_cm_above_sternal_angle" DECIMAL(4,1),
  "hepatojugular_reflux" BOOLEAN DEFAULT FALSE,
  "jvd_notes" TEXT,

  -- Cardiac symptoms
  "chest_pain_present" BOOLEAN DEFAULT FALSE,
  "chest_pain_type" VARCHAR(100),
  "chest_pain_severity" INTEGER,
  "chest_pain_location" VARCHAR(255),
  "chest_pain_radiation" VARCHAR(255),
  "chest_pain_quality" VARCHAR(100),
  "chest_pain_duration" VARCHAR(100),
  "chest_pain_aggravating" TEXT,
  "chest_pain_relieving" TEXT,
  "dyspnea_present" BOOLEAN DEFAULT FALSE,
  "dyspnea_type" VARCHAR(100),
  "dyspnea_severity" VARCHAR(50),
  "pillows_for_sleep" INTEGER,
  "palpitations_present" BOOLEAN DEFAULT FALSE,
  "palpitations_description" TEXT,
  "syncope_history" BOOLEAN DEFAULT FALSE,
  "presyncope_history" BOOLEAN DEFAULT FALSE,
  "fatigue_present" BOOLEAN DEFAULT FALSE,
  "fatigue_severity" VARCHAR(50),
  "cardiac_symptoms_notes" TEXT,

  -- Functional status
  "nyha_class" VARCHAR(20),
  "activity_tolerance" VARCHAR(100),
  "exercise_capacity_mets" DECIMAL(4,1),
  "functional_status_notes" TEXT,

  -- Cardiac devices
  "pacemaker_present" BOOLEAN DEFAULT FALSE,
  "pacemaker_type" VARCHAR(100),
  "pacemaker_last_check" TIMESTAMP,
  "aicd_present" BOOLEAN DEFAULT FALSE,
  "aicd_last_check" TIMESTAMP,
  "device_functioning" BOOLEAN DEFAULT TRUE,
  "device_notes" TEXT,

  -- Clinical notes and summary
  "clinical_notes" TEXT,
  "assessment_summary" TEXT,
  "follow_up_plan" TEXT,
  "provider_notified" BOOLEAN DEFAULT FALSE,
  "provider_notified_reason" TEXT,

  -- Signature and compliance
  "signature_id" BIGINT,
  "signed_at" TIMESTAMP,
  "signed_by_id" BIGINT,
  "amended" BOOLEAN DEFAULT FALSE,
  "amendment_reason" TEXT,
  "amended_at" TIMESTAMP,
  "amended_by_id" BIGINT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for cardiac_system_assessments
CREATE INDEX IF NOT EXISTS "idx_cardiac_system_assessments_patient_id" ON "cardiac_system_assessments" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_cardiac_system_assessments_date" ON "cardiac_system_assessments" ("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_cardiac_system_assessments_patient_date" ON "cardiac_system_assessments" ("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_cardiac_system_assessments_status" ON "cardiac_system_assessments" ("overall_status");
CREATE INDEX IF NOT EXISTS "idx_cardiac_system_assessments_nyha" ON "cardiac_system_assessments" ("nyha_class");


-- =========================================
-- ENDOCRINE SYSTEM ASSESSMENTS
-- =========================================
CREATE TABLE IF NOT EXISTS "endocrine_system_assessments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),
  "encounter_id" BIGINT,
  "note_id" BIGINT,

  -- Assessment metadata
  "assessment_date" TIMESTAMP DEFAULT NOW() NOT NULL,
  "assessment_type" VARCHAR(50),
  "assessed_by_id" BIGINT,

  -- Overall endocrine status
  "overall_status" VARCHAR(50),
  "endocrine_history" TEXT,
  "known_conditions" JSONB,

  -- Thyroid assessment
  "thyroid_palpable" BOOLEAN DEFAULT FALSE,
  "thyroid_size" VARCHAR(50),
  "thyroid_symmetry" VARCHAR(50),
  "thyroid_consistency" VARCHAR(50),
  "thyroid_tenderness" BOOLEAN DEFAULT FALSE,
  "thyroid_nodules" BOOLEAN DEFAULT FALSE,
  "thyroid_nodule_description" TEXT,
  "thyroid_bruit" BOOLEAN DEFAULT FALSE,
  "thyroid_movement_swallowing" VARCHAR(50),

  -- Hypothyroid symptoms
  "fatigue_present" BOOLEAN DEFAULT FALSE,
  "cold_intolerance" BOOLEAN DEFAULT FALSE,
  "weight_gain" BOOLEAN DEFAULT FALSE,
  "constipation" BOOLEAN DEFAULT FALSE,
  "dry_skin" BOOLEAN DEFAULT FALSE,
  "hair_loss" BOOLEAN DEFAULT FALSE,
  "bradycardia" BOOLEAN DEFAULT FALSE,
  "delayed_reflexes" BOOLEAN DEFAULT FALSE,
  "facial_puffiness" BOOLEAN DEFAULT FALSE,
  "voice_hoarseness" BOOLEAN DEFAULT FALSE,
  "hypothyroid_symptoms_notes" TEXT,

  -- Hyperthyroid symptoms
  "heat_intolerance" BOOLEAN DEFAULT FALSE,
  "weight_loss" BOOLEAN DEFAULT FALSE,
  "diarrhea" BOOLEAN DEFAULT FALSE,
  "sweating_excessive" BOOLEAN DEFAULT FALSE,
  "tremor_present" BOOLEAN DEFAULT FALSE,
  "tachycardia" BOOLEAN DEFAULT FALSE,
  "hyperreflexia" BOOLEAN DEFAULT FALSE,
  "anxiety_nervousness" BOOLEAN DEFAULT FALSE,
  "exophthalmos" BOOLEAN DEFAULT FALSE,
  "lid_lag" BOOLEAN DEFAULT FALSE,
  "hyperthyroid_symptoms_notes" TEXT,

  "thyroid_status" VARCHAR(50),
  "thyroid_notes" TEXT,

  -- Glucose metabolism / Diabetes
  "diabetes_type" VARCHAR(50),
  "diabetes_duration_years" INTEGER,
  "blood_glucose_fasting" INTEGER,
  "blood_glucose_random" INTEGER,
  "blood_glucose_time" TIMESTAMP,
  "glucose_monitoring_frequency" VARCHAR(100),
  "glucose_monitoring_method" VARCHAR(100),
  "hba1c_value" DECIMAL(4,1),
  "hba1c_date" TIMESTAMP,

  -- Hypoglycemia
  "hypoglycemia_episodes" BOOLEAN DEFAULT FALSE,
  "hypoglycemia_frequency" VARCHAR(100),
  "hypoglycemia_awareness" VARCHAR(50),
  "hypoglycemia_symptoms" JSONB,

  -- Hyperglycemia symptoms
  "polyuria" BOOLEAN DEFAULT FALSE,
  "polydipsia" BOOLEAN DEFAULT FALSE,
  "polyphagia" BOOLEAN DEFAULT FALSE,
  "blurred_vision" BOOLEAN DEFAULT FALSE,
  "slow_wound_healing" BOOLEAN DEFAULT FALSE,

  -- Diabetes complications
  "diabetic_neuropathy" BOOLEAN DEFAULT FALSE,
  "neuropathy_type" VARCHAR(100),
  "neuropathy_symptoms" TEXT,
  "diabetic_retinopathy" BOOLEAN DEFAULT FALSE,
  "diabetic_nephropathy" BOOLEAN DEFAULT FALSE,
  "diabetic_foot_exam" VARCHAR(50),
  "foot_sensation" VARCHAR(50),
  "monofilament_test" VARCHAR(50),
  "diabetes_management" VARCHAR(100),
  "insulin_regimen" TEXT,
  "diabetes_notes" TEXT,

  -- Adrenal function
  "adrenal_status" VARCHAR(50),
  "fatigue_adrenal" BOOLEAN DEFAULT FALSE,
  "muscle_weakness" BOOLEAN DEFAULT FALSE,
  "orthostatic_hypotension" BOOLEAN DEFAULT FALSE,
  "salt_craving" BOOLEAN DEFAULT FALSE,
  "hyperpigmentation" BOOLEAN DEFAULT FALSE,
  "nausea_vomiting" BOOLEAN DEFAULT FALSE,
  "abdominal_pain" BOOLEAN DEFAULT FALSE,

  -- Cushing's symptoms
  "moon_facies" BOOLEAN DEFAULT FALSE,
  "buffalo_hump" BOOLEAN DEFAULT FALSE,
  "central_obesity" BOOLEAN DEFAULT FALSE,
  "striae" BOOLEAN DEFAULT FALSE,
  "striae_color" VARCHAR(50),
  "easy_bruising" BOOLEAN DEFAULT FALSE,
  "proximal_muscle_weakness" BOOLEAN DEFAULT FALSE,
  "hirsutism" BOOLEAN DEFAULT FALSE,
  "steroid_use_current" BOOLEAN DEFAULT FALSE,
  "steroid_type" VARCHAR(100),
  "steroid_dose" VARCHAR(100),
  "steroid_duration" VARCHAR(100),
  "adrenal_notes" TEXT,

  -- Pituitary function
  "pituitary_status" VARCHAR(50),
  "growth_hormone_status" VARCHAR(50),
  "acromegaly_features" BOOLEAN DEFAULT FALSE,
  "prolactin_status" VARCHAR(50),
  "galactorrhea" BOOLEAN DEFAULT FALSE,
  "menstrual_irregularities" BOOLEAN DEFAULT FALSE,
  "pituitary_notes" TEXT,

  -- Parathyroid / Calcium metabolism
  "calcium_status" VARCHAR(50),
  "serum_calcium" DECIMAL(4,1),
  "ionized_calcium" DECIMAL(4,2),
  "bone_pain" BOOLEAN DEFAULT FALSE,
  "kidney_stones_history" BOOLEAN DEFAULT FALSE,
  "abdominal_complaints" BOOLEAN DEFAULT FALSE,
  "confusion_lethargy" BOOLEAN DEFAULT FALSE,
  "muscle_cramps" BOOLEAN DEFAULT FALSE,
  "paresthesias" BOOLEAN DEFAULT FALSE,
  "tetany" BOOLEAN DEFAULT FALSE,
  "chvostek_sign" BOOLEAN DEFAULT FALSE,
  "trousseau_sign" BOOLEAN DEFAULT FALSE,
  "parathyroid_notes" TEXT,

  -- Metabolic indicators
  "body_weight_kg" DECIMAL(6,2),
  "body_weight_lbs" DECIMAL(6,2),
  "weight_change_percent" DECIMAL(5,2),
  "weight_change_period_weeks" INTEGER,
  "weight_trend" VARCHAR(50),
  "bmi" DECIMAL(5,2),
  "waist_circumference_cm" DECIMAL(5,1),
  "waist_circumference_in" DECIMAL(5,1),
  "appetite_status" VARCHAR(50),
  "energy_level" VARCHAR(50),
  "sleep_disturbance" BOOLEAN DEFAULT FALSE,
  "sleep_disturbance_type" VARCHAR(100),
  "metabolic_notes" TEXT,

  -- Laboratory values
  "tsh_value" DECIMAL(6,3),
  "free_t4" DECIMAL(4,2),
  "free_t3" DECIMAL(4,2),
  "cortisol_am" DECIMAL(5,1),
  "cortisol_pm" DECIMAL(5,1),
  "acth" DECIMAL(5,1),
  "pth" DECIMAL(5,1),
  "vitamin_d" DECIMAL(5,1),
  "labs_date" TIMESTAMP,
  "labs_notes" TEXT,

  -- Clinical notes and summary
  "clinical_notes" TEXT,
  "assessment_summary" TEXT,
  "follow_up_plan" TEXT,
  "provider_notified" BOOLEAN DEFAULT FALSE,
  "provider_notified_reason" TEXT,

  -- Signature and compliance
  "signature_id" BIGINT,
  "signed_at" TIMESTAMP,
  "signed_by_id" BIGINT,
  "amended" BOOLEAN DEFAULT FALSE,
  "amendment_reason" TEXT,
  "amended_at" TIMESTAMP,
  "amended_by_id" BIGINT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for endocrine_system_assessments
CREATE INDEX IF NOT EXISTS "idx_endocrine_system_assessments_patient_id" ON "endocrine_system_assessments" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_endocrine_system_assessments_date" ON "endocrine_system_assessments" ("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_endocrine_system_assessments_patient_date" ON "endocrine_system_assessments" ("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_endocrine_system_assessments_status" ON "endocrine_system_assessments" ("overall_status");
CREATE INDEX IF NOT EXISTS "idx_endocrine_system_assessments_diabetes" ON "endocrine_system_assessments" ("diabetes_type");
CREATE INDEX IF NOT EXISTS "idx_endocrine_system_assessments_thyroid" ON "endocrine_system_assessments" ("thyroid_status");


-- =========================================
-- HEMATOLOGICAL SYSTEM ASSESSMENTS
-- =========================================
CREATE TABLE IF NOT EXISTS "hematological_system_assessments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),
  "encounter_id" BIGINT,
  "note_id" BIGINT,

  -- Assessment metadata
  "assessment_date" TIMESTAMP DEFAULT NOW() NOT NULL,
  "assessment_type" VARCHAR(50),
  "assessed_by_id" BIGINT,

  -- Overall hematological status
  "overall_status" VARCHAR(50),
  "hematological_history" TEXT,
  "known_conditions" JSONB,
  "blood_type" VARCHAR(10),

  -- CBC - White blood cells
  "wbc_count" DECIMAL(6,2),
  "wbc_unit" VARCHAR(20) DEFAULT 'K/uL',
  "wbc_status" VARCHAR(50),
  "neutrophils_percent" DECIMAL(5,2),
  "neutrophils_absolute" DECIMAL(6,2),
  "lymphocytes_percent" DECIMAL(5,2),
  "lymphocytes_absolute" DECIMAL(6,2),
  "monocytes_percent" DECIMAL(5,2),
  "eosinophils_percent" DECIMAL(5,2),
  "basophils_percent" DECIMAL(5,2),
  "bands_percent" DECIMAL(5,2),

  -- CBC - Red blood cells
  "rbc_count" DECIMAL(5,2),
  "rbc_unit" VARCHAR(20) DEFAULT 'M/uL',
  "hemoglobin" DECIMAL(5,1),
  "hematocrit" DECIMAL(5,1),
  "rbc_status" VARCHAR(50),
  "mcv" DECIMAL(5,1),
  "mch" DECIMAL(5,1),
  "mchc" DECIMAL(5,1),
  "rdw" DECIMAL(5,1),
  "reticulocyte_count" DECIMAL(5,2),

  -- CBC - Platelets
  "platelet_count" DECIMAL(7,0),
  "platelet_unit" VARCHAR(20) DEFAULT 'K/uL',
  "platelet_status" VARCHAR(50),
  "mpv" DECIMAL(4,1),
  "cbc_date" TIMESTAMP,
  "cbc_notes" TEXT,

  -- Anemia assessment
  "anemia_present" BOOLEAN DEFAULT FALSE,
  "anemia_severity" VARCHAR(50),
  "anemia_type" VARCHAR(100),
  "anemia_morphology" VARCHAR(50),
  "fatigue_present" BOOLEAN DEFAULT FALSE,
  "fatigue_severity" VARCHAR(50),
  "weakness" BOOLEAN DEFAULT FALSE,
  "shortness_of_breath" BOOLEAN DEFAULT FALSE,
  "dizziness" BOOLEAN DEFAULT FALSE,
  "pallor_present" BOOLEAN DEFAULT FALSE,
  "pallor_location" JSONB,
  "pica_present" BOOLEAN DEFAULT FALSE,
  "glossitis" BOOLEAN DEFAULT FALSE,
  "koilonychia" BOOLEAN DEFAULT FALSE,
  "angular_cheilitis" BOOLEAN DEFAULT FALSE,
  "tachycardia_related" BOOLEAN DEFAULT FALSE,
  "anemia_notes" TEXT,

  -- Iron studies
  "serum_iron" DECIMAL(5,0),
  "tibc" DECIMAL(5,0),
  "transferrin_saturation" DECIMAL(5,1),
  "ferritin" DECIMAL(7,1),
  "iron_studies_date" TIMESTAMP,
  "vitamin_b12" DECIMAL(7,0),
  "folate" DECIMAL(6,1),
  "b12_folate_date" TIMESTAMP,

  -- Coagulation assessment
  "pt" DECIMAL(5,1),
  "inr" DECIMAL(4,2),
  "ptt" DECIMAL(5,1),
  "aptt" DECIMAL(5,1),
  "fibrinogen" DECIMAL(5,0),
  "d_dimer" DECIMAL(6,2),
  "coagulation_date" TIMESTAMP,
  "coagulation_status" VARCHAR(50),

  -- Anticoagulation therapy
  "on_anticoagulation" BOOLEAN DEFAULT FALSE,
  "anticoagulant_type" VARCHAR(100),
  "anticoagulant_indication" VARCHAR(255),
  "inr_target_low" DECIMAL(3,1),
  "inr_target_high" DECIMAL(3,1),
  "inr_in_range" BOOLEAN,
  "anticoagulation_notes" TEXT,

  -- Bleeding assessment
  "active_bleeding" BOOLEAN DEFAULT FALSE,
  "bleeding_sites" JSONB,
  "bleeding_severity" VARCHAR(50),
  "bleeding_description" TEXT,
  "bruising_present" BOOLEAN DEFAULT FALSE,
  "bruising_extent" VARCHAR(50),
  "bruising_locations" JSONB,
  "bruising_unexplained" BOOLEAN DEFAULT FALSE,
  "petechiae_present" BOOLEAN DEFAULT FALSE,
  "petechiae_locations" JSONB,
  "ecchymosis_present" BOOLEAN DEFAULT FALSE,
  "hematoma_present" BOOLEAN DEFAULT FALSE,
  "hematoma_locations" TEXT,
  "bleeding_history" TEXT,
  "bleeding_notes" TEXT,

  -- Clotting/thrombosis risk
  "dvt_history" BOOLEAN DEFAULT FALSE,
  "pe_history" BOOLEAN DEFAULT FALSE,
  "current_dvt_pe" BOOLEAN DEFAULT FALSE,
  "thrombosis_location" VARCHAR(255),
  "thrombosis_date" TIMESTAMP,
  "immobility" BOOLEAN DEFAULT FALSE,
  "recent_surgery" BOOLEAN DEFAULT FALSE,
  "malignancy_active" BOOLEAN DEFAULT FALSE,
  "central_line_present" BOOLEAN DEFAULT FALSE,
  "thrombophilia" BOOLEAN DEFAULT FALSE,
  "thrombophilia_type" VARCHAR(255),

  -- Lower extremity assessment
  "leg_swelling" BOOLEAN DEFAULT FALSE,
  "leg_swelling_side" VARCHAR(20),
  "leg_pain" BOOLEAN DEFAULT FALSE,
  "leg_warmth" BOOLEAN DEFAULT FALSE,
  "leg_redness" BOOLEAN DEFAULT FALSE,
  "calf_tenderness" BOOLEAN DEFAULT FALSE,
  "homans_sign" BOOLEAN DEFAULT FALSE,
  "calf_circumference_right" DECIMAL(5,1),
  "calf_circumference_left" DECIMAL(5,1),
  "thrombosis_notes" TEXT,

  -- Lymphatic system
  "lymphadenopathy_present" BOOLEAN DEFAULT FALSE,
  "lymph_node_locations" JSONB,
  "lymph_node_characteristics" VARCHAR(255),
  "lymph_node_size" VARCHAR(100),
  "splenomegaly" BOOLEAN DEFAULT FALSE,
  "spleen_size_cm" DECIMAL(5,1),
  "hepatomegaly" BOOLEAN DEFAULT FALSE,
  "liver_span_cm" DECIMAL(5,1),
  "lymphatic_notes" TEXT,

  -- Transfusion history
  "transfusion_history" BOOLEAN DEFAULT FALSE,
  "last_transfusion_date" TIMESTAMP,
  "last_transfusion_type" VARCHAR(100),
  "transfusion_reactions" BOOLEAN DEFAULT FALSE,
  "transfusion_reaction_type" TEXT,
  "blood_product_refusal" BOOLEAN DEFAULT FALSE,
  "refusal_reason" TEXT,
  "transfusion_notes" TEXT,

  -- Clinical notes and summary
  "clinical_notes" TEXT,
  "assessment_summary" TEXT,
  "follow_up_plan" TEXT,
  "provider_notified" BOOLEAN DEFAULT FALSE,
  "provider_notified_reason" TEXT,

  -- Signature and compliance
  "signature_id" BIGINT,
  "signed_at" TIMESTAMP,
  "signed_by_id" BIGINT,
  "amended" BOOLEAN DEFAULT FALSE,
  "amendment_reason" TEXT,
  "amended_at" TIMESTAMP,
  "amended_by_id" BIGINT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for hematological_system_assessments
CREATE INDEX IF NOT EXISTS "idx_hematological_system_assessments_patient_id" ON "hematological_system_assessments" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_hematological_system_assessments_date" ON "hematological_system_assessments" ("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_hematological_system_assessments_patient_date" ON "hematological_system_assessments" ("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_hematological_system_assessments_status" ON "hematological_system_assessments" ("overall_status");
CREATE INDEX IF NOT EXISTS "idx_hematological_system_assessments_anemia" ON "hematological_system_assessments" ("anemia_present");
CREATE INDEX IF NOT EXISTS "idx_hematological_system_assessments_anticoag" ON "hematological_system_assessments" ("on_anticoagulation");


-- =========================================
-- INTEGUMENTARY SYSTEM ASSESSMENTS
-- =========================================
CREATE TABLE IF NOT EXISTS "integumentary_system_assessments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),
  "encounter_id" BIGINT,
  "note_id" BIGINT,

  -- Assessment metadata
  "assessment_date" TIMESTAMP DEFAULT NOW() NOT NULL,
  "assessment_type" VARCHAR(50),
  "assessed_by_id" BIGINT,

  -- Overall skin status
  "overall_status" VARCHAR(50),
  "skin_history" TEXT,
  "known_conditions" JSONB,

  -- General skin assessment
  "skin_color" VARCHAR(100),
  "skin_color_distribution" VARCHAR(100),
  "abnormal_color_location" TEXT,
  "skin_texture" VARCHAR(100),
  "texture_abnormalities" TEXT,
  "skin_temperature" VARCHAR(50),
  "temperature_distribution" VARCHAR(100),
  "temperature_abnormal_location" TEXT,
  "skin_turgor" VARCHAR(50),
  "turgor_recoil_seconds" DECIMAL(4,1),
  "turgor_test_location" VARCHAR(100),
  "skin_moisture" VARCHAR(50),
  "moisture_distribution" VARCHAR(100),
  "moisture_location" TEXT,
  "xerosis_present" BOOLEAN DEFAULT FALSE,
  "xerosis_severity" VARCHAR(50),
  "skin_intact" BOOLEAN DEFAULT TRUE,
  "integrity_notes" TEXT,
  "skin_general_notes" TEXT,

  -- Braden Scale
  "braden_sensory_perception" INTEGER,
  "braden_moisture" INTEGER,
  "braden_activity" INTEGER,
  "braden_mobility" INTEGER,
  "braden_nutrition" INTEGER,
  "braden_friction_shear" INTEGER,
  "braden_total_score" INTEGER,
  "braden_risk_level" VARCHAR(50),
  "braden_notes" TEXT,

  -- Pressure injury assessment
  "pressure_injury_present" BOOLEAN DEFAULT FALSE,
  "pressure_injury_count" INTEGER,
  "pressure_injuries" JSONB,
  "pi_sacrum" BOOLEAN DEFAULT FALSE,
  "pi_sacrum_stage" VARCHAR(50),
  "pi_coccyx" BOOLEAN DEFAULT FALSE,
  "pi_coccyx_stage" VARCHAR(50),
  "pi_heel_right" BOOLEAN DEFAULT FALSE,
  "pi_heel_right_stage" VARCHAR(50),
  "pi_heel_left" BOOLEAN DEFAULT FALSE,
  "pi_heel_left_stage" VARCHAR(50),
  "pi_ischial_right" BOOLEAN DEFAULT FALSE,
  "pi_ischial_right_stage" VARCHAR(50),
  "pi_ischial_left" BOOLEAN DEFAULT FALSE,
  "pi_ischial_left_stage" VARCHAR(50),
  "pi_trochanter_right" BOOLEAN DEFAULT FALSE,
  "pi_trochanter_right_stage" VARCHAR(50),
  "pi_trochanter_left" BOOLEAN DEFAULT FALSE,
  "pi_trochanter_left_stage" VARCHAR(50),
  "pi_other_locations" TEXT,
  "pressure_injury_notes" TEXT,

  -- Other wounds
  "other_wounds_present" BOOLEAN DEFAULT FALSE,
  "other_wounds" JSONB,
  "skin_tears_present" BOOLEAN DEFAULT FALSE,
  "skin_tear_count" INTEGER,
  "skin_tear_locations" JSONB,
  "skin_tear_type" VARCHAR(100),
  "surgical_wounds_present" BOOLEAN DEFAULT FALSE,
  "surgical_wound_healing" VARCHAR(50),
  "other_wounds_notes" TEXT,

  -- Lesions and skin changes
  "lesions_present" BOOLEAN DEFAULT FALSE,
  "lesion_count" INTEGER,
  "lesions" JSONB,
  "rash_present" BOOLEAN DEFAULT FALSE,
  "rash_type" VARCHAR(100),
  "rash_distribution" VARCHAR(255),
  "rash_characteristics" TEXT,
  "bruising_present" BOOLEAN DEFAULT FALSE,
  "bruising_locations" JSONB,
  "bruising_unexplained" BOOLEAN DEFAULT FALSE,
  "petechiae_present" BOOLEAN DEFAULT FALSE,
  "petechiae_locations" TEXT,
  "skin_cancerous_lesions" BOOLEAN DEFAULT FALSE,
  "cancerous_lesion_details" TEXT,
  "lesions_notes" TEXT,

  -- Edema assessment
  "edema_present" BOOLEAN DEFAULT FALSE,
  "edema_type" VARCHAR(50),
  "edema_severity" VARCHAR(20),
  "edema_locations" JSONB,
  "edema_bilateral" BOOLEAN DEFAULT TRUE,
  "weeping_edema" BOOLEAN DEFAULT FALSE,
  "edema_notes" TEXT,

  -- Hair assessment
  "hair_distribution" VARCHAR(100),
  "hair_texture" VARCHAR(100),
  "hair_loss_pattern" VARCHAR(100),
  "hair_loss_present" BOOLEAN DEFAULT FALSE,
  "hair_loss_cause" VARCHAR(255),
  "scalp_condition" VARCHAR(255),
  "hair_notes" TEXT,
  "leg_hair_present" BOOLEAN DEFAULT TRUE,
  "leg_hair_distribution" VARCHAR(100),

  -- Nail assessment
  "fingernails_condition" VARCHAR(100),
  "fingernails_color" VARCHAR(100),
  "fingernails_shape" VARCHAR(100),
  "fingernails_capillary_refill" DECIMAL(3,1),
  "onychomycosis_fingers" BOOLEAN DEFAULT FALSE,
  "paronychia_fingers" BOOLEAN DEFAULT FALSE,
  "toenails_condition" VARCHAR(100),
  "toenails_color" VARCHAR(100),
  "onychomycosis_toes" BOOLEAN DEFAULT FALSE,
  "ingrown_toenails" BOOLEAN DEFAULT FALSE,
  "ingrown_toenail_location" VARCHAR(255),
  "nails_notes" TEXT,

  -- Diabetic foot assessment
  "diabetic_foot_exam_done" BOOLEAN DEFAULT FALSE,
  "monofilament_test_right" VARCHAR(50),
  "monofilament_test_left" VARCHAR(50),
  "monofilament_sites_tested" INTEGER,
  "monofilament_sites_felt" INTEGER,
  "tuning_fork_test_right" VARCHAR(50),
  "tuning_fork_test_left" VARCHAR(50),
  "ankle_reflexes_right" VARCHAR(50),
  "ankle_reflexes_left" VARCHAR(50),
  "calluses_present" BOOLEAN DEFAULT FALSE,
  "callus_locations" TEXT,
  "foot_deformities" JSONB,
  "diabetic_foot_risk" VARCHAR(50),
  "diabetic_foot_notes" TEXT,

  -- Infection signs
  "infection_signs_present" BOOLEAN DEFAULT FALSE,
  "infection_signs" JSONB,
  "infection_location" TEXT,
  "cellulitis_present" BOOLEAN DEFAULT FALSE,
  "cellulitis_location" TEXT,
  "abscess_present" BOOLEAN DEFAULT FALSE,
  "abscess_location" TEXT,
  "infection_notes" TEXT,

  -- Clinical notes and summary
  "clinical_notes" TEXT,
  "assessment_summary" TEXT,
  "follow_up_plan" TEXT,
  "wound_care_orders" TEXT,
  "provider_notified" BOOLEAN DEFAULT FALSE,
  "provider_notified_reason" TEXT,

  -- Signature and compliance
  "signature_id" BIGINT,
  "signed_at" TIMESTAMP,
  "signed_by_id" BIGINT,
  "amended" BOOLEAN DEFAULT FALSE,
  "amendment_reason" TEXT,
  "amended_at" TIMESTAMP,
  "amended_by_id" BIGINT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for integumentary_system_assessments
CREATE INDEX IF NOT EXISTS "idx_integumentary_system_assessments_patient_id" ON "integumentary_system_assessments" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_integumentary_system_assessments_date" ON "integumentary_system_assessments" ("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_integumentary_system_assessments_patient_date" ON "integumentary_system_assessments" ("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_integumentary_system_assessments_status" ON "integumentary_system_assessments" ("overall_status");
CREATE INDEX IF NOT EXISTS "idx_integumentary_system_assessments_pi" ON "integumentary_system_assessments" ("pressure_injury_present");
CREATE INDEX IF NOT EXISTS "idx_integumentary_system_assessments_braden" ON "integumentary_system_assessments" ("braden_total_score");


-- =========================================
-- RESPIRATORY SYSTEM ASSESSMENTS
-- =========================================
CREATE TABLE IF NOT EXISTS "respiratory_system_assessments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),
  "encounter_id" BIGINT,
  "note_id" BIGINT,

  -- Assessment metadata
  "assessment_date" TIMESTAMP DEFAULT NOW() NOT NULL,
  "assessment_type" VARCHAR(50),
  "assessed_by_id" BIGINT,

  -- Overall respiratory status
  "overall_status" VARCHAR(50),
  "respiratory_history" TEXT,
  "known_conditions" JSONB,

  -- Respiratory rate and pattern
  "respiratory_rate" INTEGER,
  "respiratory_rate_unit" VARCHAR(20) DEFAULT 'breaths/min',
  "respiratory_rhythm" VARCHAR(50),
  "respiratory_pattern" VARCHAR(100),
  "respiratory_depth" VARCHAR(50),
  "respiratory_rate_notes" TEXT,

  -- Respiratory effort
  "respiratory_effort" VARCHAR(50),
  "use_of_accessory_muscles" BOOLEAN DEFAULT FALSE,
  "accessory_muscles_used" JSONB,
  "nasal_flaring" BOOLEAN DEFAULT FALSE,
  "tracheal_tugging" BOOLEAN DEFAULT FALSE,
  "intercostal_retractions" BOOLEAN DEFAULT FALSE,
  "suprasternal_retractions" BOOLEAN DEFAULT FALSE,
  "subcostal_retractions" BOOLEAN DEFAULT FALSE,
  "paradoxical_breathing" BOOLEAN DEFAULT FALSE,
  "tripod_positioning" BOOLEAN DEFAULT FALSE,
  "pursed_lip_breathing" BOOLEAN DEFAULT FALSE,
  "effort_notes" TEXT,

  -- Oxygen saturation
  "spo2_percentage" DECIMAL(5,2),
  "spo2_measurement_site" VARCHAR(50),
  "room_air" BOOLEAN DEFAULT TRUE,
  "supplemental_oxygen" BOOLEAN DEFAULT FALSE,
  "oxygen_flow_rate" DECIMAL(5,2),
  "oxygen_flow_unit" VARCHAR(20) DEFAULT 'L/min',
  "fio2_percentage" DECIMAL(5,2),
  "oxygen_delivery_device" VARCHAR(100),
  "oxygen_saturation_target_low" DECIMAL(4,1),
  "oxygen_saturation_target_high" DECIMAL(4,1),
  "oxygen_continuous_prn" VARCHAR(50),
  "oxygen_notes" TEXT,

  -- Breath sounds - Anterior
  "breath_sounds_right_upper_anterior" VARCHAR(100),
  "breath_sounds_right_middle_anterior" VARCHAR(100),
  "breath_sounds_right_lower_anterior" VARCHAR(100),
  "breath_sounds_left_upper_anterior" VARCHAR(100),
  "breath_sounds_left_lower_anterior" VARCHAR(100),

  -- Breath sounds - Posterior
  "breath_sounds_right_upper_posterior" VARCHAR(100),
  "breath_sounds_right_middle_posterior" VARCHAR(100),
  "breath_sounds_right_lower_posterior" VARCHAR(100),
  "breath_sounds_left_upper_posterior" VARCHAR(100),
  "breath_sounds_left_lower_posterior" VARCHAR(100),

  -- Breath sounds - Lateral
  "breath_sounds_right_lateral" VARCHAR(100),
  "breath_sounds_left_lateral" VARCHAR(100),

  -- General breath sounds
  "breath_sounds_overall" VARCHAR(100),
  "adventitious_sounds" JSONB,
  "adventitious_sounds_timing" VARCHAR(50),
  "breath_sounds_notes" TEXT,

  -- Chest assessment
  "chest_shape" VARCHAR(100),
  "chest_symmetry" VARCHAR(50),
  "chest_expansion" VARCHAR(50),
  "chest_expansion_side" VARCHAR(50),
  "percussion_notes_right" VARCHAR(100),
  "percussion_notes_left" VARCHAR(100),
  "tactile_fremitus_right" VARCHAR(50),
  "tactile_fremitus_left" VARCHAR(50),
  "chest_assessment_notes" TEXT,

  -- Cough assessment
  "cough_present" BOOLEAN DEFAULT FALSE,
  "cough_type" VARCHAR(50),
  "cough_frequency" VARCHAR(50),
  "cough_timing" VARCHAR(100),
  "cough_severity" VARCHAR(50),
  "cough_effectiveness" VARCHAR(50),
  "cough_quality" VARCHAR(255),
  "cough_triggers" TEXT,
  "cough_notes" TEXT,

  -- Sputum assessment
  "sputum_present" BOOLEAN DEFAULT FALSE,
  "sputum_amount" VARCHAR(50),
  "sputum_color" VARCHAR(100),
  "sputum_consistency" VARCHAR(50),
  "sputum_odor" VARCHAR(50),
  "hemoptysis" BOOLEAN DEFAULT FALSE,
  "hemoptysis_amount" VARCHAR(100),
  "sputum_notes" TEXT,

  -- Dyspnea assessment
  "dyspnea_present" BOOLEAN DEFAULT FALSE,
  "dyspnea_severity" VARCHAR(50),
  "dyspnea_scale_used" VARCHAR(100),
  "dyspnea_score" INTEGER,
  "dyspnea_at_rest" BOOLEAN DEFAULT FALSE,
  "dyspnea_with_exertion" BOOLEAN DEFAULT FALSE,
  "dyspnea_onset" VARCHAR(100),
  "dyspnea_duration" VARCHAR(100),
  "orthopnea" BOOLEAN DEFAULT FALSE,
  "orthopnea_pillows" INTEGER,
  "paroxysmal_nocturnal_dyspnea" BOOLEAN DEFAULT FALSE,
  "dyspnea_aggravating_factors" TEXT,
  "dyspnea_relieving_factors" TEXT,
  "dyspnea_notes" TEXT,
  "mmrc_grade" INTEGER,
  "mmrc_description" VARCHAR(255),

  -- Airway management
  "airway_status" VARCHAR(50),
  "artificial_airway" BOOLEAN DEFAULT FALSE,
  "airway_type" VARCHAR(100),
  "tracheostomy_size" VARCHAR(50),
  "tracheostomy_cuff" VARCHAR(50),
  "tracheostomy_cuff_pressure" DECIMAL(4,1),
  "tracheostomy_last_change" TIMESTAMP,
  "tracheostomy_stoma" VARCHAR(100),
  "suctioning_required" BOOLEAN DEFAULT FALSE,
  "suctioning_frequency" VARCHAR(100),
  "secretions_amount" VARCHAR(50),
  "secretions_characteristics" VARCHAR(255),
  "airway_notes" TEXT,

  -- Ventilator settings
  "mechanically_ventilated" BOOLEAN DEFAULT FALSE,
  "ventilator_mode" VARCHAR(100),
  "vent_rate" INTEGER,
  "tidal_volume" INTEGER,
  "fio2_vent" DECIMAL(5,2),
  "peep" DECIMAL(4,1),
  "pressure_support" DECIMAL(4,1),
  "peak_inspiratory_pressure" DECIMAL(4,1),
  "minute_ventilation" DECIMAL(5,2),
  "ventilator_notes" TEXT,

  -- Pulmonary function
  "peak_flow" INTEGER,
  "peak_flow_personal_best" INTEGER,
  "peak_flow_zone" VARCHAR(20),
  "spirometry_available" BOOLEAN DEFAULT FALSE,
  "fev1" DECIMAL(5,2),
  "fev1_percent_predicted" DECIMAL(5,1),
  "fvc" DECIMAL(5,2),
  "fev1_fvc_ratio" DECIMAL(5,2),
  "pulmonary_function_date" TIMESTAMP,
  "pulmonary_function_notes" TEXT,

  -- ABG
  "abg_available" BOOLEAN DEFAULT FALSE,
  "abg_ph" DECIMAL(4,2),
  "abg_pco2" DECIMAL(5,1),
  "abg_po2" DECIMAL(5,1),
  "abg_hco3" DECIMAL(5,1),
  "abg_base_excess" DECIMAL(4,1),
  "abg_sao2" DECIMAL(5,1),
  "abg_interpretation" VARCHAR(255),
  "abg_date" TIMESTAMP,
  "abg_notes" TEXT,

  -- Hospice-specific respiratory
  "death_rattle_present" BOOLEAN DEFAULT FALSE,
  "death_rattle_severity" VARCHAR(50),
  "terminal_secretions" BOOLEAN DEFAULT FALSE,
  "comfort_measures_only" BOOLEAN DEFAULT FALSE,
  "dyspnea_management_goals" TEXT,
  "fan_therapy" BOOLEAN DEFAULT FALSE,
  "positioning_for_comfort" TEXT,
  "hospice_respiratory_notes" TEXT,

  -- Clinical notes and summary
  "clinical_notes" TEXT,
  "assessment_summary" TEXT,
  "follow_up_plan" TEXT,
  "provider_notified" BOOLEAN DEFAULT FALSE,
  "provider_notified_reason" TEXT,

  -- Signature and compliance
  "signature_id" BIGINT,
  "signed_at" TIMESTAMP,
  "signed_by_id" BIGINT,
  "amended" BOOLEAN DEFAULT FALSE,
  "amendment_reason" TEXT,
  "amended_at" TIMESTAMP,
  "amended_by_id" BIGINT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for respiratory_system_assessments
CREATE INDEX IF NOT EXISTS "idx_respiratory_system_assessments_patient_id" ON "respiratory_system_assessments" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_respiratory_system_assessments_date" ON "respiratory_system_assessments" ("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_respiratory_system_assessments_patient_date" ON "respiratory_system_assessments" ("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_respiratory_system_assessments_status" ON "respiratory_system_assessments" ("overall_status");
CREATE INDEX IF NOT EXISTS "idx_respiratory_system_assessments_spo2" ON "respiratory_system_assessments" ("spo2_percentage");
CREATE INDEX IF NOT EXISTS "idx_respiratory_system_assessments_o2" ON "respiratory_system_assessments" ("supplemental_oxygen");
