-- Admin Settings Tables
-- System-wide configuration settings for the hospice EHR system
-- HIPAA-compliant with full audit trail

-- Admin Settings Table
CREATE TABLE IF NOT EXISTS admin_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Setting identification
  setting_key VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,

  -- Setting value
  setting_value TEXT,
  default_value TEXT,

  -- Setting type for validation
  -- Types: STRING, INTEGER, BOOLEAN, JSON, ENCRYPTED, URL, EMAIL, SELECT
  setting_type VARCHAR(50) NOT NULL,

  -- Category for grouping
  -- Categories: SYSTEM, SECURITY, CLEARINGHOUSE, NOTIFICATIONS, INTEGRATION, APPEARANCE
  category VARCHAR(50) NOT NULL,

  -- For SELECT type settings - available options
  options JSONB,

  -- Validation rules
  validation_rules JSONB,

  -- Display order within category
  display_order INTEGER DEFAULT 0,

  -- Flags
  is_sensitive BOOLEAN DEFAULT FALSE,
  requires_restart BOOLEAN DEFAULT FALSE,
  is_readonly BOOLEAN DEFAULT FALSE,

  -- Metadata
  metadata JSONB,

  -- Audit fields
  created_by_id TEXT REFERENCES users(id),
  updated_by_id TEXT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Indexes for admin_settings
CREATE INDEX IF NOT EXISTS idx_admin_settings_key ON admin_settings(setting_key);
CREATE INDEX IF NOT EXISTS idx_admin_settings_category ON admin_settings(category);
CREATE INDEX IF NOT EXISTS idx_admin_settings_type ON admin_settings(setting_type);

-- Admin Settings History Table (Audit Trail)
CREATE TABLE IF NOT EXISTS admin_settings_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Reference to setting
  setting_id BIGINT REFERENCES admin_settings(id) NOT NULL,
  setting_key VARCHAR(100) NOT NULL,

  -- Change details
  previous_value TEXT,
  new_value TEXT,

  -- Change context
  change_reason TEXT,

  -- Session/request context
  ip_address VARCHAR(45),
  user_agent TEXT,
  session_id VARCHAR(255),

  -- Audit fields
  changed_by_id TEXT REFERENCES users(id) NOT NULL,
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Indexes for admin_settings_history
CREATE INDEX IF NOT EXISTS idx_admin_settings_history_setting ON admin_settings_history(setting_id);
CREATE INDEX IF NOT EXISTS idx_admin_settings_history_key ON admin_settings_history(setting_key);
CREATE INDEX IF NOT EXISTS idx_admin_settings_history_user ON admin_settings_history(changed_by_id);
CREATE INDEX IF NOT EXISTS idx_admin_settings_history_date ON admin_settings_history(changed_at);

-- Comment on tables for documentation
COMMENT ON TABLE admin_settings IS 'System-wide configuration settings for the hospice EHR system';
COMMENT ON TABLE admin_settings_history IS 'Audit trail of all settings changes - HIPAA compliant';

-- Comment on important columns
COMMENT ON COLUMN admin_settings.setting_key IS 'Unique key for the setting (e.g., system.timezone)';
COMMENT ON COLUMN admin_settings.setting_type IS 'Type for validation: STRING, INTEGER, BOOLEAN, JSON, ENCRYPTED, URL, EMAIL, SELECT';
COMMENT ON COLUMN admin_settings.category IS 'Category for grouping: SYSTEM, SECURITY, CLEARINGHOUSE, etc.';
COMMENT ON COLUMN admin_settings.is_sensitive IS 'If true, value should be masked in UI and encrypted in storage';
COMMENT ON COLUMN admin_settings.requires_restart IS 'If true, changes require application restart';
COMMENT ON COLUMN admin_settings.is_readonly IS 'If true, cannot be edited via UI';
