-- Migration: Comprehensive Nutrition Assessment System
-- Description: Creates tables for dietary restrictions, food preferences,
-- nutritional intake tracking, and overall nutritional status for hospice patients.

-- =========================================
-- NUTRITION DIETARY RESTRICTIONS
-- =========================================
-- Tracks patient food allergies, intolerances, medical restrictions,
-- and cultural/religious dietary requirements
CREATE TABLE IF NOT EXISTS "nutrition_dietary_restrictions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),

  -- Restriction identification
  "restriction_type" VARCHAR(50) NOT NULL,
  "restriction_category" VARCHAR(100),
  "food_item" VARCHAR(255) NOT NULL,
  "food_group" VARCHAR(100),
  "allergen_code" VARCHAR(50),

  -- Severity and reaction details
  "severity" VARCHAR(50),
  "reaction_type" VARCHAR(255),
  "reaction_description" TEXT,
  "onset_time" VARCHAR(100),
  "last_reaction_date" TIMESTAMP,

  -- Temporal status
  "is_permanent" BOOLEAN DEFAULT TRUE,
  "is_active" BOOLEAN DEFAULT TRUE,
  "effective_date" TIMESTAMP DEFAULT NOW(),
  "expiration_date" TIMESTAMP,
  "review_date" TIMESTAMP,

  -- Medical context
  "diagnosed_by" VARCHAR(255),
  "diagnosis_date" TIMESTAMP,
  "verification_method" VARCHAR(100),
  "medical_condition_related" VARCHAR(255),
  "icd10_code" VARCHAR(20),

  -- Management
  "avoidance_instructions" TEXT,
  "cross_contamination_risk" BOOLEAN DEFAULT FALSE,
  "safe_alternatives" TEXT,
  "emergency_treatment" TEXT,
  "epipen_available" BOOLEAN DEFAULT FALSE,
  "epipen_location" VARCHAR(255),

  -- Notification flags
  "notify_on_admission" BOOLEAN DEFAULT TRUE,
  "notify_dietary" BOOLEAN DEFAULT TRUE,
  "notify_pharmacy" BOOLEAN DEFAULT FALSE,
  "display_on_chart" BOOLEAN DEFAULT TRUE,

  -- Documentation
  "source_of_information" VARCHAR(100),
  "verified" BOOLEAN DEFAULT FALSE,
  "verified_by_id" BIGINT,
  "verified_date" TIMESTAMP,
  "notes" TEXT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for nutrition_dietary_restrictions
CREATE INDEX IF NOT EXISTS "idx_nutrition_dietary_restrictions_patient_id" ON "nutrition_dietary_restrictions" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_nutrition_dietary_restrictions_type" ON "nutrition_dietary_restrictions" ("restriction_type");
CREATE INDEX IF NOT EXISTS "idx_nutrition_dietary_restrictions_food_group" ON "nutrition_dietary_restrictions" ("food_group");
CREATE INDEX IF NOT EXISTS "idx_nutrition_dietary_restrictions_active" ON "nutrition_dietary_restrictions" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_nutrition_dietary_restrictions_severity" ON "nutrition_dietary_restrictions" ("severity");
CREATE INDEX IF NOT EXISTS "idx_nutrition_dietary_restrictions_patient_active" ON "nutrition_dietary_restrictions" ("patient_id", "is_active");


-- =========================================
-- NUTRITION FOOD PREFERENCES
-- =========================================
-- Tracks patient food likes, dislikes, cultural/religious requirements,
-- and meal-related preferences
CREATE TABLE IF NOT EXISTS "nutrition_food_preferences" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),

  -- Preference type and food item
  "preference_type" VARCHAR(50) NOT NULL,
  "preference_category" VARCHAR(100),
  "food_item" VARCHAR(255),
  "food_group" VARCHAR(100),
  "description" TEXT,

  -- Preference strength
  "preference_strength" VARCHAR(50),
  "priority_level" INTEGER DEFAULT 1,
  "is_mandatory" BOOLEAN DEFAULT FALSE,

  -- Cultural/religious requirements
  "cultural_background" VARCHAR(255),
  "religious_requirement" VARCHAR(255),
  "dietary_philosophy" VARCHAR(100),
  "fasting_requirements" TEXT,
  "special_occasions" TEXT,

  -- Texture preferences
  "texture_preference" VARCHAR(100),
  "texture_modifications" TEXT,
  "dysphagia_diet_level" VARCHAR(100),
  "chewing_ability" VARCHAR(100),
  "swallowing_concerns" TEXT,

  -- Temperature preferences
  "temperature_preference" VARCHAR(50),
  "specific_temperature_notes" TEXT,

  -- Seasoning and flavor
  "seasoning_preference" VARCHAR(100),
  "salt_preference" VARCHAR(50),
  "sugar_preference" VARCHAR(50),
  "spice_tolerance" VARCHAR(50),
  "flavor_preferences" TEXT,

  -- Meal preferences
  "preferred_meal_times" TEXT,
  "snack_preferences" TEXT,
  "beverage_preferences" TEXT,
  "portion_size_preference" VARCHAR(50),
  "eating_frequency" VARCHAR(100),

  -- Preparation method
  "preferred_cooking_methods" TEXT,
  "avoided_cooking_methods" TEXT,
  "preparation_notes" TEXT,

  -- Appetite context
  "appetite_notes" TEXT,
  "comfort_foods" TEXT,
  "aversions_during_illness" TEXT,
  "preferences_when_nauseous" TEXT,

  -- Temporal status
  "is_active" BOOLEAN DEFAULT TRUE,
  "effective_date" TIMESTAMP DEFAULT NOW(),
  "last_reviewed_date" TIMESTAMP,
  "preference_changed_date" TIMESTAMP,
  "change_reason" TEXT,

  -- Source
  "source_of_information" VARCHAR(100),
  "reported_by" VARCHAR(255),
  "notes" TEXT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for nutrition_food_preferences
CREATE INDEX IF NOT EXISTS "idx_nutrition_food_preferences_patient_id" ON "nutrition_food_preferences" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_nutrition_food_preferences_type" ON "nutrition_food_preferences" ("preference_type");
CREATE INDEX IF NOT EXISTS "idx_nutrition_food_preferences_active" ON "nutrition_food_preferences" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_nutrition_food_preferences_patient_active" ON "nutrition_food_preferences" ("patient_id", "is_active");
CREATE INDEX IF NOT EXISTS "idx_nutrition_food_preferences_religious" ON "nutrition_food_preferences" ("religious_requirement");


-- =========================================
-- NUTRITION INTAKE RECORDS
-- =========================================
-- Comprehensive tracking of patient nutritional intake including meals,
-- portions, macronutrients, and hydration
CREATE TABLE IF NOT EXISTS "nutrition_intake_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),
  "encounter_id" BIGINT,
  "note_id" BIGINT,

  -- Meal/intake identification
  "intake_datetime" TIMESTAMP DEFAULT NOW() NOT NULL,
  "meal_type" VARCHAR(50) NOT NULL,
  "intake_category" VARCHAR(50),

  -- Food/beverage details
  "food_description" TEXT,
  "beverage_description" TEXT,
  "food_items_json" TEXT,

  -- Portion consumption
  "portion_offered" VARCHAR(50),
  "portion_consumed_percent" INTEGER,
  "portion_consumed_description" VARCHAR(100),
  "solid_food_consumed_percent" INTEGER,
  "liquid_consumed_percent" INTEGER,

  -- Caloric and macronutrient intake
  "calories_estimated" DECIMAL(7,2),
  "calories_unit" VARCHAR(10) DEFAULT 'kcal',
  "protein_grams" DECIMAL(6,2),
  "carbohydrates_grams" DECIMAL(6,2),
  "fat_grams" DECIMAL(6,2),
  "fiber_grams" DECIMAL(5,2),
  "sugar_grams" DECIMAL(6,2),
  "saturated_fat_grams" DECIMAL(5,2),
  "sodium_mg" DECIMAL(7,2),
  "cholesterol_mg" DECIMAL(6,2),

  -- Fluid intake
  "fluid_intake_ml" DECIMAL(7,2),
  "fluid_intake_oz" DECIMAL(6,2),
  "fluid_type" VARCHAR(255),
  "fluid_consistency" VARCHAR(100),
  "ice_chips" BOOLEAN DEFAULT FALSE,
  "ice_chips_amount" VARCHAR(50),

  -- Appetite assessment
  "appetite_level" VARCHAR(50),
  "appetite_compared_to_normal" VARCHAR(50),
  "hunger_reported" BOOLEAN,
  "hunger_cues_observed" TEXT,

  -- Tolerance and symptoms
  "tolerated_well" BOOLEAN DEFAULT TRUE,
  "nausea_present" BOOLEAN DEFAULT FALSE,
  "nausea_severity" VARCHAR(50),
  "vomiting" BOOLEAN DEFAULT FALSE,
  "vomiting_amount" VARCHAR(100),
  "abdominal_discomfort" BOOLEAN DEFAULT FALSE,
  "bloating" BOOLEAN DEFAULT FALSE,
  "reflux" BOOLEAN DEFAULT FALSE,
  "dysphagia_symptoms" BOOLEAN DEFAULT FALSE,
  "choking_episode" BOOLEAN DEFAULT FALSE,
  "aspiration_concern" BOOLEAN DEFAULT FALSE,
  "taste_changes" VARCHAR(255),
  "mouth_sores" BOOLEAN DEFAULT FALSE,
  "dry_mouth" BOOLEAN DEFAULT FALSE,
  "early_satiety" BOOLEAN DEFAULT FALSE,
  "tolerance_notes" TEXT,

  -- Eating environment and context
  "eating_location" VARCHAR(100),
  "eating_position" VARCHAR(100),
  "feeding_method" VARCHAR(100),
  "assistance_level" VARCHAR(50),
  "adaptive_equipment_used" TEXT,

  -- Tube feeding details
  "tube_feeding_formula" VARCHAR(255),
  "tube_feeding_rate" DECIMAL(6,2),
  "tube_feeding_method" VARCHAR(50),
  "tube_type" VARCHAR(100),
  "tube_feeding_residual" DECIMAL(6,2),
  "residual_action_taken" VARCHAR(255),
  "tube_feeding_notes" TEXT,

  -- Parenteral nutrition
  "tpn_formula" VARCHAR(255),
  "tpn_rate" DECIMAL(6,2),
  "tpn_additives" TEXT,
  "lipid_infusion" BOOLEAN DEFAULT FALSE,
  "lipid_rate" DECIMAL(6,2),
  "parenteral_notes" TEXT,

  -- Oral supplements
  "supplement_taken" BOOLEAN DEFAULT FALSE,
  "supplement_name" VARCHAR(255),
  "supplement_amount" VARCHAR(100),
  "supplement_calories" DECIMAL(6,2),
  "supplement_protein" DECIMAL(5,2),
  "supplement_notes" TEXT,

  -- Meal refusal
  "meal_refused" BOOLEAN DEFAULT FALSE,
  "refusal_reason" VARCHAR(255),
  "refusal_details" TEXT,
  "intervention_attempted" BOOLEAN DEFAULT FALSE,
  "intervention_description" TEXT,
  "intervention_outcome" VARCHAR(100),

  -- Timing
  "meal_duration_minutes" INTEGER,
  "time_offered" TIMESTAMP,
  "time_completed" TIMESTAMP,

  -- Documentation
  "documented_by_id" BIGINT,
  "is_shift_summary" BOOLEAN DEFAULT FALSE,
  "shift_period" VARCHAR(50),
  "notes" TEXT,

  -- Signature and compliance
  "signature_id" BIGINT,
  "signed_at" TIMESTAMP,
  "signed_by_id" BIGINT,

  -- Amendment tracking
  "amended" BOOLEAN DEFAULT FALSE,
  "amendment_reason" TEXT,
  "amended_at" TIMESTAMP,
  "amended_by_id" BIGINT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for nutrition_intake_records
CREATE INDEX IF NOT EXISTS "idx_nutrition_intake_records_patient_id" ON "nutrition_intake_records" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_nutrition_intake_records_datetime" ON "nutrition_intake_records" ("intake_datetime");
CREATE INDEX IF NOT EXISTS "idx_nutrition_intake_records_meal_type" ON "nutrition_intake_records" ("meal_type");
CREATE INDEX IF NOT EXISTS "idx_nutrition_intake_records_patient_date" ON "nutrition_intake_records" ("patient_id", "intake_datetime");
CREATE INDEX IF NOT EXISTS "idx_nutrition_intake_records_encounter" ON "nutrition_intake_records" ("encounter_id");
CREATE INDEX IF NOT EXISTS "idx_nutrition_intake_records_refused" ON "nutrition_intake_records" ("meal_refused");


-- =========================================
-- NUTRITION STATUS
-- =========================================
-- Comprehensive tracking of patient nutritional status including anthropometrics,
-- laboratory values, risk assessments, and overall nutritional indicators
CREATE TABLE IF NOT EXISTS "nutrition_status" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" BIGINT NOT NULL REFERENCES "patients"("id"),
  "encounter_id" BIGINT,
  "note_id" BIGINT,

  -- Assessment metadata
  "assessment_date" TIMESTAMP DEFAULT NOW() NOT NULL,
  "assessment_type" VARCHAR(50),
  "assessed_by_id" BIGINT,

  -- Overall nutritional status
  "overall_status" VARCHAR(50),
  "nutritional_diagnosis" TEXT,
  "etiology" TEXT,
  "signs_symptoms" TEXT,

  -- Anthropometric measurements - Height
  "height_cm" DECIMAL(6,2),
  "height_inches" DECIMAL(5,2),
  "height_source" VARCHAR(100),

  -- Current weight
  "weight_kg" DECIMAL(6,2),
  "weight_lbs" DECIMAL(6,2),
  "weight_source" VARCHAR(100),
  "weight_date" TIMESTAMP,

  -- BMI
  "bmi" DECIMAL(5,2),
  "bmi_category" VARCHAR(50),

  -- Ideal and usual body weight
  "ideal_body_weight_kg" DECIMAL(6,2),
  "percent_ideal_body_weight" DECIMAL(5,2),
  "usual_body_weight_kg" DECIMAL(6,2),
  "percent_usual_body_weight" DECIMAL(5,2),

  -- Weight change history
  "weight_change_1_week_kg" DECIMAL(5,2),
  "weight_change_1_week_percent" DECIMAL(5,2),
  "weight_change_1_month_kg" DECIMAL(5,2),
  "weight_change_1_month_percent" DECIMAL(5,2),
  "weight_change_3_month_kg" DECIMAL(6,2),
  "weight_change_3_month_percent" DECIMAL(5,2),
  "weight_change_6_month_kg" DECIMAL(6,2),
  "weight_change_6_month_percent" DECIMAL(5,2),
  "weight_trend" VARCHAR(50),
  "weight_loss_intentional" BOOLEAN,
  "weight_history_notes" TEXT,

  -- Additional anthropometrics
  "waist_circumference_cm" DECIMAL(5,2),
  "hip_circumference_cm" DECIMAL(5,2),
  "waist_hip_ratio" DECIMAL(4,2),
  "mid_arm_circumference_cm" DECIMAL(5,2),
  "calf_circumference_cm" DECIMAL(5,2),
  "triceps_skinfold_mm" DECIMAL(4,2),
  "body_fat_percentage" DECIMAL(5,2),

  -- MNA (Mini Nutritional Assessment)
  "mna_screening_score" INTEGER,
  "mna_assessment_score" INTEGER,
  "mna_total_score" DECIMAL(4,1),
  "mna_category" VARCHAR(50),

  -- MUST (Malnutrition Universal Screening Tool)
  "must_bmi_score" INTEGER,
  "must_weight_loss_score" INTEGER,
  "must_acute_disease_score" INTEGER,
  "must_total_score" INTEGER,
  "must_risk_category" VARCHAR(50),

  -- SGA (Subjective Global Assessment)
  "sga_rating" VARCHAR(50),
  "sga_weight_change" VARCHAR(50),
  "sga_dietary_intake" VARCHAR(50),
  "sga_gi_symptoms" VARCHAR(50),
  "sga_functional_capacity" VARCHAR(50),
  "sga_physical_exam" VARCHAR(50),

  -- Laboratory values
  "albumin_g_dl" DECIMAL(4,2),
  "albumin_date" TIMESTAMP,
  "prealbumin_mg_dl" DECIMAL(5,2),
  "prealbumin_date" TIMESTAMP,
  "transferrin_mg_dl" DECIMAL(5,1),
  "total_protein_g_dl" DECIMAL(4,2),
  "total_lymphocyte_count" DECIMAL(6,1),
  "hemoglobin_g_dl" DECIMAL(4,1),
  "hematocrit_percent" DECIMAL(4,1),
  "cholesterol_mg_dl" INTEGER,
  "triglycerides_mg_dl" INTEGER,
  "blood_glucose_fasting" INTEGER,
  "hba1c" DECIMAL(4,1),
  "bun" DECIMAL(5,1),
  "creatinine" DECIMAL(4,2),
  "sodium" INTEGER,
  "potassium" DECIMAL(4,2),
  "phosphorus" DECIMAL(4,2),
  "magnesium" DECIMAL(4,2),
  "calcium" DECIMAL(4,2),
  "labs_date" TIMESTAMP,
  "lab_notes" TEXT,

  -- Vitamin/mineral deficiencies
  "vitamin_deficiencies_json" TEXT,
  "vitamin_d_level" DECIMAL(5,1),
  "vitamin_b12_level" DECIMAL(6,0),
  "folate_level" DECIMAL(5,1),
  "iron_level" DECIMAL(5,0),
  "ferritin_level" DECIMAL(6,1),
  "zinc_level" DECIMAL(5,1),
  "deficiency_notes" TEXT,

  -- Hydration status
  "hydration_status" VARCHAR(50),
  "dehydration_signs" TEXT,
  "skin_turgor" VARCHAR(50),
  "mucous_membranes" VARCHAR(50),
  "urine_output" VARCHAR(50),
  "fluid_restriction" BOOLEAN DEFAULT FALSE,
  "fluid_restriction_amount_ml" INTEGER,
  "hydration_notes" TEXT,

  -- Physical signs of malnutrition
  "muscle_wasting" BOOLEAN DEFAULT FALSE,
  "muscle_wasting_location" TEXT,
  "subcutaneous_fat_loss" BOOLEAN DEFAULT FALSE,
  "fat_loss_location" TEXT,
  "edema_nutritional" BOOLEAN DEFAULT FALSE,
  "edema_location" TEXT,
  "ascites" BOOLEAN DEFAULT FALSE,
  "hair_changes" BOOLEAN DEFAULT FALSE,
  "hair_changes_description" TEXT,
  "nail_changes" BOOLEAN DEFAULT FALSE,
  "nail_changes_description" TEXT,
  "skin_changes" BOOLEAN DEFAULT FALSE,
  "skin_changes_description" TEXT,
  "oral_changes" BOOLEAN DEFAULT FALSE,
  "oral_changes_description" TEXT,
  "physical_exam_notes" TEXT,

  -- Functional status
  "functional_status" VARCHAR(50),
  "handgrip_strength_kg" DECIMAL(5,2),
  "handgrip_side" VARCHAR(10),
  "activity_level" VARCHAR(50),
  "energy_level" VARCHAR(50),
  "fatigue_level" VARCHAR(50),
  "functional_notes" TEXT,

  -- Nutritional requirements
  "estimated_calorie_needs" INTEGER,
  "calorie_calculation_method" VARCHAR(100),
  "activity_factor" DECIMAL(3,2),
  "stress_factor" DECIMAL(3,2),
  "estimated_protein_needs_g" DECIMAL(5,1),
  "protein_needs_g_per_kg" DECIMAL(3,2),
  "estimated_fluid_needs_ml" INTEGER,
  "requirements_notes" TEXT,

  -- Nutrition goals
  "nutrition_goals" TEXT,
  "weight_goal" VARCHAR(50),
  "weight_goal_target_kg" DECIMAL(6,2),
  "intake_goal" VARCHAR(255),
  "hydration_goal" VARCHAR(255),
  "goal_timeframe" VARCHAR(100),
  "goal_progress" VARCHAR(50),
  "goal_notes" TEXT,

  -- Interventions
  "interventions_json" TEXT,
  "diet_order" VARCHAR(255),
  "diet_texture" VARCHAR(100),
  "fluid_consistency" VARCHAR(100),
  "supplements_ordered" TEXT,
  "tube_feeding_ordered" BOOLEAN DEFAULT FALSE,
  "tpn_ordered" BOOLEAN DEFAULT FALSE,
  "speech_therapy_referral" BOOLEAN DEFAULT FALSE,
  "registered_dietitian_referral" BOOLEAN DEFAULT FALSE,
  "intervention_notes" TEXT,

  -- Hospice-specific considerations
  "comfort_care_focus" BOOLEAN DEFAULT FALSE,
  "artificial_nutrition_discussed" BOOLEAN,
  "artificial_nutrition_decision" VARCHAR(50),
  "patient_family_goals" TEXT,
  "quality_of_life_priority" TEXT,
  "hospice_nutrition_notes" TEXT,

  -- Clinical notes and summary
  "clinical_notes" TEXT,
  "assessment_summary" TEXT,
  "recommendations" TEXT,
  "follow_up_plan" TEXT,
  "next_assessment_date" TIMESTAMP,
  "provider_notified" BOOLEAN DEFAULT FALSE,
  "provider_notified_reason" TEXT,

  -- Signature and compliance
  "signature_id" BIGINT,
  "signed_at" TIMESTAMP,
  "signed_by_id" BIGINT,

  -- Amendment tracking
  "amended" BOOLEAN DEFAULT FALSE,
  "amendment_reason" TEXT,
  "amended_at" TIMESTAMP,
  "amended_by_id" BIGINT,

  -- Audit fields
  "created_by_id" BIGINT,
  "updated_by_id" BIGINT,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Indexes for nutrition_status
CREATE INDEX IF NOT EXISTS "idx_nutrition_status_patient_id" ON "nutrition_status" ("patient_id");
CREATE INDEX IF NOT EXISTS "idx_nutrition_status_assessment_date" ON "nutrition_status" ("assessment_date");
CREATE INDEX IF NOT EXISTS "idx_nutrition_status_patient_date" ON "nutrition_status" ("patient_id", "assessment_date");
CREATE INDEX IF NOT EXISTS "idx_nutrition_status_overall" ON "nutrition_status" ("overall_status");
CREATE INDEX IF NOT EXISTS "idx_nutrition_status_bmi" ON "nutrition_status" ("bmi");
CREATE INDEX IF NOT EXISTS "idx_nutrition_status_mna" ON "nutrition_status" ("mna_category");
CREATE INDEX IF NOT EXISTS "idx_nutrition_status_must" ON "nutrition_status" ("must_risk_category");
