-- Migration: 0043_prognosis_tracking_schema
-- Description: Comprehensive Prognosis Tracking Schema for Hospice Care
--
-- This migration creates tables for tracking patient prognosis information including:
-- - Expected length of stay with date ranges
-- - Disease progression status tracking
-- - Clinical indicators with trend analysis
-- - Full version history for audit compliance
-- - Outcome tracking for quality improvement
--
-- HIPAA Compliance: All tables include audit fields for tracking access and changes

-- ============================================================================
-- PROGNOSIS TRACKING - Main Table
-- ============================================================================
-- Comprehensive prognosis records with temporal tracking and versioning
CREATE TABLE IF NOT EXISTS prognosis_tracking (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),

    -- Version Control
    version INTEGER NOT NULL DEFAULT 1,
    is_current BOOLEAN NOT NULL DEFAULT true,
    previous_version_id BIGINT,
    superseded_at TIMESTAMP,
    superseded_by_id TEXT REFERENCES "user"(id),
    superseded_reason TEXT,

    -- Prognosis Status
    prognosis_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    -- ACTIVE, UNDER_REVIEW, PROVISIONAL, FINALIZED, AMENDED, ARCHIVED

    -- Expected Length of Stay
    admission_date DATE,
    expected_discharge_date DATE,
    expected_length_of_stay_days INTEGER,
    length_of_stay_range_min_days INTEGER,
    length_of_stay_range_max_days INTEGER,
    length_of_stay_confidence_level VARCHAR(50),
    length_of_stay_notes TEXT,

    -- Hospice-specific prognosis fields
    prognosis_months INTEGER,
    prognosis_less_than_6_months BOOLEAN,
    terminal_diagnosis_confirmed BOOLEAN,
    terminal_diagnosis_date DATE,

    -- Disease Progression Status
    disease_progression_status VARCHAR(50) NOT NULL,
    -- IMPROVING, STABLE, SLOWLY_DECLINING, RAPIDLY_DECLINING, DETERIORATING, CRITICAL, ACTIVELY_DYING
    disease_progression_trend VARCHAR(50),
    progression_rate VARCHAR(50),
    progression_since_last_assessment VARCHAR(50),
    disease_progression_notes TEXT,

    -- Clinical Indicators - Vital Signs
    vital_signs_trend VARCHAR(50),
    vital_signs_summary JSONB,
    vital_signs_last_assessment_date TIMESTAMP,

    -- Clinical Indicators - Lab Values
    lab_values_summary JSONB,
    lab_values_trend VARCHAR(50),
    lab_values_last_date DATE,

    -- Clinical Indicators - Functional Status
    functional_status_score INTEGER,
    functional_status_scale VARCHAR(50),
    functional_status_trend VARCHAR(50),
    previous_functional_score INTEGER,
    functional_status_date DATE,
    functional_status_notes TEXT,

    -- PPS (Palliative Performance Scale) fields
    pps_ambulation VARCHAR(100),
    pps_activity_evidence_of_disease VARCHAR(100),
    pps_self_care VARCHAR(100),
    pps_intake VARCHAR(100),
    pps_conscious_level VARCHAR(100),

    -- Diagnosis Information
    primary_diagnosis_icd10 VARCHAR(20),
    primary_diagnosis_description TEXT,
    secondary_diagnoses JSONB,
    comorbidities JSONB,
    diagnosis_related_prognosis_factors TEXT,

    -- Symptom Burden
    symptom_burden_score INTEGER,
    symptom_burden_level VARCHAR(50),
    primary_symptoms JSONB,
    symptom_management_effectiveness VARCHAR(50),

    -- Imminence of Death Indicators
    is_imminently_dying BOOLEAN DEFAULT false,
    imminence_level VARCHAR(50),
    imminence_indicators JSONB,
    imminence_assessment_date TIMESTAMP,
    days_to_death_estimate INTEGER,
    hours_to_death_estimate INTEGER,

    -- Patient/Family Awareness
    patient_awareness_of_prognosis VARCHAR(50),
    family_awareness_of_prognosis VARCHAR(50),
    prognosis_discussion_date DATE,
    prognosis_discussed_with JSONB,
    goals_of_care_aligned BOOLEAN,
    goals_of_care_notes TEXT,

    -- Confidence and Uncertainty
    overall_confidence_level VARCHAR(50),
    confidence_percentage INTEGER,
    uncertainty_factors JSONB,
    prediction_model_used VARCHAR(100),
    surprise_question_response VARCHAR(50),

    -- Complications
    complications JSONB,
    unexpected_events TEXT,
    prognosis_modifying_factors JSONB,

    -- Review and Reassessment
    last_review_date TIMESTAMP,
    next_review_date TIMESTAMP,
    review_frequency_days INTEGER,
    review_notes TEXT,
    requires_idg_review BOOLEAN DEFAULT false,
    idg_review_date DATE,
    idg_review_outcome TEXT,

    -- Clinical Notes
    clinical_summary TEXT,
    prognosis_rationale TEXT,
    treatment_response TEXT,
    additional_notes TEXT,

    -- Electronic Signature (21 CFR Part 11)
    signature JSONB,
    signed_at TIMESTAMP,
    signed_by_id TEXT REFERENCES "user"(id),
    cosignature JSONB,
    cosigned_at TIMESTAMP,
    cosigned_by_id TEXT REFERENCES "user"(id),
    requires_physician_signature BOOLEAN DEFAULT true,
    physician_signature_date DATE,

    -- Audit Fields (HIPAA Compliance)
    created_by_id TEXT REFERENCES "user"(id),
    updated_by_id TEXT REFERENCES "user"(id),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Self-reference for version history
ALTER TABLE prognosis_tracking
ADD CONSTRAINT fk_prognosis_tracking_previous_version
FOREIGN KEY (previous_version_id) REFERENCES prognosis_tracking(id);

-- Indexes for prognosis_tracking
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_patient_id ON prognosis_tracking(patient_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_status ON prognosis_tracking(prognosis_status);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_is_current ON prognosis_tracking(is_current);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_progression ON prognosis_tracking(disease_progression_status);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_imminent ON prognosis_tracking(is_imminently_dying);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_patient_current ON prognosis_tracking(patient_id, is_current);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_patient_version ON prognosis_tracking(patient_id, version);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_patient_created ON prognosis_tracking(patient_id, created_at);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_progression_trend ON prognosis_tracking(disease_progression_status, disease_progression_trend);
CREATE INDEX IF NOT EXISTS idx_prognosis_tracking_review_date ON prognosis_tracking(next_review_date);

-- ============================================================================
-- PROGNOSIS HISTORY - Audit Trail
-- ============================================================================
-- Immutable records for compliance and analysis
CREATE TABLE IF NOT EXISTS prognosis_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prognosis_tracking_id BIGINT NOT NULL REFERENCES prognosis_tracking(id),
    patient_id BIGINT NOT NULL REFERENCES patients(id),

    -- Change tracking
    change_type VARCHAR(50) NOT NULL,
    -- CREATE, UPDATE, STATUS_CHANGE, PROGRESSION_CHANGE, REVIEW, SIGNATURE, ARCHIVE
    change_date TIMESTAMP NOT NULL DEFAULT NOW(),
    changed_by_id TEXT REFERENCES "user"(id),
    changed_by_name VARCHAR(255),
    changed_by_role VARCHAR(100),

    -- Previous and new values
    field_changed VARCHAR(100),
    previous_value TEXT,
    new_value TEXT,
    change_reason TEXT,

    -- Snapshot
    snapshot JSONB,

    -- Clinical context
    clinical_context TEXT,
    triggering_event VARCHAR(255),

    -- Audit fields
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for prognosis_history
CREATE INDEX IF NOT EXISTS idx_prognosis_history_prognosis_id ON prognosis_history(prognosis_tracking_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_history_patient_id ON prognosis_history(patient_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_history_change_date ON prognosis_history(change_date);
CREATE INDEX IF NOT EXISTS idx_prognosis_history_change_type ON prognosis_history(change_type);
CREATE INDEX IF NOT EXISTS idx_prognosis_history_changed_by ON prognosis_history(changed_by_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_history_patient_date ON prognosis_history(patient_id, change_date);

-- ============================================================================
-- PROGNOSIS CLINICAL INDICATORS - Detailed Tracking
-- ============================================================================
-- Supports trend analysis over time
CREATE TABLE IF NOT EXISTS prognosis_clinical_indicators (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prognosis_tracking_id BIGINT NOT NULL REFERENCES prognosis_tracking(id),
    patient_id BIGINT NOT NULL REFERENCES patients(id),

    -- Indicator identification
    indicator_type VARCHAR(50) NOT NULL,
    -- VITAL_SIGN, LAB_VALUE, FUNCTIONAL_SCORE, SYMPTOM, WEIGHT, NUTRITION, COGNITION
    indicator_name VARCHAR(100) NOT NULL,
    indicator_code VARCHAR(50),

    -- Measurement
    measurement_date TIMESTAMP NOT NULL,
    value_numeric DECIMAL(10, 4),
    value_text VARCHAR(255),
    value_unit VARCHAR(50),

    -- Reference ranges
    normal_range_low DECIMAL(10, 4),
    normal_range_high DECIMAL(10, 4),
    critical_range_low DECIMAL(10, 4),
    critical_range_high DECIMAL(10, 4),
    is_abnormal BOOLEAN DEFAULT false,
    is_critical BOOLEAN DEFAULT false,
    abnormality_direction VARCHAR(20),

    -- Trend analysis
    trend_direction VARCHAR(50),
    trend_rate VARCHAR(50),
    previous_value DECIMAL(10, 4),
    change_percentage DECIMAL(6, 2),
    days_since_previous INTEGER,

    -- Clinical significance
    clinical_significance VARCHAR(50),
    prognosis_impact VARCHAR(50),
    notes TEXT,

    -- Source
    source_system VARCHAR(100),
    source_record_id VARCHAR(255),
    recorded_by_id TEXT REFERENCES "user"(id),

    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for prognosis_clinical_indicators
CREATE INDEX IF NOT EXISTS idx_prognosis_indicators_prognosis_id ON prognosis_clinical_indicators(prognosis_tracking_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_indicators_patient_id ON prognosis_clinical_indicators(patient_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_indicators_type ON prognosis_clinical_indicators(indicator_type);
CREATE INDEX IF NOT EXISTS idx_prognosis_indicators_date ON prognosis_clinical_indicators(measurement_date);
CREATE INDEX IF NOT EXISTS idx_prognosis_indicators_abnormal ON prognosis_clinical_indicators(is_abnormal);
CREATE INDEX IF NOT EXISTS idx_prognosis_indicators_critical ON prognosis_clinical_indicators(is_critical);
CREATE INDEX IF NOT EXISTS idx_prognosis_indicators_patient_type_date ON prognosis_clinical_indicators(patient_id, indicator_type, measurement_date);

-- ============================================================================
-- PROGNOSIS OUTCOMES - Retrospective Analysis
-- ============================================================================
-- Links prognoses to actual outcomes for quality improvement
CREATE TABLE IF NOT EXISTS prognosis_outcomes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prognosis_tracking_id BIGINT NOT NULL REFERENCES prognosis_tracking(id),
    patient_id BIGINT NOT NULL REFERENCES patients(id),

    -- Outcome details
    outcome_type VARCHAR(50) NOT NULL,
    -- DEATH, DISCHARGE_ALIVE, TRANSFER, REVOCATION, ONGOING
    outcome_date DATE,
    outcome_location VARCHAR(100),

    -- Prognosis accuracy analysis
    prognosis_date DATE NOT NULL,
    predicted_los_days INTEGER,
    actual_los_days INTEGER,
    los_variance_days INTEGER,
    los_accuracy_category VARCHAR(50),

    predicted_imminence_level VARCHAR(50),
    actual_time_to_outcome_days INTEGER,
    imminence_accuracy_category VARCHAR(50),

    -- Quality metrics
    symptom_management_at_end VARCHAR(50),
    family_satisfaction VARCHAR(50),
    goals_achieved BOOLEAN,
    unexpected_events_occurred BOOLEAN,
    unexpected_events_description TEXT,

    -- Analysis notes
    analysis_notes TEXT,
    lessons_learned TEXT,
    analyzed_by_id TEXT REFERENCES "user"(id),
    analysis_date TIMESTAMP,

    -- Audit fields
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for prognosis_outcomes
CREATE INDEX IF NOT EXISTS idx_prognosis_outcomes_prognosis_id ON prognosis_outcomes(prognosis_tracking_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_outcomes_patient_id ON prognosis_outcomes(patient_id);
CREATE INDEX IF NOT EXISTS idx_prognosis_outcomes_type ON prognosis_outcomes(outcome_type);
CREATE INDEX IF NOT EXISTS idx_prognosis_outcomes_date ON prognosis_outcomes(outcome_date);
CREATE INDEX IF NOT EXISTS idx_prognosis_outcomes_accuracy ON prognosis_outcomes(los_accuracy_category);

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================
COMMENT ON TABLE prognosis_tracking IS 'Comprehensive prognosis tracking with version control and temporal tracking capabilities for hospice patients';
COMMENT ON TABLE prognosis_history IS 'Immutable audit trail of all prognosis changes for HIPAA compliance and retrospective analysis';
COMMENT ON TABLE prognosis_clinical_indicators IS 'Detailed clinical indicator tracking with trend analysis for prognosis assessment';
COMMENT ON TABLE prognosis_outcomes IS 'Outcome tracking for retrospective analysis and quality improvement of prognosis predictions';

COMMENT ON COLUMN prognosis_tracking.disease_progression_status IS 'Current disease progression status: IMPROVING, STABLE, SLOWLY_DECLINING, RAPIDLY_DECLINING, DETERIORATING, CRITICAL, ACTIVELY_DYING';
COMMENT ON COLUMN prognosis_tracking.is_current IS 'Indicates if this is the current active prognosis record for the patient (only one per patient should be true)';
COMMENT ON COLUMN prognosis_tracking.functional_status_scale IS 'Scale used for functional assessment: PPS (Palliative Performance Scale), KPS (Karnofsky), ECOG, ADL, IADL';
COMMENT ON COLUMN prognosis_tracking.imminence_level IS 'Estimated time until death: MONTHS, WEEKS, DAYS, HOURS';
COMMENT ON COLUMN prognosis_tracking.surprise_question_response IS 'Response to "Would you be surprised if this patient died in the next year?": YES_SURPRISED, NO_NOT_SURPRISED, UNCERTAIN';
