-- Migration: ASC 606 Revenue Recognition Schema
-- Module: Revenue Recognition - ASC 606 Five-Step Model Compliance
-- Created: 2025-12-31
-- Purpose: Implement FASB ASC 606 compliant revenue recognition with daily accrual calculations

-- ============================================
-- TABLE 1: ASC 606 CONTRACTS
-- Step 1: Identify the contract with a customer
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_contracts" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Contract reference
  "billing_contract_id" bigint REFERENCES "contracts"("id"),
  "payer_id" bigint NOT NULL REFERENCES "payers"("id"),
  "patient_id" bigint REFERENCES "patients"("id"),

  -- Contract identification
  "contract_number" varchar(100) NOT NULL,
  "contract_name" varchar(255),
  "contract_type" varchar(50) NOT NULL, -- SERVICE_AGREEMENT, CAPITATION, FEE_FOR_SERVICE, BUNDLED_PAYMENT

  -- Contract period
  "contract_start_date" date NOT NULL,
  "contract_end_date" date,
  "is_evergreen" boolean DEFAULT false,

  -- Contract value (in cents)
  "total_contract_value" bigint,
  "estimated_contract_value" bigint,
  "currency" varchar(3) DEFAULT 'USD',

  -- ASC 606 Step 1 Criteria
  "criteria_approval_commitment" boolean DEFAULT false,
  "criteria_rights_identified" boolean DEFAULT false,
  "criteria_payment_terms_identified" boolean DEFAULT false,
  "criteria_commercial_substance" boolean DEFAULT false,
  "criteria_collection_probable" boolean DEFAULT false,

  -- Contract validation
  "is_valid_asc606_contract" boolean DEFAULT false,
  "validation_date" timestamp,
  "validation_notes" text,

  -- Contract status
  "contract_status" varchar(50) NOT NULL DEFAULT 'DRAFT',

  -- Collectibility
  "collectibility_probability" bigint DEFAULT 10000, -- Basis points 0-10000
  "collectibility_assessment_date" date,
  "collectibility_notes" text,

  -- Financing component
  "has_financing_component" boolean DEFAULT false,
  "financing_rate" bigint, -- Basis points

  -- Non-cash consideration
  "has_non_cash_consideration" boolean DEFAULT false,
  "non_cash_consideration_value" bigint,
  "non_cash_consideration_description" text,

  -- Time zone
  "contract_timezone" varchar(50) DEFAULT 'America/New_York',

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "deleted_at" timestamp
);

COMMENT ON TABLE "asc606_contracts" IS 'ASC 606 Step 1: Contract identification and validation for revenue recognition';

-- ============================================
-- TABLE 2: PERFORMANCE OBLIGATIONS
-- Step 2: Identify the performance obligations
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_performance_obligations" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Contract reference
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),

  -- Obligation identification
  "obligation_number" varchar(50) NOT NULL,
  "obligation_name" varchar(255) NOT NULL,
  "obligation_description" text,

  -- Type
  "obligation_type" varchar(50) NOT NULL,

  -- Distinctiveness
  "is_distinct" boolean DEFAULT true,
  "is_separately_identifiable" boolean DEFAULT true,
  "distinctiveness_notes" text,

  -- Satisfaction pattern
  "satisfaction_pattern" varchar(50) NOT NULL,
  "recognition_pattern" varchar(50) NOT NULL,

  -- Standalone selling price (in cents)
  "standalone_selling_price" bigint,
  "ssp_method" varchar(50),

  -- Allocation
  "allocated_price" bigint,
  "allocation_percentage" bigint, -- Basis points

  -- Period
  "obligation_start_date" date NOT NULL,
  "obligation_end_date" date,
  "expected_duration_days" bigint,

  -- Status
  "satisfaction_status" varchar(50) NOT NULL DEFAULT 'NOT_STARTED',
  "satisfaction_percentage" bigint DEFAULT 0, -- Basis points
  "satisfaction_date" date,

  -- Revenue (in cents)
  "total_recognized" bigint DEFAULT 0,
  "total_deferred" bigint DEFAULT 0,

  -- Measurement
  "output_measure_unit" varchar(50),
  "total_expected_outputs" bigint,
  "total_delivered_outputs" bigint DEFAULT 0,

  -- Series guidance
  "is_series" boolean DEFAULT false,
  "series_increment" varchar(50),

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "updated_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_performance_obligations" IS 'ASC 606 Step 2: Performance obligations for distinct goods/services in contracts';

-- ============================================
-- TABLE 3: TRANSACTION PRICES
-- Step 3: Determine the transaction price
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_transaction_prices" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Contract reference
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),

  -- Version tracking
  "version" bigint NOT NULL DEFAULT 1,
  "effective_date" date NOT NULL,
  "superseded_date" date,
  "is_current" boolean DEFAULT true,

  -- Fixed consideration (in cents)
  "fixed_consideration" bigint NOT NULL,

  -- Variable consideration
  "has_variable_consideration" boolean DEFAULT false,
  "variable_consideration_estimate" bigint,
  "variable_consideration_method" varchar(50),

  -- Constraint
  "constraint_applied" boolean DEFAULT false,
  "constrained_amount" bigint,
  "constraint_reason" text,

  -- Total (in cents)
  "total_transaction_price" bigint NOT NULL,

  -- Adjustments
  "financing_adjustment" bigint,
  "non_cash_fair_value" bigint,
  "consideration_payable_to_customer" bigint,

  -- Calculation
  "calculation_method" text,
  "calculation_assumptions" jsonb,

  -- Approval
  "approved" boolean DEFAULT false,
  "approved_by_id" text REFERENCES "user"("id"),
  "approved_at" timestamp,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_transaction_prices" IS 'ASC 606 Step 3: Transaction price determination including variable consideration';

-- ============================================
-- TABLE 4: VARIABLE CONSIDERATION
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_variable_consideration" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- References
  "transaction_price_id" bigint NOT NULL REFERENCES "asc606_transaction_prices"("id"),
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),

  -- Type
  "consideration_type" varchar(50) NOT NULL,
  "consideration_name" varchar(255) NOT NULL,
  "description" text,

  -- Estimation
  "estimation_method" varchar(50) NOT NULL,
  "probability_scenarios" jsonb,
  "most_likely_amount" bigint,
  "alternative_outcomes" jsonb,

  -- Amounts (in cents)
  "estimated_amount" bigint NOT NULL,

  -- Constraint
  "is_constrained" boolean DEFAULT false,
  "constraint_factors" jsonb,
  "constrained_amount" bigint,
  "constraint_release_date" date,

  -- Reversal assessment
  "reversal_probability" bigint, -- Basis points
  "reversal_impact_if_occurs" bigint,

  -- Re-estimation
  "requires_reestimation" boolean DEFAULT true,
  "reestimation_frequency" varchar(50),
  "last_reestimated_at" timestamp,
  "next_reestimation_date" date,

  -- Resolution
  "is_resolved" boolean DEFAULT false,
  "resolved_date" date,
  "resolved_amount" bigint,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_variable_consideration" IS 'Variable consideration components with constraint assessment per ASC 606-10-32';

-- ============================================
-- TABLE 5: PRICE ALLOCATIONS
-- Step 4: Allocate transaction price to obligations
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_price_allocations" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- References
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),
  "transaction_price_id" bigint NOT NULL REFERENCES "asc606_transaction_prices"("id"),
  "obligation_id" bigint NOT NULL REFERENCES "asc606_performance_obligations"("id"),

  -- Version
  "version" bigint NOT NULL DEFAULT 1,
  "effective_date" date NOT NULL,
  "is_current" boolean DEFAULT true,

  -- Standalone selling price (in cents)
  "standalone_selling_price" bigint NOT NULL,
  "ssp_determination_method" varchar(50) NOT NULL,
  "ssp_observable_source" text,
  "ssp_adjustments" jsonb,

  -- Relative SSP
  "relative_ssp_percentage" bigint NOT NULL, -- Basis points

  -- Allocation (in cents)
  "allocated_amount" bigint NOT NULL,

  -- Discount
  "discount_amount" bigint,
  "discount_allocation_method" varchar(50),

  -- Variable consideration
  "variable_consideration_allocated" bigint,
  "variable_consideration_allocation_method" varchar(50),

  -- Daily rate
  "daily_accrual_rate" bigint, -- In cents per day

  -- Calculation
  "calculation_workpaper" jsonb,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_price_allocations" IS 'ASC 606 Step 4: Allocation of transaction price to performance obligations based on relative SSP';

-- ============================================
-- TABLE 6: DAILY REVENUE ACCRUALS
-- Step 5: Recognize revenue as obligations are satisfied
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_daily_revenue_accruals" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- References
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),
  "obligation_id" bigint NOT NULL REFERENCES "asc606_performance_obligations"("id"),
  "allocation_id" bigint REFERENCES "asc606_price_allocations"("id"),
  "claim_id" bigint REFERENCES "claims"("id"),
  "patient_id" bigint REFERENCES "patients"("id"),

  -- Date
  "accrual_date" date NOT NULL,
  "fiscal_year" bigint NOT NULL,
  "fiscal_quarter" bigint NOT NULL,
  "fiscal_month" bigint NOT NULL,
  "period_label" varchar(7) NOT NULL,

  -- Day-specific
  "is_leap_year" boolean DEFAULT false,
  "days_in_month" bigint NOT NULL,
  "is_partial_period" boolean DEFAULT false,

  -- Recognition pattern
  "recognition_pattern" varchar(50) NOT NULL,

  -- Amounts (in cents)
  "base_daily_rate" bigint NOT NULL,
  "adjustment_factor" bigint DEFAULT 10000, -- Basis points
  "adjusted_daily_amount" bigint NOT NULL,

  -- Pro-rata
  "prorate_numerator" bigint,
  "prorate_denominator" bigint,
  "prorated_amount" bigint,

  -- Cumulative (in cents)
  "cumulative_recognized" bigint NOT NULL,
  "remaining_to_recognize" bigint NOT NULL,
  "satisfaction_percentage" bigint NOT NULL, -- Basis points

  -- Usage-based
  "units_delivered" bigint,
  "unit_rate" bigint,

  -- Milestone
  "milestone_achieved" boolean DEFAULT false,
  "milestone_name" varchar(255),
  "milestone_amount" bigint,

  -- Status
  "status" varchar(50) NOT NULL DEFAULT 'CALCULATED',
  "posted_to_gl" boolean DEFAULT false,
  "gl_posting_date" date,
  "gl_journal_entry_id" varchar(50),

  -- Calculation metadata
  "calculation_timestamp" timestamp NOT NULL,
  "calculation_version" bigint DEFAULT 1,
  "calculation_source" varchar(50),

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_daily_revenue_accruals" IS 'ASC 606 Step 5: Daily revenue recognition tracking with full audit trail';

-- ============================================
-- TABLE 7: CONTRACT MODIFICATIONS
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_contract_modifications" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Contract reference
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),

  -- Identification
  "modification_number" varchar(50) NOT NULL,
  "modification_date" date NOT NULL,
  "effective_date" date NOT NULL,

  -- Type
  "modification_type" varchar(50) NOT NULL,

  -- Details
  "modification_description" text,
  "scope_change" text,
  "price_change" text,

  -- Before (in cents)
  "previous_total_price" bigint,
  "previous_remaining_price" bigint,
  "previous_satisfaction_percentage" bigint,

  -- After (in cents)
  "new_total_price" bigint,
  "price_change_amount" bigint,

  -- Catch-up
  "requires_catch_up" boolean DEFAULT false,
  "catch_up_amount" bigint,
  "catch_up_recognized_date" date,

  -- New/terminated obligations
  "adds_new_obligations" boolean DEFAULT false,
  "new_obligations" jsonb,
  "terminates_obligations" boolean DEFAULT false,
  "terminated_obligations" jsonb,

  -- Reallocation
  "requires_reallocation" boolean DEFAULT false,
  "reallocation_method" varchar(50),

  -- Status
  "modification_status" varchar(50) NOT NULL DEFAULT 'PENDING',
  "approved_by_id" text REFERENCES "user"("id"),
  "approved_at" timestamp,
  "applied_at" timestamp,

  -- Documentation
  "supporting_documentation" jsonb,
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_contract_modifications" IS 'Contract amendments and modifications per ASC 606-10-25-10 through 25-13';

-- ============================================
-- TABLE 8: REVENUE SCHEDULES
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_revenue_schedules" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- References
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),
  "obligation_id" bigint NOT NULL REFERENCES "asc606_performance_obligations"("id"),

  -- Version
  "schedule_version" bigint NOT NULL DEFAULT 1,
  "is_current" boolean DEFAULT true,
  "generated_at" timestamp NOT NULL,

  -- Period
  "schedule_start_date" date NOT NULL,
  "schedule_end_date" date NOT NULL,
  "total_days" bigint NOT NULL,

  -- Pattern
  "recognition_pattern" varchar(50) NOT NULL,

  -- Amounts (in cents)
  "total_to_recognize" bigint NOT NULL,
  "recognized_to_date" bigint DEFAULT 0,
  "remaining_to_recognize" bigint NOT NULL,
  "base_daily_rate" bigint NOT NULL,

  -- Calendar
  "calendar_adjustments" jsonb,
  "monthly_schedule" jsonb,

  -- Status
  "schedule_status" varchar(50) NOT NULL DEFAULT 'ACTIVE',
  "superseded_by_id" bigint,
  "superseded_date" date,
  "superseded_reason" text,

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_revenue_schedules" IS 'Pre-calculated revenue recognition schedules for contracts';

-- ============================================
-- TABLE 9: DEFERRALS
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_deferrals" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- References
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),
  "obligation_id" bigint REFERENCES "asc606_performance_obligations"("id"),
  "daily_accrual_id" bigint REFERENCES "asc606_daily_revenue_accruals"("id"),

  -- Type
  "deferral_type" varchar(50) NOT NULL,

  -- Details
  "deferral_date" date NOT NULL,
  "amount" bigint NOT NULL,
  "reason" text NOT NULL,

  -- Period
  "period_label" varchar(7) NOT NULL,
  "fiscal_year" bigint NOT NULL,
  "fiscal_quarter" bigint NOT NULL,

  -- Release
  "expected_release_date" date,
  "release_pattern" varchar(50),

  -- Status
  "status" varchar(50) NOT NULL DEFAULT 'DEFERRED',
  "released_amount" bigint DEFAULT 0,
  "remaining_amount" bigint NOT NULL,
  "releases" jsonb,

  -- GL
  "posted_to_gl" boolean DEFAULT false,
  "gl_account" varchar(50),
  "gl_journal_entry_id" varchar(50),

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_deferrals" IS 'Deferred revenue, contract assets/liabilities tracking';

-- ============================================
-- TABLE 10: CALCULATION AUDIT TRAIL
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_calculation_audit" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- References
  "contract_id" bigint NOT NULL REFERENCES "asc606_contracts"("id"),
  "obligation_id" bigint REFERENCES "asc606_performance_obligations"("id"),
  "daily_accrual_id" bigint REFERENCES "asc606_daily_revenue_accruals"("id"),

  -- Event
  "event_type" varchar(50) NOT NULL,
  "event_date" date NOT NULL,
  "event_timestamp" timestamp NOT NULL,
  "event_description" text NOT NULL,

  -- State tracking
  "before_state" jsonb,
  "after_state" jsonb,

  -- Change
  "change_amount" bigint,
  "change_reason" text,

  -- Calculation
  "calculation_inputs" jsonb,
  "calculation_formula" text,
  "calculation_result" jsonb,

  -- System
  "system_version" varchar(50),
  "calculation_engine_version" varchar(50),

  -- Trigger
  "trigger_source" varchar(50),
  "trigger_reference_id" varchar(100),

  -- Metadata (immutable)
  "metadata" jsonb,

  -- Audit - NO updated_at for immutability
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_calculation_audit" IS 'Immutable audit trail for all revenue recognition calculations';

-- ============================================
-- TABLE 11: RECONCILIATION
-- ============================================
CREATE TABLE IF NOT EXISTS "asc606_reconciliation" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Period
  "period_label" varchar(7) NOT NULL UNIQUE,
  "fiscal_year" bigint NOT NULL,
  "fiscal_quarter" bigint NOT NULL,

  -- Amounts (in cents)
  "total_recognized_revenue" bigint NOT NULL,
  "total_billed_revenue" bigint NOT NULL,
  "variance_amount" bigint NOT NULL,
  "variance_percentage" bigint, -- Basis points

  -- Breakdown
  "deferred_revenue_beginning" bigint,
  "deferred_revenue_ending" bigint,
  "unbilled_receivables_beginning" bigint,
  "unbilled_receivables_ending" bigint,
  "contract_assets" bigint,
  "contract_liabilities" bigint,

  -- Items
  "reconciliation_items" jsonb,

  -- Status
  "status" varchar(50) NOT NULL DEFAULT 'DRAFT',
  "is_reconciled" boolean DEFAULT false,
  "reconciled_at" timestamp,
  "reconciled_by_id" text REFERENCES "user"("id"),

  -- Approval
  "approved" boolean DEFAULT false,
  "approved_by_id" text REFERENCES "user"("id"),
  "approved_at" timestamp,

  -- Variance
  "variance_explanation" text,
  "requires_adjustment" boolean DEFAULT false,
  "adjustment_journal_entry_id" varchar(50),

  -- Metadata
  "metadata" jsonb,
  "notes" text,

  -- Audit
  "created_by_id" text REFERENCES "user"("id"),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

COMMENT ON TABLE "asc606_reconciliation" IS 'Period reconciliation between recognized revenue and billing/invoicing';

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

-- ASC606 Contracts indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_contracts_number" ON "asc606_contracts"("contract_number");
CREATE INDEX IF NOT EXISTS "idx_asc606_contracts_payer" ON "asc606_contracts"("payer_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_contracts_patient" ON "asc606_contracts"("patient_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_contracts_status" ON "asc606_contracts"("contract_status");
CREATE INDEX IF NOT EXISTS "idx_asc606_contracts_date_range" ON "asc606_contracts"("contract_start_date", "contract_end_date");

-- Performance Obligations indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_po_contract" ON "asc606_performance_obligations"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_po_status" ON "asc606_performance_obligations"("satisfaction_status");
CREATE INDEX IF NOT EXISTS "idx_asc606_po_type" ON "asc606_performance_obligations"("obligation_type");
CREATE INDEX IF NOT EXISTS "idx_asc606_po_date_range" ON "asc606_performance_obligations"("obligation_start_date", "obligation_end_date");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_asc606_po_contract_number" ON "asc606_performance_obligations"("contract_id", "obligation_number");

-- Transaction Prices indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_tp_contract" ON "asc606_transaction_prices"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_tp_current" ON "asc606_transaction_prices"("contract_id", "is_current");
CREATE INDEX IF NOT EXISTS "idx_asc606_tp_effective" ON "asc606_transaction_prices"("effective_date");

-- Variable Consideration indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_vc_transaction_price" ON "asc606_variable_consideration"("transaction_price_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_vc_contract" ON "asc606_variable_consideration"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_vc_type" ON "asc606_variable_consideration"("consideration_type");
CREATE INDEX IF NOT EXISTS "idx_asc606_vc_resolved" ON "asc606_variable_consideration"("is_resolved");

-- Price Allocations indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_pa_contract" ON "asc606_price_allocations"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_pa_obligation" ON "asc606_price_allocations"("obligation_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_pa_current" ON "asc606_price_allocations"("contract_id", "is_current");
CREATE INDEX IF NOT EXISTS "idx_asc606_pa_transaction_price" ON "asc606_price_allocations"("transaction_price_id");

-- Daily Revenue Accruals indexes (critical for performance)
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_contract_date" ON "asc606_daily_revenue_accruals"("contract_id", "accrual_date");
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_obligation_date" ON "asc606_daily_revenue_accruals"("obligation_id", "accrual_date");
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_date" ON "asc606_daily_revenue_accruals"("accrual_date");
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_period" ON "asc606_daily_revenue_accruals"("period_label");
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_fiscal" ON "asc606_daily_revenue_accruals"("fiscal_year", "fiscal_quarter", "fiscal_month");
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_status" ON "asc606_daily_revenue_accruals"("status");
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_gl_posting" ON "asc606_daily_revenue_accruals"("posted_to_gl");
CREATE INDEX IF NOT EXISTS "idx_asc606_dra_patient_date" ON "asc606_daily_revenue_accruals"("patient_id", "accrual_date");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_asc606_dra_unique" ON "asc606_daily_revenue_accruals"("contract_id", "obligation_id", "accrual_date");

-- Contract Modifications indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_cm_contract" ON "asc606_contract_modifications"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_cm_effective_date" ON "asc606_contract_modifications"("effective_date");
CREATE INDEX IF NOT EXISTS "idx_asc606_cm_status" ON "asc606_contract_modifications"("modification_status");
CREATE INDEX IF NOT EXISTS "idx_asc606_cm_type" ON "asc606_contract_modifications"("modification_type");

-- Revenue Schedules indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_rs_contract" ON "asc606_revenue_schedules"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_rs_obligation" ON "asc606_revenue_schedules"("obligation_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_rs_current" ON "asc606_revenue_schedules"("contract_id", "obligation_id", "is_current");
CREATE INDEX IF NOT EXISTS "idx_asc606_rs_status" ON "asc606_revenue_schedules"("schedule_status");

-- Deferrals indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_def_contract" ON "asc606_deferrals"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_def_obligation" ON "asc606_deferrals"("obligation_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_def_type" ON "asc606_deferrals"("deferral_type");
CREATE INDEX IF NOT EXISTS "idx_asc606_def_period" ON "asc606_deferrals"("period_label");
CREATE INDEX IF NOT EXISTS "idx_asc606_def_status" ON "asc606_deferrals"("status");
CREATE INDEX IF NOT EXISTS "idx_asc606_def_release_date" ON "asc606_deferrals"("expected_release_date");

-- Calculation Audit indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_audit_contract" ON "asc606_calculation_audit"("contract_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_audit_obligation" ON "asc606_calculation_audit"("obligation_id");
CREATE INDEX IF NOT EXISTS "idx_asc606_audit_event_date" ON "asc606_calculation_audit"("event_date");
CREATE INDEX IF NOT EXISTS "idx_asc606_audit_event_type" ON "asc606_calculation_audit"("event_type");
CREATE INDEX IF NOT EXISTS "idx_asc606_audit_timestamp" ON "asc606_calculation_audit"("event_timestamp");

-- Reconciliation indexes
CREATE INDEX IF NOT EXISTS "idx_asc606_recon_fiscal" ON "asc606_reconciliation"("fiscal_year", "fiscal_quarter");
CREATE INDEX IF NOT EXISTS "idx_asc606_recon_status" ON "asc606_reconciliation"("status");
